// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/gw_socket_close.proto

package gateway // import "github.com/duckchat/duckchat-gateway/proto/gateway"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GwSocketCloseRequest struct {
	SocketIds            []string `protobuf:"bytes,1,rep,name=socketIds,proto3" json:"socketIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwSocketCloseRequest) Reset()         { *m = GwSocketCloseRequest{} }
func (m *GwSocketCloseRequest) String() string { return proto.CompactTextString(m) }
func (*GwSocketCloseRequest) ProtoMessage()    {}
func (*GwSocketCloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_socket_close_54896e43b4aef0d2, []int{0}
}
func (m *GwSocketCloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwSocketCloseRequest.Unmarshal(m, b)
}
func (m *GwSocketCloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwSocketCloseRequest.Marshal(b, m, deterministic)
}
func (dst *GwSocketCloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwSocketCloseRequest.Merge(dst, src)
}
func (m *GwSocketCloseRequest) XXX_Size() int {
	return xxx_messageInfo_GwSocketCloseRequest.Size(m)
}
func (m *GwSocketCloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GwSocketCloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GwSocketCloseRequest proto.InternalMessageInfo

func (m *GwSocketCloseRequest) GetSocketIds() []string {
	if m != nil {
		return m.SocketIds
	}
	return nil
}

type GwSocketCloseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwSocketCloseResponse) Reset()         { *m = GwSocketCloseResponse{} }
func (m *GwSocketCloseResponse) String() string { return proto.CompactTextString(m) }
func (*GwSocketCloseResponse) ProtoMessage()    {}
func (*GwSocketCloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_socket_close_54896e43b4aef0d2, []int{1}
}
func (m *GwSocketCloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwSocketCloseResponse.Unmarshal(m, b)
}
func (m *GwSocketCloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwSocketCloseResponse.Marshal(b, m, deterministic)
}
func (dst *GwSocketCloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwSocketCloseResponse.Merge(dst, src)
}
func (m *GwSocketCloseResponse) XXX_Size() int {
	return xxx_messageInfo_GwSocketCloseResponse.Size(m)
}
func (m *GwSocketCloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GwSocketCloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GwSocketCloseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GwSocketCloseRequest)(nil), "gateway.GwSocketCloseRequest")
	proto.RegisterType((*GwSocketCloseResponse)(nil), "gateway.GwSocketCloseResponse")
}

func init() {
	proto.RegisterFile("gateway/gw_socket_close.proto", fileDescriptor_gw_socket_close_54896e43b4aef0d2)
}

var fileDescriptor_gw_socket_close_54896e43b4aef0d2 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x4f, 0x2f, 0x8f, 0x2f, 0xce, 0x4f, 0xce, 0x4e, 0x2d, 0x89, 0x4f, 0xce,
	0xc9, 0x2f, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x4a, 0x2b, 0x99, 0x70,
	0x89, 0xb8, 0x97, 0x07, 0x83, 0x15, 0x38, 0x83, 0xe4, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x64, 0xb8, 0x38, 0x21, 0xda, 0x3c, 0x53, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83,
	0x10, 0x02, 0x4a, 0xe2, 0x5c, 0xa2, 0x68, 0xba, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x9d, 0x12,
	0xb9, 0xc4, 0x92, 0xf3, 0x73, 0xf5, 0xaa, 0x12, 0x73, 0x2a, 0x21, 0x36, 0xe9, 0x41, 0x2d, 0x8a,
	0x32, 0x4a, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x29, 0x4d, 0xce,
	0x4e, 0xce, 0x48, 0x2c, 0x81, 0x33, 0x74, 0x61, 0xae, 0x05, 0xeb, 0xd1, 0x87, 0xf2, 0x4e, 0x31,
	0x09, 0x45, 0x25, 0xe6, 0x54, 0xc6, 0x04, 0x80, 0x04, 0x63, 0xdc, 0x21, 0x82, 0x49, 0x6c, 0x60,
	0x35, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x19, 0x60, 0x01, 0xe2, 0x00, 0x00, 0x00,
}
