// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/gw_socket_write.proto

package gateway // import "github.com/duckchat/duckchat-gateway/proto/gateway"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GwSocketWritePackage struct {
	SocketIds            []string `protobuf:"bytes,1,rep,name=socketIds,proto3" json:"socketIds,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwSocketWritePackage) Reset()         { *m = GwSocketWritePackage{} }
func (m *GwSocketWritePackage) String() string { return proto.CompactTextString(m) }
func (*GwSocketWritePackage) ProtoMessage()    {}
func (*GwSocketWritePackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_socket_write_860111385519574b, []int{0}
}
func (m *GwSocketWritePackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwSocketWritePackage.Unmarshal(m, b)
}
func (m *GwSocketWritePackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwSocketWritePackage.Marshal(b, m, deterministic)
}
func (dst *GwSocketWritePackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwSocketWritePackage.Merge(dst, src)
}
func (m *GwSocketWritePackage) XXX_Size() int {
	return xxx_messageInfo_GwSocketWritePackage.Size(m)
}
func (m *GwSocketWritePackage) XXX_DiscardUnknown() {
	xxx_messageInfo_GwSocketWritePackage.DiscardUnknown(m)
}

var xxx_messageInfo_GwSocketWritePackage proto.InternalMessageInfo

func (m *GwSocketWritePackage) GetSocketIds() []string {
	if m != nil {
		return m.SocketIds
	}
	return nil
}

func (m *GwSocketWritePackage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// *
//
// error:
//      error.offline    the sockeid if offline.
type GwSocketWriteRequest struct {
	Packages             []*GwSocketWritePackage `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GwSocketWriteRequest) Reset()         { *m = GwSocketWriteRequest{} }
func (m *GwSocketWriteRequest) String() string { return proto.CompactTextString(m) }
func (*GwSocketWriteRequest) ProtoMessage()    {}
func (*GwSocketWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_socket_write_860111385519574b, []int{1}
}
func (m *GwSocketWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwSocketWriteRequest.Unmarshal(m, b)
}
func (m *GwSocketWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwSocketWriteRequest.Marshal(b, m, deterministic)
}
func (dst *GwSocketWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwSocketWriteRequest.Merge(dst, src)
}
func (m *GwSocketWriteRequest) XXX_Size() int {
	return xxx_messageInfo_GwSocketWriteRequest.Size(m)
}
func (m *GwSocketWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GwSocketWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GwSocketWriteRequest proto.InternalMessageInfo

func (m *GwSocketWriteRequest) GetPackages() []*GwSocketWritePackage {
	if m != nil {
		return m.Packages
	}
	return nil
}

type GwSocketWriteResponse struct {
	Length               int32    `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwSocketWriteResponse) Reset()         { *m = GwSocketWriteResponse{} }
func (m *GwSocketWriteResponse) String() string { return proto.CompactTextString(m) }
func (*GwSocketWriteResponse) ProtoMessage()    {}
func (*GwSocketWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_socket_write_860111385519574b, []int{2}
}
func (m *GwSocketWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwSocketWriteResponse.Unmarshal(m, b)
}
func (m *GwSocketWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwSocketWriteResponse.Marshal(b, m, deterministic)
}
func (dst *GwSocketWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwSocketWriteResponse.Merge(dst, src)
}
func (m *GwSocketWriteResponse) XXX_Size() int {
	return xxx_messageInfo_GwSocketWriteResponse.Size(m)
}
func (m *GwSocketWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GwSocketWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GwSocketWriteResponse proto.InternalMessageInfo

func (m *GwSocketWriteResponse) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*GwSocketWritePackage)(nil), "gateway.GwSocketWritePackage")
	proto.RegisterType((*GwSocketWriteRequest)(nil), "gateway.GwSocketWriteRequest")
	proto.RegisterType((*GwSocketWriteResponse)(nil), "gateway.GwSocketWriteResponse")
}

func init() {
	proto.RegisterFile("gateway/gw_socket_write.proto", fileDescriptor_gw_socket_write_860111385519574b)
}

var fileDescriptor_gw_socket_write_860111385519574b = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x4f, 0x2f, 0x8f, 0x2f, 0xce, 0x4f, 0xce, 0x4e, 0x2d, 0x89, 0x2f, 0x2f,
	0xca, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x4a, 0x2b, 0xf9, 0x71,
	0x89, 0xb8, 0x97, 0x07, 0x83, 0x15, 0x84, 0x83, 0xe4, 0x03, 0x12, 0x93, 0xb3, 0x13, 0xd3, 0x53,
	0x85, 0x64, 0xb8, 0x38, 0x21, 0xda, 0x3c, 0x53, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83,
	0x10, 0x02, 0x42, 0x12, 0x5c, 0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x3c, 0x41, 0x30, 0xae, 0x52, 0x20, 0x9a, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x96, 0x5c, 0x1c, 0x05, 0x10, 0xa3, 0x21, 0xc6, 0x71, 0x1b, 0xc9, 0xea, 0x41, 0xdd,
	0xa0, 0x87, 0xcd, 0x01, 0x41, 0x70, 0xe5, 0x4a, 0xfa, 0x5c, 0xa2, 0x68, 0x46, 0x16, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0xe5, 0xa4, 0xe6, 0xa5, 0x97, 0x64, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x4e, 0x89, 0x5c, 0x62, 0xc9, 0xf9, 0xb9, 0x7a, 0x55, 0x89,
	0x39, 0x95, 0x10, 0xef, 0xc2, 0x6c, 0x8a, 0x32, 0x4a, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b,
	0xce, 0xcf, 0xd5, 0x4f, 0x29, 0x4d, 0xce, 0x4e, 0xce, 0x48, 0x2c, 0x81, 0x33, 0x74, 0x61, 0x41,
	0x06, 0xd6, 0xa3, 0x0f, 0xe5, 0x9d, 0x62, 0x12, 0x8a, 0x4a, 0xcc, 0xa9, 0x8c, 0x09, 0x00, 0x09,
	0xc6, 0xb8, 0x43, 0x04, 0x93, 0xd8, 0xc0, 0x6a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4,
	0x91, 0x45, 0x10, 0x67, 0x01, 0x00, 0x00,
}
