// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/message.proto

package core // import "github.com/duckchat/duckchat-gateway/proto/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageRoomType int32

const (
	MessageRoomType_MessageRoomGroup MessageRoomType = 0
	MessageRoomType_MessageRoomU2    MessageRoomType = 1
)

var MessageRoomType_name = map[int32]string{
	0: "MessageRoomGroup",
	1: "MessageRoomU2",
}
var MessageRoomType_value = map[string]int32{
	"MessageRoomGroup": 0,
	"MessageRoomU2":    1,
}

func (x MessageRoomType) String() string {
	return proto.EnumName(MessageRoomType_name, int32(x))
}
func (MessageRoomType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{0}
}

type MessageStatus int32

const (
	MessageStatus_MessageStatusUnsent  MessageStatus = 0
	MessageStatus_MessageStatusSending MessageStatus = 1
	MessageStatus_MessageStatusFailed  MessageStatus = 3
	MessageStatus_MessageStatusServer  MessageStatus = 4
)

var MessageStatus_name = map[int32]string{
	0: "MessageStatusUnsent",
	1: "MessageStatusSending",
	3: "MessageStatusFailed",
	4: "MessageStatusServer",
}
var MessageStatus_value = map[string]int32{
	"MessageStatusUnsent":  0,
	"MessageStatusSending": 1,
	"MessageStatusFailed":  3,
	"MessageStatusServer":  4,
}

func (x MessageStatus) String() string {
	return proto.EnumName(MessageStatus_name, int32(x))
}
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{1}
}

type MessageType int32

const (
	MessageType_MessageInvalid   MessageType = 0
	MessageType_MessageNotice    MessageType = 1
	MessageType_MessageText      MessageType = 2
	MessageType_MessageImage     MessageType = 3
	MessageType_MessageAudio     MessageType = 4
	MessageType_MessageWeb       MessageType = 5
	MessageType_MessageWebNotice MessageType = 6
	// event message start
	MessageType_MessageEventFriendRequest MessageType = 20
	MessageType_MessageEventStatus        MessageType = 21
	MessageType_MessageEventSyncEnd       MessageType = 22
)

var MessageType_name = map[int32]string{
	0:  "MessageInvalid",
	1:  "MessageNotice",
	2:  "MessageText",
	3:  "MessageImage",
	4:  "MessageAudio",
	5:  "MessageWeb",
	6:  "MessageWebNotice",
	20: "MessageEventFriendRequest",
	21: "MessageEventStatus",
	22: "MessageEventSyncEnd",
}
var MessageType_value = map[string]int32{
	"MessageInvalid":            0,
	"MessageNotice":             1,
	"MessageText":               2,
	"MessageImage":              3,
	"MessageAudio":              4,
	"MessageWeb":                5,
	"MessageWebNotice":          6,
	"MessageEventFriendRequest": 20,
	"MessageEventStatus":        21,
	"MessageEventSyncEnd":       22,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{2}
}

type NoticeMessage struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeMessage) Reset()         { *m = NoticeMessage{} }
func (m *NoticeMessage) String() string { return proto.CompactTextString(m) }
func (*NoticeMessage) ProtoMessage()    {}
func (*NoticeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{0}
}
func (m *NoticeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeMessage.Unmarshal(m, b)
}
func (m *NoticeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeMessage.Marshal(b, m, deterministic)
}
func (dst *NoticeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeMessage.Merge(dst, src)
}
func (m *NoticeMessage) XXX_Size() int {
	return xxx_messageInfo_NoticeMessage.Size(m)
}
func (m *NoticeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeMessage proto.InternalMessageInfo

func (m *NoticeMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type WebNoticeMessage struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	HrefURL              string   `protobuf:"bytes,3,opt,name=hrefURL,proto3" json:"hrefURL,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebNoticeMessage) Reset()         { *m = WebNoticeMessage{} }
func (m *WebNoticeMessage) String() string { return proto.CompactTextString(m) }
func (*WebNoticeMessage) ProtoMessage()    {}
func (*WebNoticeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{1}
}
func (m *WebNoticeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebNoticeMessage.Unmarshal(m, b)
}
func (m *WebNoticeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebNoticeMessage.Marshal(b, m, deterministic)
}
func (dst *WebNoticeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebNoticeMessage.Merge(dst, src)
}
func (m *WebNoticeMessage) XXX_Size() int {
	return xxx_messageInfo_WebNoticeMessage.Size(m)
}
func (m *WebNoticeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebNoticeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebNoticeMessage proto.InternalMessageInfo

func (m *WebNoticeMessage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WebNoticeMessage) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *WebNoticeMessage) GetHrefURL() string {
	if m != nil {
		return m.HrefURL
	}
	return ""
}

func (m *WebNoticeMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TextMessage struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextMessage) Reset()         { *m = TextMessage{} }
func (m *TextMessage) String() string { return proto.CompactTextString(m) }
func (*TextMessage) ProtoMessage()    {}
func (*TextMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{2}
}
func (m *TextMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextMessage.Unmarshal(m, b)
}
func (m *TextMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextMessage.Marshal(b, m, deterministic)
}
func (dst *TextMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextMessage.Merge(dst, src)
}
func (m *TextMessage) XXX_Size() int {
	return xxx_messageInfo_TextMessage.Size(m)
}
func (m *TextMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TextMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TextMessage proto.InternalMessageInfo

func (m *TextMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ImageMessage struct {
	// url or fileId
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageMessage) Reset()         { *m = ImageMessage{} }
func (m *ImageMessage) String() string { return proto.CompactTextString(m) }
func (*ImageMessage) ProtoMessage()    {}
func (*ImageMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{3}
}
func (m *ImageMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageMessage.Unmarshal(m, b)
}
func (m *ImageMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageMessage.Marshal(b, m, deterministic)
}
func (dst *ImageMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageMessage.Merge(dst, src)
}
func (m *ImageMessage) XXX_Size() int {
	return xxx_messageInfo_ImageMessage.Size(m)
}
func (m *ImageMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ImageMessage proto.InternalMessageInfo

func (m *ImageMessage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ImageMessage) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImageMessage) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type AudioMessage struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Time                 int32    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioMessage) Reset()         { *m = AudioMessage{} }
func (m *AudioMessage) String() string { return proto.CompactTextString(m) }
func (*AudioMessage) ProtoMessage()    {}
func (*AudioMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{4}
}
func (m *AudioMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioMessage.Unmarshal(m, b)
}
func (m *AudioMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioMessage.Marshal(b, m, deterministic)
}
func (dst *AudioMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioMessage.Merge(dst, src)
}
func (m *AudioMessage) XXX_Size() int {
	return xxx_messageInfo_AudioMessage.Size(m)
}
func (m *AudioMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AudioMessage proto.InternalMessageInfo

func (m *AudioMessage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AudioMessage) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type WebMessage struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	HrefURL              string   `protobuf:"bytes,4,opt,name=hrefURL,proto3" json:"hrefURL,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebMessage) Reset()         { *m = WebMessage{} }
func (m *WebMessage) String() string { return proto.CompactTextString(m) }
func (*WebMessage) ProtoMessage()    {}
func (*WebMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{5}
}
func (m *WebMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebMessage.Unmarshal(m, b)
}
func (m *WebMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebMessage.Marshal(b, m, deterministic)
}
func (dst *WebMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebMessage.Merge(dst, src)
}
func (m *WebMessage) XXX_Size() int {
	return xxx_messageInfo_WebMessage.Size(m)
}
func (m *WebMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebMessage proto.InternalMessageInfo

func (m *WebMessage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WebMessage) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *WebMessage) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *WebMessage) GetHrefURL() string {
	if m != nil {
		return m.HrefURL
	}
	return ""
}

func (m *WebMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type StatusMessage struct {
	MsgId  string        `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Status MessageStatus `protobuf:"varint,2,opt,name=status,proto3,enum=core.MessageStatus" json:"status,omitempty"`
	// whether this is a request.
	IsReq                bool     `protobuf:"varint,3,opt,name=isReq,proto3" json:"isReq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{6}
}
func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (dst *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(dst, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *StatusMessage) GetStatus() MessageStatus {
	if m != nil {
		return m.Status
	}
	return MessageStatus_MessageStatusUnsent
}

func (m *StatusMessage) GetIsReq() bool {
	if m != nil {
		return m.IsReq
	}
	return false
}

type SyncEndMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncEndMessage) Reset()         { *m = SyncEndMessage{} }
func (m *SyncEndMessage) String() string { return proto.CompactTextString(m) }
func (*SyncEndMessage) ProtoMessage()    {}
func (*SyncEndMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{7}
}
func (m *SyncEndMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncEndMessage.Unmarshal(m, b)
}
func (m *SyncEndMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncEndMessage.Marshal(b, m, deterministic)
}
func (dst *SyncEndMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncEndMessage.Merge(dst, src)
}
func (m *SyncEndMessage) XXX_Size() int {
	return xxx_messageInfo_SyncEndMessage.Size(m)
}
func (m *SyncEndMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncEndMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SyncEndMessage proto.InternalMessageInfo

type Message struct {
	// basic info
	MsgId      string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	FromUserId string `protobuf:"bytes,2,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	Pointer    int64  `protobuf:"varint,3,opt,name=pointer,proto3" json:"pointer,omitempty"`
	TimeServer int64  `protobuf:"varint,4,opt,name=timeServer,proto3" json:"timeServer,omitempty"`
	// type info
	RoomType MessageRoomType `protobuf:"varint,5,opt,name=roomType,proto3,enum=core.MessageRoomType" json:"roomType,omitempty"`
	// Types that are valid to be assigned to ToRoom:
	//	*Message_ToUserId
	//	*Message_ToGroupId
	ToRoom isMessage_ToRoom `protobuf_oneof:"toRoom"`
	// body info
	Type MessageType `protobuf:"varint,8,opt,name=type,proto3,enum=core.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Maybe:
	//	*Message_Text
	//	*Message_Image
	//	*Message_Audio
	//	*Message_Web
	//	*Message_Status
	//	*Message_Notice
	//	*Message_WebNotice
	Maybe isMessage_Maybe `protobuf_oneof:"maybe"`
	// reverts 15-50
	TreatPointerAsU2Pointer bool     `protobuf:"varint,51,opt,name=treatPointerAsU2Pointer,proto3" json:"treatPointerAsU2Pointer,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_414fdb4eecac552a, []int{8}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_ToRoom interface {
	isMessage_ToRoom()
}
type isMessage_Maybe interface {
	isMessage_Maybe()
}

type Message_ToUserId struct {
	ToUserId string `protobuf:"bytes,6,opt,name=toUserId,proto3,oneof"`
}
type Message_ToGroupId struct {
	ToGroupId string `protobuf:"bytes,7,opt,name=toGroupId,proto3,oneof"`
}
type Message_Text struct {
	Text *TextMessage `protobuf:"bytes,9,opt,name=text,proto3,oneof"`
}
type Message_Image struct {
	Image *ImageMessage `protobuf:"bytes,10,opt,name=image,proto3,oneof"`
}
type Message_Audio struct {
	Audio *AudioMessage `protobuf:"bytes,11,opt,name=audio,proto3,oneof"`
}
type Message_Web struct {
	Web *WebMessage `protobuf:"bytes,12,opt,name=web,proto3,oneof"`
}
type Message_Status struct {
	Status *StatusMessage `protobuf:"bytes,13,opt,name=status,proto3,oneof"`
}
type Message_Notice struct {
	Notice *NoticeMessage `protobuf:"bytes,14,opt,name=notice,proto3,oneof"`
}
type Message_WebNotice struct {
	WebNotice *WebNoticeMessage `protobuf:"bytes,15,opt,name=webNotice,proto3,oneof"`
}

func (*Message_ToUserId) isMessage_ToRoom()  {}
func (*Message_ToGroupId) isMessage_ToRoom() {}
func (*Message_Text) isMessage_Maybe()       {}
func (*Message_Image) isMessage_Maybe()      {}
func (*Message_Audio) isMessage_Maybe()      {}
func (*Message_Web) isMessage_Maybe()        {}
func (*Message_Status) isMessage_Maybe()     {}
func (*Message_Notice) isMessage_Maybe()     {}
func (*Message_WebNotice) isMessage_Maybe()  {}

func (m *Message) GetToRoom() isMessage_ToRoom {
	if m != nil {
		return m.ToRoom
	}
	return nil
}
func (m *Message) GetMaybe() isMessage_Maybe {
	if m != nil {
		return m.Maybe
	}
	return nil
}

func (m *Message) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Message) GetFromUserId() string {
	if m != nil {
		return m.FromUserId
	}
	return ""
}

func (m *Message) GetPointer() int64 {
	if m != nil {
		return m.Pointer
	}
	return 0
}

func (m *Message) GetTimeServer() int64 {
	if m != nil {
		return m.TimeServer
	}
	return 0
}

func (m *Message) GetRoomType() MessageRoomType {
	if m != nil {
		return m.RoomType
	}
	return MessageRoomType_MessageRoomGroup
}

func (m *Message) GetToUserId() string {
	if x, ok := m.GetToRoom().(*Message_ToUserId); ok {
		return x.ToUserId
	}
	return ""
}

func (m *Message) GetToGroupId() string {
	if x, ok := m.GetToRoom().(*Message_ToGroupId); ok {
		return x.ToGroupId
	}
	return ""
}

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_MessageInvalid
}

func (m *Message) GetText() *TextMessage {
	if x, ok := m.GetMaybe().(*Message_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Message) GetImage() *ImageMessage {
	if x, ok := m.GetMaybe().(*Message_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Message) GetAudio() *AudioMessage {
	if x, ok := m.GetMaybe().(*Message_Audio); ok {
		return x.Audio
	}
	return nil
}

func (m *Message) GetWeb() *WebMessage {
	if x, ok := m.GetMaybe().(*Message_Web); ok {
		return x.Web
	}
	return nil
}

func (m *Message) GetStatus() *StatusMessage {
	if x, ok := m.GetMaybe().(*Message_Status); ok {
		return x.Status
	}
	return nil
}

func (m *Message) GetNotice() *NoticeMessage {
	if x, ok := m.GetMaybe().(*Message_Notice); ok {
		return x.Notice
	}
	return nil
}

func (m *Message) GetWebNotice() *WebNoticeMessage {
	if x, ok := m.GetMaybe().(*Message_WebNotice); ok {
		return x.WebNotice
	}
	return nil
}

func (m *Message) GetTreatPointerAsU2Pointer() bool {
	if m != nil {
		return m.TreatPointerAsU2Pointer
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_ToUserId)(nil),
		(*Message_ToGroupId)(nil),
		(*Message_Text)(nil),
		(*Message_Image)(nil),
		(*Message_Audio)(nil),
		(*Message_Web)(nil),
		(*Message_Status)(nil),
		(*Message_Notice)(nil),
		(*Message_WebNotice)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// toRoom
	switch x := m.ToRoom.(type) {
	case *Message_ToUserId:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ToUserId)
	case *Message_ToGroupId:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ToGroupId)
	case nil:
	default:
		return fmt.Errorf("Message.ToRoom has unexpected type %T", x)
	}
	// maybe
	switch x := m.Maybe.(type) {
	case *Message_Text:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Text); err != nil {
			return err
		}
	case *Message_Image:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Image); err != nil {
			return err
		}
	case *Message_Audio:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Audio); err != nil {
			return err
		}
	case *Message_Web:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Web); err != nil {
			return err
		}
	case *Message_Status:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Status); err != nil {
			return err
		}
	case *Message_Notice:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Notice); err != nil {
			return err
		}
	case *Message_WebNotice:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WebNotice); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Maybe has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 6: // toRoom.toUserId
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ToRoom = &Message_ToUserId{x}
		return true, err
	case 7: // toRoom.toGroupId
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ToRoom = &Message_ToGroupId{x}
		return true, err
	case 9: // maybe.text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TextMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_Text{msg}
		return true, err
	case 10: // maybe.image
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ImageMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_Image{msg}
		return true, err
	case 11: // maybe.audio
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AudioMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_Audio{msg}
		return true, err
	case 12: // maybe.web
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WebMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_Web{msg}
		return true, err
	case 13: // maybe.status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StatusMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_Status{msg}
		return true, err
	case 14: // maybe.notice
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NoticeMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_Notice{msg}
		return true, err
	case 15: // maybe.webNotice
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WebNoticeMessage)
		err := b.DecodeMessage(msg)
		m.Maybe = &Message_WebNotice{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// toRoom
	switch x := m.ToRoom.(type) {
	case *Message_ToUserId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ToUserId)))
		n += len(x.ToUserId)
	case *Message_ToGroupId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ToGroupId)))
		n += len(x.ToGroupId)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// maybe
	switch x := m.Maybe.(type) {
	case *Message_Text:
		s := proto.Size(x.Text)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Image:
		s := proto.Size(x.Image)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Audio:
		s := proto.Size(x.Audio)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Web:
		s := proto.Size(x.Web)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Status:
		s := proto.Size(x.Status)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Notice:
		s := proto.Size(x.Notice)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_WebNotice:
		s := proto.Size(x.WebNotice)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*NoticeMessage)(nil), "core.NoticeMessage")
	proto.RegisterType((*WebNoticeMessage)(nil), "core.WebNoticeMessage")
	proto.RegisterType((*TextMessage)(nil), "core.TextMessage")
	proto.RegisterType((*ImageMessage)(nil), "core.ImageMessage")
	proto.RegisterType((*AudioMessage)(nil), "core.AudioMessage")
	proto.RegisterType((*WebMessage)(nil), "core.WebMessage")
	proto.RegisterType((*StatusMessage)(nil), "core.StatusMessage")
	proto.RegisterType((*SyncEndMessage)(nil), "core.SyncEndMessage")
	proto.RegisterType((*Message)(nil), "core.Message")
	proto.RegisterEnum("core.MessageRoomType", MessageRoomType_name, MessageRoomType_value)
	proto.RegisterEnum("core.MessageStatus", MessageStatus_name, MessageStatus_value)
	proto.RegisterEnum("core.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("core/message.proto", fileDescriptor_message_414fdb4eecac552a) }

var fileDescriptor_message_414fdb4eecac552a = []byte{
	// 797 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0x4d, 0x52, 0x96, 0xc6, 0xb6, 0xbc, 0x19, 0x2b, 0x0e, 0x0b, 0xb4, 0x81, 0xab, 0xb6,
	0xa8, 0xe1, 0xc2, 0x12, 0xea, 0x14, 0x45, 0xd1, 0xb7, 0xb8, 0x48, 0x2a, 0x01, 0x6d, 0x10, 0xac,
	0x23, 0xb8, 0x08, 0xf2, 0xc2, 0xcb, 0x44, 0x22, 0x2a, 0x72, 0x1d, 0x72, 0x65, 0x5b, 0x7d, 0xe8,
	0x8f, 0xf4, 0x8f, 0xfa, 0x13, 0xfd, 0x95, 0x62, 0x2f, 0xa2, 0x57, 0x31, 0x6c, 0x20, 0x6f, 0x33,
	0x67, 0xce, 0xec, 0x9c, 0x9d, 0x3d, 0xa2, 0x00, 0x53, 0x51, 0xd1, 0xb0, 0xa0, 0xba, 0x8e, 0xa7,
	0x34, 0xb8, 0xac, 0x84, 0x14, 0x18, 0x28, 0xac, 0xff, 0x15, 0xec, 0xbe, 0x12, 0x32, 0x4f, 0xe9,
	0x77, 0x53, 0x44, 0x84, 0x20, 0x11, 0xd9, 0x32, 0xf2, 0x0e, 0xbd, 0xa3, 0x0e, 0xd7, 0x71, 0xbf,
	0x04, 0x76, 0x41, 0xc9, 0x1d, 0x5e, 0x2a, 0x32, 0x5a, 0xf1, 0x54, 0x8c, 0x07, 0xd0, 0x9a, 0x51,
	0x3e, 0x9d, 0xc9, 0x68, 0xf3, 0xd0, 0x3b, 0x0a, 0xb9, 0xcd, 0x30, 0x82, 0xad, 0x59, 0x45, 0xef,
	0x27, 0xfc, 0xb7, 0xc8, 0xd7, 0xf4, 0x55, 0x8a, 0x3d, 0x08, 0x65, 0x2e, 0xe7, 0x14, 0x05, 0x1a,
	0x37, 0x49, 0xff, 0x4b, 0xd8, 0x7e, 0x43, 0x37, 0xf2, 0x21, 0x49, 0xaf, 0x60, 0x67, 0x5c, 0xc4,
	0xd3, 0x46, 0x0e, 0x03, 0x7f, 0x51, 0xcd, 0x2d, 0x45, 0x85, 0xea, 0xe8, 0xeb, 0x3c, 0x93, 0x33,
	0xab, 0xc5, 0x24, 0x8e, 0x44, 0xdf, 0x95, 0xd8, 0xff, 0x01, 0x76, 0x9e, 0x2f, 0xb2, 0x5c, 0xdc,
	0x7f, 0x1e, 0x42, 0x20, 0xf3, 0x82, 0xec, 0x71, 0x3a, 0xee, 0xff, 0x0d, 0x70, 0x41, 0xc9, 0x43,
	0x2b, 0xf9, 0x24, 0x15, 0xee, 0xa2, 0x82, 0x7b, 0x16, 0x15, 0xba, 0x8b, 0x9a, 0xc1, 0xee, 0xb9,
	0x8c, 0xe5, 0xa2, 0x5e, 0x49, 0xe8, 0x41, 0x58, 0xd4, 0xd3, 0x71, 0x66, 0x35, 0x98, 0x04, 0xbf,
	0x83, 0x56, 0xad, 0x69, 0x5a, 0x45, 0xf7, 0x74, 0x7f, 0xa0, 0xde, 0x7e, 0x60, 0x9b, 0xcc, 0x09,
	0xdc, 0x52, 0xd4, 0x11, 0x79, 0xcd, 0xe9, 0x83, 0x96, 0xd6, 0xe6, 0x26, 0xe9, 0x33, 0xe8, 0x9e,
	0x2f, 0xcb, 0xf4, 0x45, 0x99, 0xd9, 0xae, 0xfe, 0x3f, 0x21, 0x6c, 0x3d, 0x3c, 0xf6, 0x29, 0xc0,
	0xfb, 0x4a, 0x14, 0x93, 0x9a, 0xaa, 0x71, 0xa6, 0x47, 0x77, 0xb8, 0x83, 0xa8, 0xdb, 0x5e, 0x8a,
	0xbc, 0x94, 0x54, 0xe9, 0x59, 0x3e, 0x5f, 0xa5, 0xaa, 0x53, 0xed, 0xf7, 0x9c, 0xaa, 0x2b, 0xaa,
	0xf4, 0x2a, 0x7c, 0xee, 0x20, 0xf8, 0x3d, 0xb4, 0x2b, 0x21, 0x8a, 0x37, 0xcb, 0x4b, 0xb3, 0x90,
	0xee, 0xe9, 0xe3, 0xb5, 0x2b, 0x71, 0x5b, 0xe4, 0x0d, 0x0d, 0x3f, 0x87, 0xb6, 0x14, 0x56, 0x4a,
	0x4b, 0x49, 0x19, 0x6d, 0xf0, 0x06, 0xc1, 0xa7, 0xd0, 0x91, 0xe2, 0xd7, 0x4a, 0x2c, 0x2e, 0xc7,
	0x59, 0xb4, 0x65, 0xcb, 0xb7, 0x10, 0x7e, 0x03, 0x81, 0x54, 0xc3, 0xda, 0x7a, 0xd8, 0xa3, 0xb5,
	0x61, 0x7a, 0x90, 0x2e, 0xe3, 0xb7, 0x10, 0x48, 0xba, 0x91, 0x51, 0xe7, 0xd0, 0x3b, 0xda, 0x5e,
	0xd1, 0x1c, 0x2b, 0x8f, 0x3c, 0xae, 0x09, 0x78, 0x0c, 0x61, 0xae, 0xec, 0x1b, 0x81, 0x66, 0xa2,
	0x61, 0xba, 0x8e, 0x1e, 0x79, 0xdc, 0x50, 0x14, 0x37, 0x56, 0xd6, 0x8c, 0xb6, 0x5d, 0xae, 0xeb,
	0x56, 0xc5, 0xd5, 0x14, 0xfc, 0x1a, 0xfc, 0x6b, 0x4a, 0xa2, 0x1d, 0xcd, 0x64, 0x86, 0x79, 0xeb,
	0xd0, 0x91, 0xc7, 0x55, 0x19, 0x4f, 0x1a, 0x3f, 0xec, 0x6a, 0xa2, 0xf5, 0xc3, 0x9a, 0x95, 0x46,
	0x5e, 0xe3, 0x88, 0x13, 0x68, 0x95, 0xfa, 0xb7, 0x1f, 0x75, 0x5d, 0xfa, 0xda, 0xf7, 0x40, 0xd1,
	0x0d, 0x09, 0x7f, 0x84, 0xce, 0xf5, 0xea, 0x6b, 0x11, 0xed, 0xe9, 0x8e, 0x83, 0x46, 0xc9, 0xc7,
	0x4d, 0xb7, 0x54, 0xfc, 0x09, 0x9e, 0xc8, 0x8a, 0x62, 0xf9, 0xda, 0x98, 0xe0, 0x79, 0x3d, 0x39,
	0xb5, 0x61, 0xf4, 0x4c, 0x5b, 0xf1, 0xbe, 0xf2, 0x59, 0x1b, 0x5a, 0x52, 0xa8, 0x37, 0x3f, 0xdb,
	0x82, 0xb0, 0x88, 0x97, 0x09, 0x1d, 0xff, 0x0c, 0x7b, 0x1f, 0x79, 0x01, 0x7b, 0xc0, 0x1c, 0x48,
	0xbf, 0x2c, 0xdb, 0xc0, 0x47, 0xb0, 0xeb, 0xa0, 0x93, 0x53, 0xe6, 0x1d, 0xcb, 0x06, 0x32, 0x1b,
	0xc1, 0x27, 0xb0, 0xbf, 0x06, 0x4c, 0xca, 0x9a, 0x4a, 0xc9, 0x36, 0x30, 0x82, 0xde, 0x5a, 0xe1,
	0x9c, 0xca, 0x2c, 0x2f, 0xa7, 0xcc, 0xbb, 0xd3, 0xf2, 0x32, 0xce, 0xe7, 0x94, 0x31, 0xff, 0x4e,
	0xc1, 0x38, 0x9a, 0x05, 0xc7, 0xff, 0x79, 0xb0, 0xed, 0x38, 0x0a, 0x11, 0xba, 0x36, 0x1d, 0x97,
	0x57, 0xf1, 0x3c, 0xcf, 0xd6, 0xc4, 0x9a, 0x9d, 0x31, 0x0f, 0xf7, 0x6e, 0xbb, 0xe8, 0x46, 0xb2,
	0x4d, 0x64, 0xb0, 0xb3, 0xea, 0x53, 0xf6, 0x61, 0xbe, 0x83, 0x68, 0xd3, 0xb0, 0x00, 0xbb, 0x00,
	0x16, 0xb9, 0xa0, 0x84, 0x85, 0xce, 0x6a, 0x9a, 0x27, 0x62, 0x2d, 0xfc, 0x02, 0x3e, 0xb3, 0xe8,
	0x8b, 0x2b, 0x2a, 0xe5, 0xcb, 0x2a, 0xa7, 0x32, 0xe3, 0xf4, 0x61, 0x41, 0xb5, 0x64, 0x3d, 0x3c,
	0x00, 0x74, 0xcb, 0xe6, 0x3a, 0xec, 0xb1, 0x73, 0x43, 0x83, 0x9b, 0xcf, 0x06, 0x3b, 0x38, 0xfb,
	0x03, 0xf6, 0x53, 0x51, 0x0c, 0xfe, 0x8a, 0xe7, 0x4b, 0xf3, 0x1f, 0xa4, 0x5d, 0xf1, 0x76, 0x38,
	0xcd, 0xe5, 0x6c, 0x91, 0x0c, 0x52, 0x51, 0x0c, 0xb3, 0x45, 0xfa, 0x67, 0x3a, 0x8b, 0x65, 0x13,
	0x9c, 0x4c, 0x63, 0x49, 0xd7, 0xf1, 0x72, 0xa8, 0x1b, 0x86, 0xaa, 0xe1, 0xdf, 0xcd, 0xbd, 0xb7,
	0xf1, 0x7c, 0xf9, 0xee, 0xb5, 0x42, 0xde, 0xfd, 0x22, 0x2a, 0x4a, 0x5a, 0xba, 0xfa, 0xec, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x44, 0x46, 0xf8, 0xe8, 0x06, 0x00, 0x00,
}
