// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/site.proto

package core // import "github.com/duckchat/duckchat-gateway/proto/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushType int32

const (
	PushType_PushDisabled           PushType = 0
	PushType_PushNotificationOnly   PushType = 2
	PushType_PushWithMessageContent PushType = 3
)

var PushType_name = map[int32]string{
	0: "PushDisabled",
	2: "PushNotificationOnly",
	3: "PushWithMessageContent",
}
var PushType_value = map[string]int32{
	"PushDisabled":           0,
	"PushNotificationOnly":   2,
	"PushWithMessageContent": 3,
}

func (x PushType) String() string {
	return proto.EnumName(PushType_name, int32(x))
}
func (PushType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_site_35287d8d82d33dd8, []int{0}
}

type HooksType int32

const (
	HooksType_HooksInvalid HooksType = 0
	HooksType_HooksByHttp  HooksType = 1
	HooksType_HooksByRedis HooksType = 2
)

var HooksType_name = map[int32]string{
	0: "HooksInvalid",
	1: "HooksByHttp",
	2: "HooksByRedis",
}
var HooksType_value = map[string]int32{
	"HooksInvalid": 0,
	"HooksByHttp":  1,
	"HooksByRedis": 2,
}

func (x HooksType) String() string {
	return proto.EnumName(HooksType_name, int32(x))
}
func (HooksType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_site_35287d8d82d33dd8, []int{1}
}

type BuiltinPluginId int32

const (
	BuiltinPluginId_PluginInvalid             BuiltinPluginId = 0
	BuiltinPluginId_PluginAdmin               BuiltinPluginId = 1
	BuiltinPluginId_PluginPlaza               BuiltinPluginId = 2
	BuiltinPluginId_PluginLoginByPlatform     BuiltinPluginId = 3
	BuiltinPluginId_PluginLoginByPassword     BuiltinPluginId = 4
	BuiltinPluginId_PluginLoginByUsernameOnly BuiltinPluginId = 5
	BuiltinPluginId_PluginLoginByCert         BuiltinPluginId = 6
	BuiltinPluginId_PluginLoginByLdap         BuiltinPluginId = 7
)

var BuiltinPluginId_name = map[int32]string{
	0: "PluginInvalid",
	1: "PluginAdmin",
	2: "PluginPlaza",
	3: "PluginLoginByPlatform",
	4: "PluginLoginByPassword",
	5: "PluginLoginByUsernameOnly",
	6: "PluginLoginByCert",
	7: "PluginLoginByLdap",
}
var BuiltinPluginId_value = map[string]int32{
	"PluginInvalid":             0,
	"PluginAdmin":               1,
	"PluginPlaza":               2,
	"PluginLoginByPlatform":     3,
	"PluginLoginByPassword":     4,
	"PluginLoginByUsernameOnly": 5,
	"PluginLoginByCert":         6,
	"PluginLoginByLdap":         7,
}

func (x BuiltinPluginId) String() string {
	return proto.EnumName(BuiltinPluginId_name, int32(x))
}
func (BuiltinPluginId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_site_35287d8d82d33dd8, []int{2}
}

type Version struct {
	First  int32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second int32 `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
	Third  int32 `protobuf:"varint,3,opt,name=third,proto3" json:"third,omitempty"`
	// proto-version
	Proto                int32    `protobuf:"varint,4,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_site_35287d8d82d33dd8, []int{0}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Version) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *Version) GetThird() int32 {
	if m != nil {
		return m.Third
	}
	return 0
}

func (m *Version) GetProto() int32 {
	if m != nil {
		return m.Proto
	}
	return 0
}

// Publicly available configurations
type PublicSiteConfig struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Logo string `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	// json array, [A, B, C]
	Masters              string   `protobuf:"bytes,3,opt,name=masters,proto3" json:"masters,omitempty"`
	ServerAddressForApi  string   `protobuf:"bytes,4,opt,name=serverAddressForApi,proto3" json:"serverAddressForApi,omitempty"`
	ServerAddressForIM   string   `protobuf:"bytes,5,opt,name=serverAddressForIM,proto3" json:"serverAddressForIM,omitempty"`
	EnableCreateGroup    bool     `protobuf:"varint,6,opt,name=enableCreateGroup,proto3" json:"enableCreateGroup,omitempty"`
	EnableAddFriend      bool     `protobuf:"varint,7,opt,name=enableAddFriend,proto3" json:"enableAddFriend,omitempty"`
	EnableTmpChat        bool     `protobuf:"varint,8,opt,name=enableTmpChat,proto3" json:"enableTmpChat,omitempty"`
	EnableInvitationCode bool     `protobuf:"varint,9,opt,name=enableInvitationCode,proto3" json:"enableInvitationCode,omitempty"`
	EnableRealName       bool     `protobuf:"varint,10,opt,name=enableRealName,proto3" json:"enableRealName,omitempty"`
	LoginPluginId        int32    `protobuf:"varint,11,opt,name=loginPluginId,proto3" json:"loginPluginId,omitempty"`
	EnableWidgetWeb      bool     `protobuf:"varint,12,opt,name=enableWidgetWeb,proto3" json:"enableWidgetWeb,omitempty"`
	SiteIdPubkBase64     string   `protobuf:"bytes,13,opt,name=siteIdPubkBase64,proto3" json:"siteIdPubkBase64,omitempty"`
	Version              *Version `protobuf:"bytes,14,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicSiteConfig) Reset()         { *m = PublicSiteConfig{} }
func (m *PublicSiteConfig) String() string { return proto.CompactTextString(m) }
func (*PublicSiteConfig) ProtoMessage()    {}
func (*PublicSiteConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_site_35287d8d82d33dd8, []int{1}
}
func (m *PublicSiteConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicSiteConfig.Unmarshal(m, b)
}
func (m *PublicSiteConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicSiteConfig.Marshal(b, m, deterministic)
}
func (dst *PublicSiteConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicSiteConfig.Merge(dst, src)
}
func (m *PublicSiteConfig) XXX_Size() int {
	return xxx_messageInfo_PublicSiteConfig.Size(m)
}
func (m *PublicSiteConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicSiteConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PublicSiteConfig proto.InternalMessageInfo

func (m *PublicSiteConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublicSiteConfig) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *PublicSiteConfig) GetMasters() string {
	if m != nil {
		return m.Masters
	}
	return ""
}

func (m *PublicSiteConfig) GetServerAddressForApi() string {
	if m != nil {
		return m.ServerAddressForApi
	}
	return ""
}

func (m *PublicSiteConfig) GetServerAddressForIM() string {
	if m != nil {
		return m.ServerAddressForIM
	}
	return ""
}

func (m *PublicSiteConfig) GetEnableCreateGroup() bool {
	if m != nil {
		return m.EnableCreateGroup
	}
	return false
}

func (m *PublicSiteConfig) GetEnableAddFriend() bool {
	if m != nil {
		return m.EnableAddFriend
	}
	return false
}

func (m *PublicSiteConfig) GetEnableTmpChat() bool {
	if m != nil {
		return m.EnableTmpChat
	}
	return false
}

func (m *PublicSiteConfig) GetEnableInvitationCode() bool {
	if m != nil {
		return m.EnableInvitationCode
	}
	return false
}

func (m *PublicSiteConfig) GetEnableRealName() bool {
	if m != nil {
		return m.EnableRealName
	}
	return false
}

func (m *PublicSiteConfig) GetLoginPluginId() int32 {
	if m != nil {
		return m.LoginPluginId
	}
	return 0
}

func (m *PublicSiteConfig) GetEnableWidgetWeb() bool {
	if m != nil {
		return m.EnableWidgetWeb
	}
	return false
}

func (m *PublicSiteConfig) GetSiteIdPubkBase64() string {
	if m != nil {
		return m.SiteIdPubkBase64
	}
	return ""
}

func (m *PublicSiteConfig) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// all the configurations, private!
type AllSiteConfig struct {
	Public                       *PublicSiteConfig `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	HooksType                    HooksType         `protobuf:"varint,2,opt,name=HooksType,proto3,enum=core.HooksType" json:"HooksType,omitempty"`
	HooksRedisServer             string            `protobuf:"bytes,3,opt,name=hooksRedisServer,proto3" json:"hooksRedisServer,omitempty"`
	PushType                     PushType          `protobuf:"varint,4,opt,name=PushType,proto3,enum=core.PushType" json:"PushType,omitempty"`
	SiteIdPrikBase64             string            `protobuf:"bytes,5,opt,name=siteIdPrikBase64,proto3" json:"siteIdPrikBase64,omitempty"`
	MaxGroupMembers              string            `protobuf:"bytes,6,opt,name=maxGroupMembers,proto3" json:"maxGroupMembers,omitempty"`
	GroupInvitationUrlExpiration int32             `protobuf:"varint,7,opt,name=groupInvitationUrlExpiration,proto3" json:"groupInvitationUrlExpiration,omitempty"`
	MaxClientsNum                int32             `protobuf:"varint,8,opt,name=maxClientsNum,proto3" json:"maxClientsNum,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}          `json:"-"`
	XXX_unrecognized             []byte            `json:"-"`
	XXX_sizecache                int32             `json:"-"`
}

func (m *AllSiteConfig) Reset()         { *m = AllSiteConfig{} }
func (m *AllSiteConfig) String() string { return proto.CompactTextString(m) }
func (*AllSiteConfig) ProtoMessage()    {}
func (*AllSiteConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_site_35287d8d82d33dd8, []int{2}
}
func (m *AllSiteConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllSiteConfig.Unmarshal(m, b)
}
func (m *AllSiteConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllSiteConfig.Marshal(b, m, deterministic)
}
func (dst *AllSiteConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllSiteConfig.Merge(dst, src)
}
func (m *AllSiteConfig) XXX_Size() int {
	return xxx_messageInfo_AllSiteConfig.Size(m)
}
func (m *AllSiteConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AllSiteConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AllSiteConfig proto.InternalMessageInfo

func (m *AllSiteConfig) GetPublic() *PublicSiteConfig {
	if m != nil {
		return m.Public
	}
	return nil
}

func (m *AllSiteConfig) GetHooksType() HooksType {
	if m != nil {
		return m.HooksType
	}
	return HooksType_HooksInvalid
}

func (m *AllSiteConfig) GetHooksRedisServer() string {
	if m != nil {
		return m.HooksRedisServer
	}
	return ""
}

func (m *AllSiteConfig) GetPushType() PushType {
	if m != nil {
		return m.PushType
	}
	return PushType_PushDisabled
}

func (m *AllSiteConfig) GetSiteIdPrikBase64() string {
	if m != nil {
		return m.SiteIdPrikBase64
	}
	return ""
}

func (m *AllSiteConfig) GetMaxGroupMembers() string {
	if m != nil {
		return m.MaxGroupMembers
	}
	return ""
}

func (m *AllSiteConfig) GetGroupInvitationUrlExpiration() int32 {
	if m != nil {
		return m.GroupInvitationUrlExpiration
	}
	return 0
}

func (m *AllSiteConfig) GetMaxClientsNum() int32 {
	if m != nil {
		return m.MaxClientsNum
	}
	return 0
}

func init() {
	proto.RegisterType((*Version)(nil), "core.Version")
	proto.RegisterType((*PublicSiteConfig)(nil), "core.PublicSiteConfig")
	proto.RegisterType((*AllSiteConfig)(nil), "core.AllSiteConfig")
	proto.RegisterEnum("core.PushType", PushType_name, PushType_value)
	proto.RegisterEnum("core.HooksType", HooksType_name, HooksType_value)
	proto.RegisterEnum("core.BuiltinPluginId", BuiltinPluginId_name, BuiltinPluginId_value)
}

func init() { proto.RegisterFile("core/site.proto", fileDescriptor_site_35287d8d82d33dd8) }

var fileDescriptor_site_35287d8d82d33dd8 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdf, 0x6e, 0xdb, 0x36,
	0x14, 0xc6, 0x67, 0xc7, 0x7f, 0xe2, 0x93, 0xda, 0x56, 0xd8, 0x34, 0x50, 0x87, 0x0d, 0x08, 0x82,
	0x61, 0x33, 0x8c, 0xd5, 0x1e, 0xbc, 0x61, 0xd7, 0xb3, 0xbd, 0x75, 0x35, 0xd0, 0x64, 0x86, 0xda,
	0x2e, 0x43, 0xd1, 0x1b, 0x5a, 0xa4, 0x65, 0x22, 0x94, 0x28, 0x90, 0x94, 0x1b, 0xf5, 0x01, 0xf6,
	0x46, 0x7b, 0x88, 0xed, 0xa9, 0x06, 0x1e, 0xf9, 0xbf, 0x83, 0xde, 0xf1, 0xfc, 0xbe, 0x8f, 0x87,
	0xe2, 0xe1, 0x07, 0x41, 0x3b, 0x54, 0x9a, 0xf7, 0x8d, 0xb0, 0xbc, 0x97, 0x6a, 0x65, 0x15, 0xa9,
	0x38, 0x70, 0x1d, 0x42, 0xfd, 0x4f, 0xae, 0x8d, 0x50, 0x09, 0xb9, 0x80, 0xea, 0x5c, 0x68, 0x63,
	0xfd, 0xd2, 0x55, 0xa9, 0x53, 0x0d, 0x8a, 0x82, 0x5c, 0x42, 0xcd, 0xf0, 0x50, 0x25, 0xcc, 0x2f,
	0x23, 0x5e, 0x55, 0xce, 0x6d, 0x17, 0x42, 0x33, 0xff, 0xa4, 0x70, 0x63, 0xe1, 0x28, 0x76, 0xf7,
	0x2b, 0x05, 0xc5, 0xe2, 0xfa, 0x9f, 0x0a, 0x78, 0xd3, 0x6c, 0x26, 0x45, 0xf8, 0x46, 0x58, 0x3e,
	0x56, 0xc9, 0x5c, 0x44, 0x84, 0x40, 0x25, 0xa1, 0x31, 0xc7, 0xd3, 0x1a, 0x01, 0xae, 0x1d, 0x93,
	0x2a, 0x52, 0x78, 0x54, 0x23, 0xc0, 0x35, 0xf1, 0xa1, 0x1e, 0x53, 0x63, 0xb9, 0x36, 0x78, 0x54,
	0x23, 0x58, 0x97, 0xe4, 0x07, 0x78, 0x6a, 0xb8, 0x5e, 0x72, 0x3d, 0x64, 0x4c, 0x73, 0x63, 0x5e,
	0x2a, 0x3d, 0x4c, 0x05, 0x1e, 0xdd, 0x08, 0x1e, 0x93, 0x48, 0x0f, 0xc8, 0x21, 0x9e, 0xdc, 0xf8,
	0x55, 0xdc, 0xf0, 0x88, 0x42, 0xbe, 0x87, 0x73, 0x9e, 0xd0, 0x99, 0xe4, 0x63, 0xcd, 0xa9, 0xe5,
	0xbf, 0x6b, 0x95, 0xa5, 0x7e, 0xed, 0xaa, 0xd4, 0x39, 0x0d, 0x8e, 0x05, 0xd2, 0x81, 0x76, 0x01,
	0x87, 0x8c, 0xbd, 0xd4, 0x82, 0x27, 0xcc, 0xaf, 0xa3, 0xf7, 0x10, 0x93, 0x6f, 0xa0, 0x59, 0xa0,
	0xb7, 0x71, 0x3a, 0x5e, 0x50, 0xeb, 0x9f, 0xa2, 0x6f, 0x1f, 0x92, 0x01, 0x5c, 0x14, 0x60, 0x92,
	0x2c, 0x85, 0xa5, 0x56, 0xa8, 0x64, 0xac, 0x18, 0xf7, 0x1b, 0x68, 0x7e, 0x54, 0x23, 0xdf, 0x42,
	0xab, 0xe0, 0x01, 0xa7, 0xf2, 0xd6, 0xcd, 0x17, 0xd0, 0x7d, 0x40, 0xdd, 0x17, 0x48, 0x15, 0x89,
	0x64, 0x2a, 0xb3, 0x48, 0x24, 0x13, 0xe6, 0x9f, 0xe1, 0x83, 0xed, 0xc3, 0xed, 0x8d, 0xee, 0x04,
	0x8b, 0xb8, 0xbd, 0xe3, 0x33, 0xff, 0xc9, 0xee, 0x8d, 0x36, 0x98, 0x74, 0xc1, 0x73, 0xd9, 0x9a,
	0xb0, 0x69, 0x36, 0xbb, 0x1f, 0x51, 0xc3, 0x7f, 0xfe, 0xc9, 0x6f, 0xe2, 0x5c, 0x8f, 0x38, 0xf9,
	0x0e, 0xea, 0xcb, 0x22, 0x73, 0x7e, 0xeb, 0xaa, 0xd4, 0x39, 0x1b, 0x34, 0x7b, 0x2e, 0x8b, 0xbd,
	0x55, 0x10, 0x83, 0xb5, 0x7a, 0xfd, 0xf7, 0x09, 0x34, 0x87, 0x52, 0xee, 0x84, 0xa6, 0x07, 0xb5,
	0x14, 0x83, 0x84, 0xb1, 0x39, 0x1b, 0x5c, 0x16, 0x3b, 0x0f, 0xc3, 0x15, 0xac, 0x5c, 0xe4, 0x05,
	0x34, 0x5e, 0x29, 0x75, 0x6f, 0xde, 0xe6, 0x29, 0xc7, 0x54, 0xb5, 0x06, 0xed, 0x62, 0xcb, 0x06,
	0x07, 0x5b, 0x87, 0xbb, 0xc5, 0xc2, 0x15, 0x01, 0x67, 0xc2, 0xbc, 0xc1, 0x3c, 0xac, 0x42, 0x77,
	0xc4, 0x49, 0x17, 0x4e, 0xa7, 0x99, 0x59, 0x60, 0xe7, 0x0a, 0x76, 0x6e, 0xad, 0x3f, 0xa6, 0xa0,
	0xc1, 0x46, 0xdf, 0x99, 0x8e, 0x16, 0xeb, 0xe9, 0x54, 0xf7, 0xa6, 0xb3, 0xe1, 0x6e, 0xe6, 0x31,
	0x7d, 0xc0, 0x44, 0xdd, 0xf0, 0x78, 0xe6, 0x72, 0x5f, 0x43, 0xeb, 0x21, 0x26, 0x23, 0xf8, 0x2a,
	0x72, 0xf5, 0x36, 0x02, 0xef, 0xb4, 0xfc, 0xed, 0x21, 0x15, 0x1a, 0x0b, 0x0c, 0x5f, 0x35, 0xf8,
	0xac, 0xc7, 0xe5, 0x20, 0xa6, 0x0f, 0x63, 0x29, 0x78, 0x62, 0xcd, 0x6d, 0x16, 0x63, 0x12, 0xab,
	0xc1, 0x3e, 0xec, 0x06, 0xdb, 0xbb, 0x12, 0x0f, 0x9e, 0xb8, 0xf5, 0xaf, 0xc2, 0xb8, 0x04, 0x30,
	0xef, 0x0b, 0xe2, 0xc3, 0x85, 0x23, 0xb7, 0xca, 0x8a, 0xb9, 0x08, 0xb1, 0xef, 0x1f, 0x89, 0xcc,
	0xbd, 0x32, 0xf9, 0x12, 0x2e, 0x9d, 0x72, 0x27, 0xec, 0xe2, 0x86, 0x1b, 0x43, 0x23, 0xf7, 0x3e,
	0x96, 0x27, 0xd6, 0x3b, 0xe9, 0xfe, 0xb2, 0xf3, 0x34, 0xae, 0x29, 0x16, 0x93, 0x64, 0x49, 0xa5,
	0x70, 0x4d, 0xdb, 0x70, 0x86, 0x64, 0x94, 0xbf, 0xb2, 0x36, 0xf5, 0x4a, 0x1b, 0xcb, 0x28, 0xc7,
	0x57, 0xf0, 0xca, 0xdd, 0x7f, 0x4b, 0xd0, 0x1e, 0x65, 0x42, 0xda, 0x9d, 0xc4, 0x9e, 0x43, 0x73,
	0xb5, 0xde, 0xed, 0x54, 0xa0, 0x21, 0x8b, 0x45, 0xe2, 0x95, 0xb6, 0x60, 0x2a, 0xe9, 0x27, 0xea,
	0x95, 0xc9, 0x73, 0x78, 0x56, 0x80, 0xd7, 0x2e, 0xfd, 0xa3, 0x7c, 0x2a, 0xa9, 0x9d, 0x2b, 0x1d,
	0x7b, 0x27, 0xc7, 0x12, 0x35, 0xe6, 0xa3, 0xd2, 0xcc, 0xab, 0x90, 0xaf, 0xe1, 0xf9, 0x9e, 0xf4,
	0xce, 0x70, 0xed, 0xfe, 0x62, 0x78, 0xf7, 0x2a, 0x79, 0x06, 0xe7, 0x7b, 0xf2, 0x98, 0x6b, 0xeb,
	0xd5, 0x8e, 0xf0, 0x6b, 0x46, 0x53, 0xaf, 0x3e, 0xfa, 0x0b, 0x9e, 0x86, 0x2a, 0xee, 0x7d, 0xa2,
	0x32, 0x2f, 0xfe, 0xcf, 0x98, 0xa5, 0xf7, 0xfd, 0x48, 0xd8, 0x45, 0x36, 0xeb, 0x85, 0x2a, 0xee,
	0xb3, 0x2c, 0xbc, 0x0f, 0x17, 0xd4, 0x6e, 0x16, 0x2f, 0x22, 0x6a, 0xf9, 0x47, 0x9a, 0xf7, 0x71,
	0x43, 0xdf, 0x6d, 0xf8, 0xaf, 0xdc, 0x7e, 0x4f, 0x65, 0xfe, 0x61, 0xea, 0xc8, 0x87, 0xb1, 0xd2,
	0x7c, 0x56, 0x43, 0xf5, 0xc7, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xa3, 0x49, 0xea, 0x01,
	0x06, 0x00, 0x00,
}
