// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/user.proto

package core // import "github.com/duckchat/duckchat-gateway/proto/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserAvailableType int32

const (
	UserAvailableType_UserAvailableInvalid UserAvailableType = 0
	UserAvailableType_UserAvailableNormal  UserAvailableType = 1
	UserAvailableType_UserAvailableBlocked UserAvailableType = 2
	UserAvailableType_UserAvailableGuest   UserAvailableType = 3
)

var UserAvailableType_name = map[int32]string{
	0: "UserAvailableInvalid",
	1: "UserAvailableNormal",
	2: "UserAvailableBlocked",
	3: "UserAvailableGuest",
}
var UserAvailableType_value = map[string]int32{
	"UserAvailableInvalid": 0,
	"UserAvailableNormal":  1,
	"UserAvailableBlocked": 2,
	"UserAvailableGuest":   3,
}

func (x UserAvailableType) String() string {
	return proto.EnumName(UserAvailableType_name, int32(x))
}
func (UserAvailableType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_391e24a1567b1e62, []int{0}
}

type FriendRelationType int32

const (
	FriendRelationType_FriendRelationInvalid        FriendRelationType = 0
	FriendRelationType_FriendRelationFollow         FriendRelationType = 1
	FriendRelationType_FriendRelationFollowForGroup FriendRelationType = 2
	FriendRelationType_FriendRelationFollowForWeb   FriendRelationType = 3
)

var FriendRelationType_name = map[int32]string{
	0: "FriendRelationInvalid",
	1: "FriendRelationFollow",
	2: "FriendRelationFollowForGroup",
	3: "FriendRelationFollowForWeb",
}
var FriendRelationType_value = map[string]int32{
	"FriendRelationInvalid":        0,
	"FriendRelationFollow":         1,
	"FriendRelationFollowForGroup": 2,
	"FriendRelationFollowForWeb":   3,
}

func (x FriendRelationType) String() string {
	return proto.EnumName(FriendRelationType_name, int32(x))
}
func (FriendRelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_391e24a1567b1e62, []int{1}
}

type PublicUserProfile struct {
	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginName string `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	// nickname or alias nickname
	Nickname             string            `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	NicknameInLatin      string            `protobuf:"bytes,4,opt,name=nicknameInLatin,proto3" json:"nicknameInLatin,omitempty"`
	Avatar               string            `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	AvailableType        UserAvailableType `protobuf:"varint,6,opt,name=availableType,proto3,enum=core.UserAvailableType" json:"availableType,omitempty"`
	RealNickname         string            `protobuf:"bytes,7,opt,name=realNickname,proto3" json:"realNickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PublicUserProfile) Reset()         { *m = PublicUserProfile{} }
func (m *PublicUserProfile) String() string { return proto.CompactTextString(m) }
func (*PublicUserProfile) ProtoMessage()    {}
func (*PublicUserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_391e24a1567b1e62, []int{0}
}
func (m *PublicUserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicUserProfile.Unmarshal(m, b)
}
func (m *PublicUserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicUserProfile.Marshal(b, m, deterministic)
}
func (dst *PublicUserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicUserProfile.Merge(dst, src)
}
func (m *PublicUserProfile) XXX_Size() int {
	return xxx_messageInfo_PublicUserProfile.Size(m)
}
func (m *PublicUserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicUserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PublicUserProfile proto.InternalMessageInfo

func (m *PublicUserProfile) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PublicUserProfile) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *PublicUserProfile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *PublicUserProfile) GetNicknameInLatin() string {
	if m != nil {
		return m.NicknameInLatin
	}
	return ""
}

func (m *PublicUserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PublicUserProfile) GetAvailableType() UserAvailableType {
	if m != nil {
		return m.AvailableType
	}
	return UserAvailableType_UserAvailableInvalid
}

func (m *PublicUserProfile) GetRealNickname() string {
	if m != nil {
		return m.RealNickname
	}
	return ""
}

type AllUserProfile struct {
	Public               *PublicUserProfile `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	TimeReg              int64              `protobuf:"varint,2,opt,name=timeReg,proto3" json:"timeReg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AllUserProfile) Reset()         { *m = AllUserProfile{} }
func (m *AllUserProfile) String() string { return proto.CompactTextString(m) }
func (*AllUserProfile) ProtoMessage()    {}
func (*AllUserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_391e24a1567b1e62, []int{1}
}
func (m *AllUserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllUserProfile.Unmarshal(m, b)
}
func (m *AllUserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllUserProfile.Marshal(b, m, deterministic)
}
func (dst *AllUserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllUserProfile.Merge(dst, src)
}
func (m *AllUserProfile) XXX_Size() int {
	return xxx_messageInfo_AllUserProfile.Size(m)
}
func (m *AllUserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_AllUserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_AllUserProfile proto.InternalMessageInfo

func (m *AllUserProfile) GetPublic() *PublicUserProfile {
	if m != nil {
		return m.Public
	}
	return nil
}

func (m *AllUserProfile) GetTimeReg() int64 {
	if m != nil {
		return m.TimeReg
	}
	return 0
}

type ApplyUserProfile struct {
	Public               *PublicUserProfile `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Greetings            string             `protobuf:"bytes,2,opt,name=greetings,proto3" json:"greetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ApplyUserProfile) Reset()         { *m = ApplyUserProfile{} }
func (m *ApplyUserProfile) String() string { return proto.CompactTextString(m) }
func (*ApplyUserProfile) ProtoMessage()    {}
func (*ApplyUserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_391e24a1567b1e62, []int{2}
}
func (m *ApplyUserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyUserProfile.Unmarshal(m, b)
}
func (m *ApplyUserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyUserProfile.Marshal(b, m, deterministic)
}
func (dst *ApplyUserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyUserProfile.Merge(dst, src)
}
func (m *ApplyUserProfile) XXX_Size() int {
	return xxx_messageInfo_ApplyUserProfile.Size(m)
}
func (m *ApplyUserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyUserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyUserProfile proto.InternalMessageInfo

func (m *ApplyUserProfile) GetPublic() *PublicUserProfile {
	if m != nil {
		return m.Public
	}
	return nil
}

func (m *ApplyUserProfile) GetGreetings() string {
	if m != nil {
		return m.Greetings
	}
	return ""
}

type FriendUserProfile struct {
	Profile              *PublicUserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Mute                 bool               `protobuf:"varint,2,opt,name=mute,proto3" json:"mute,omitempty"`
	Relation             FriendRelationType `protobuf:"varint,3,opt,name=relation,proto3,enum=core.FriendRelationType" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FriendUserProfile) Reset()         { *m = FriendUserProfile{} }
func (m *FriendUserProfile) String() string { return proto.CompactTextString(m) }
func (*FriendUserProfile) ProtoMessage()    {}
func (*FriendUserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_391e24a1567b1e62, []int{3}
}
func (m *FriendUserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendUserProfile.Unmarshal(m, b)
}
func (m *FriendUserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendUserProfile.Marshal(b, m, deterministic)
}
func (dst *FriendUserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendUserProfile.Merge(dst, src)
}
func (m *FriendUserProfile) XXX_Size() int {
	return xxx_messageInfo_FriendUserProfile.Size(m)
}
func (m *FriendUserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendUserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_FriendUserProfile proto.InternalMessageInfo

func (m *FriendUserProfile) GetProfile() *PublicUserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *FriendUserProfile) GetMute() bool {
	if m != nil {
		return m.Mute
	}
	return false
}

func (m *FriendUserProfile) GetRelation() FriendRelationType {
	if m != nil {
		return m.Relation
	}
	return FriendRelationType_FriendRelationInvalid
}

func init() {
	proto.RegisterType((*PublicUserProfile)(nil), "core.PublicUserProfile")
	proto.RegisterType((*AllUserProfile)(nil), "core.AllUserProfile")
	proto.RegisterType((*ApplyUserProfile)(nil), "core.ApplyUserProfile")
	proto.RegisterType((*FriendUserProfile)(nil), "core.FriendUserProfile")
	proto.RegisterEnum("core.UserAvailableType", UserAvailableType_name, UserAvailableType_value)
	proto.RegisterEnum("core.FriendRelationType", FriendRelationType_name, FriendRelationType_value)
}

func init() { proto.RegisterFile("core/user.proto", fileDescriptor_user_391e24a1567b1e62) }

var fileDescriptor_user_391e24a1567b1e62 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0x39, 0xc9, 0x2f, 0x7f, 0x06, 0x48, 0x9c, 0x6d, 0x69, 0x4d, 0x15, 0xa1, 0xc8, 0xa7,
	0xa8, 0x12, 0xb6, 0x28, 0x5c, 0x39, 0xa4, 0x48, 0xa9, 0x22, 0xa1, 0x28, 0xb2, 0x40, 0xa0, 0xd2,
	0xcb, 0xda, 0x1e, 0xdc, 0x55, 0xd6, 0x5e, 0x6b, 0xb3, 0x4e, 0x31, 0x1f, 0x01, 0x2e, 0x7c, 0x2e,
	0x3e, 0x15, 0xf2, 0x3a, 0x4e, 0x63, 0x02, 0xe2, 0xc0, 0x6d, 0xe6, 0xbd, 0xb7, 0xf3, 0xc6, 0x6f,
	0x64, 0x18, 0x04, 0x42, 0xa2, 0x9b, 0xad, 0x51, 0x3a, 0xa9, 0x14, 0x4a, 0x90, 0x56, 0x01, 0xd8,
	0x5f, 0x1b, 0x30, 0x5c, 0x66, 0x3e, 0x67, 0xc1, 0xbb, 0x35, 0xca, 0xa5, 0x14, 0x9f, 0x18, 0x47,
	0x72, 0x02, 0xed, 0x42, 0x39, 0x0f, 0x2d, 0x63, 0x6c, 0x4c, 0x7a, 0xde, 0xb6, 0x23, 0x23, 0xe8,
	0x71, 0x11, 0xb1, 0x64, 0x41, 0x63, 0xb4, 0x1a, 0x9a, 0xba, 0x07, 0xc8, 0x19, 0x74, 0x13, 0x16,
	0xac, 0x92, 0x82, 0x6c, 0x6a, 0x72, 0xd7, 0x93, 0x09, 0x0c, 0xaa, 0x7a, 0x9e, 0xbc, 0xa1, 0x8a,
	0x25, 0x56, 0x4b, 0x4b, 0x7e, 0x85, 0x0b, 0x6f, 0xba, 0xa1, 0x8a, 0x4a, 0xeb, 0xff, 0xd2, 0xbb,
	0xec, 0xc8, 0x2b, 0x78, 0x44, 0x37, 0x94, 0x71, 0xea, 0x73, 0x7c, 0x9b, 0xa7, 0x68, 0xb5, 0xc7,
	0xc6, 0xa4, 0x7f, 0x71, 0xea, 0x14, 0xdf, 0xe1, 0x14, 0xdb, 0x4f, 0xf7, 0x69, 0xaf, 0xae, 0x26,
	0x36, 0x3c, 0x94, 0x48, 0xf9, 0xa2, 0x5a, 0xb0, 0xa3, 0x87, 0xd7, 0x30, 0xfb, 0x23, 0xf4, 0xa7,
	0x9c, 0xef, 0x07, 0xe1, 0x42, 0x3b, 0xd5, 0xe9, 0xe8, 0x20, 0x1e, 0x54, 0x6e, 0x07, 0x89, 0x79,
	0x5b, 0x19, 0xb1, 0xa0, 0xa3, 0x58, 0x8c, 0x1e, 0x46, 0x3a, 0x9f, 0xa6, 0x57, 0xb5, 0x36, 0x05,
	0x73, 0x9a, 0xa6, 0x3c, 0xff, 0xa7, 0xf1, 0x23, 0xe8, 0x45, 0x12, 0x51, 0xb1, 0x24, 0x5a, 0x57,
	0x07, 0xd8, 0x01, 0xf6, 0x77, 0x03, 0x86, 0x33, 0xc9, 0x30, 0x09, 0xf7, 0x4d, 0x9e, 0x43, 0x27,
	0x2d, 0xcb, 0xbf, 0xb9, 0x54, 0x3a, 0x42, 0xa0, 0x15, 0x67, 0xaa, 0x3c, 0x71, 0xd7, 0xd3, 0x35,
	0x79, 0x09, 0x5d, 0x89, 0x9c, 0x2a, 0x26, 0x12, 0x7d, 0xdd, 0xfe, 0x85, 0x55, 0xce, 0x29, 0x1d,
	0xbd, 0x2d, 0xa7, 0xb3, 0xdf, 0x29, 0xcf, 0x3f, 0xc3, 0xf0, 0xe0, 0x34, 0xc4, 0x82, 0xe3, 0x1a,
	0x38, 0x4f, 0x36, 0x94, 0xb3, 0xd0, 0xfc, 0x8f, 0x9c, 0xc2, 0x51, 0x8d, 0x59, 0x08, 0x19, 0x53,
	0x6e, 0x1a, 0x07, 0x4f, 0x2e, 0xb9, 0x08, 0x56, 0x18, 0x9a, 0x0d, 0x72, 0x02, 0xa4, 0xc6, 0x5c,
	0x65, 0xb8, 0x56, 0x66, 0xf3, 0xfc, 0x9b, 0x01, 0xe4, 0x70, 0x35, 0xf2, 0x04, 0x1e, 0xd7, 0xd1,
	0x7b, 0x73, 0x0b, 0x8e, 0xeb, 0xd4, 0x4c, 0x70, 0x2e, 0xee, 0x4c, 0x83, 0x8c, 0x61, 0xf4, 0x3b,
	0x66, 0x26, 0xe4, 0x95, 0x14, 0x59, 0x6a, 0x36, 0xc8, 0x53, 0x38, 0xfb, 0x83, 0xe2, 0x3d, 0xfa,
	0x66, 0xf3, 0xf2, 0x03, 0x1c, 0x05, 0x22, 0x76, 0xbe, 0x50, 0x9e, 0x97, 0xff, 0x9f, 0xce, 0xee,
	0xda, 0x8d, 0x98, 0xba, 0xcd, 0x7c, 0x27, 0x10, 0xb1, 0x1b, 0x66, 0xc1, 0x2a, 0xb8, 0xa5, 0x6a,
	0x57, 0x3c, 0x8b, 0xa8, 0xc2, 0x3b, 0x9a, 0xbb, 0xfa, 0x81, 0x5b, 0x3c, 0xf8, 0xd1, 0x18, 0x5c,
	0x53, 0x9e, 0xdf, 0x2c, 0x0b, 0xe4, 0xe6, 0xb5, 0x90, 0xe8, 0xb7, 0x35, 0xfb, 0xe2, 0x67, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9c, 0x0e, 0x19, 0xc7, 0xe1, 0x03, 0x00, 0x00,
}
