// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_password_reg.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.passport.password.reg
//
//
type ApiPassportPasswordRegRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	SitePubkPem          string   `protobuf:"bytes,5,opt,name=sitePubkPem,proto3" json:"sitePubkPem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordRegRequest) Reset()         { *m = ApiPassportPasswordRegRequest{} }
func (m *ApiPassportPasswordRegRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordRegRequest) ProtoMessage()    {}
func (*ApiPassportPasswordRegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_reg_481a0c92c8c79df5, []int{0}
}
func (m *ApiPassportPasswordRegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordRegRequest.Unmarshal(m, b)
}
func (m *ApiPassportPasswordRegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordRegRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordRegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordRegRequest.Merge(dst, src)
}
func (m *ApiPassportPasswordRegRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordRegRequest.Size(m)
}
func (m *ApiPassportPasswordRegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordRegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordRegRequest proto.InternalMessageInfo

func (m *ApiPassportPasswordRegRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *ApiPassportPasswordRegRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ApiPassportPasswordRegRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ApiPassportPasswordRegRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ApiPassportPasswordRegRequest) GetSitePubkPem() string {
	if m != nil {
		return m.SitePubkPem
	}
	return ""
}

type ApiPassportPasswordRegResponse struct {
	PreSessionId         string   `protobuf:"bytes,1,opt,name=preSessionId,proto3" json:"preSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordRegResponse) Reset()         { *m = ApiPassportPasswordRegResponse{} }
func (m *ApiPassportPasswordRegResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordRegResponse) ProtoMessage()    {}
func (*ApiPassportPasswordRegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_reg_481a0c92c8c79df5, []int{1}
}
func (m *ApiPassportPasswordRegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordRegResponse.Unmarshal(m, b)
}
func (m *ApiPassportPasswordRegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordRegResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordRegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordRegResponse.Merge(dst, src)
}
func (m *ApiPassportPasswordRegResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordRegResponse.Size(m)
}
func (m *ApiPassportPasswordRegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordRegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordRegResponse proto.InternalMessageInfo

func (m *ApiPassportPasswordRegResponse) GetPreSessionId() string {
	if m != nil {
		return m.PreSessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiPassportPasswordRegRequest)(nil), "site.ApiPassportPasswordRegRequest")
	proto.RegisterType((*ApiPassportPasswordRegResponse)(nil), "site.ApiPassportPasswordRegResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_password_reg.proto", fileDescriptor_api_passport_password_reg_481a0c92c8c79df5)
}

var fileDescriptor_api_passport_password_reg_481a0c92c8c79df5 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcf, 0x4a, 0xfb, 0x30,
	0x1c, 0xa7, 0xfb, 0x6d, 0x3f, 0x5c, 0x14, 0x84, 0xe8, 0xa1, 0x88, 0xca, 0x28, 0x1e, 0xbc, 0xd8,
	0x1e, 0x7c, 0x02, 0xc5, 0x8b, 0x17, 0x09, 0xdd, 0x45, 0xc6, 0x60, 0xa4, 0xe9, 0x97, 0x2c, 0xb4,
	0xf9, 0x63, 0x92, 0x32, 0xea, 0x3b, 0xf9, 0x22, 0x3e, 0x95, 0x24, 0xed, 0xa6, 0x1e, 0xbc, 0x7d,
	0x3f, 0x7f, 0xf3, 0x21, 0xe8, 0xc6, 0x09, 0x0f, 0x05, 0x35, 0x62, 0x63, 0xa8, 0x73, 0x46, 0x5b,
	0x1f, 0x8f, 0x9d, 0xb6, 0xf5, 0xc6, 0x02, 0xcf, 0x8d, 0xd5, 0x5e, 0xe3, 0x69, 0x70, 0x65, 0x1f,
	0x09, 0xba, 0x7a, 0x30, 0x82, 0x8c, 0x46, 0x32, 0xfa, 0x4a, 0xe0, 0x25, 0xbc, 0x75, 0xe0, 0x3c,
	0xbe, 0x44, 0xf3, 0x56, 0x73, 0xa1, 0x5e, 0xa8, 0x84, 0x34, 0x59, 0x24, 0xb7, 0xf3, 0xf2, 0x9b,
	0xc0, 0x17, 0xe8, 0x68, 0xdf, 0x9d, 0x4e, 0xa2, 0x78, 0xc0, 0xf8, 0x1c, 0xcd, 0x40, 0x52, 0xd1,
	0xa6, 0xff, 0xa2, 0x30, 0x80, 0x90, 0x50, 0x82, 0x35, 0x2a, 0xd4, 0x4d, 0x87, 0xc4, 0x1e, 0xe3,
	0x05, 0x3a, 0x0e, 0xab, 0x48, 0x57, 0x35, 0x04, 0x64, 0x3a, 0x8b, 0xf2, 0x4f, 0x2a, 0x7b, 0x42,
	0xd7, 0x7f, 0xcd, 0x75, 0x46, 0x2b, 0x07, 0x38, 0x43, 0x27, 0xc6, 0xc2, 0x12, 0x9c, 0x13, 0x5a,
	0x3d, 0xd7, 0xe3, 0xe4, 0x5f, 0xdc, 0xe3, 0x2b, 0x3a, 0x63, 0x5a, 0xe6, 0xef, 0xb4, 0xed, 0x87,
	0xdf, 0xc8, 0xc3, 0x1b, 0xab, 0x82, 0x0b, 0xbf, 0xed, 0xaa, 0x9c, 0x69, 0x59, 0xd4, 0x1d, 0x6b,
	0xd8, 0x96, 0xfa, 0xc3, 0x71, 0xc7, 0xa9, 0x87, 0x1d, 0xed, 0x8b, 0x18, 0x28, 0x42, 0xe0, 0x73,
	0x72, 0xba, 0xa2, 0x6d, 0xbf, 0x26, 0x81, 0x59, 0x2f, 0x85, 0x87, 0xea, 0x7f, 0x54, 0xef, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x1c, 0x64, 0x8a, 0x84, 0x01, 0x00, 0x00,
}
