// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_file_download.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.file.download
// error:
// .   error.file.none          there's no file
// .   error.file.permission.   the file is not related to the session user.
type ApiFileDownloadRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	ReturnBase64         bool     `protobuf:"varint,2,opt,name=returnBase64,proto3" json:"returnBase64,omitempty"`
	MessageId            string   `protobuf:"bytes,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	IsGroupMessage       bool     `protobuf:"varint,4,opt,name=isGroupMessage,proto3" json:"isGroupMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFileDownloadRequest) Reset()         { *m = ApiFileDownloadRequest{} }
func (m *ApiFileDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFileDownloadRequest) ProtoMessage()    {}
func (*ApiFileDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_file_download_3c5c07279664bb30, []int{0}
}
func (m *ApiFileDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFileDownloadRequest.Unmarshal(m, b)
}
func (m *ApiFileDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFileDownloadRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFileDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFileDownloadRequest.Merge(dst, src)
}
func (m *ApiFileDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFileDownloadRequest.Size(m)
}
func (m *ApiFileDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFileDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFileDownloadRequest proto.InternalMessageInfo

func (m *ApiFileDownloadRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *ApiFileDownloadRequest) GetReturnBase64() bool {
	if m != nil {
		return m.ReturnBase64
	}
	return false
}

func (m *ApiFileDownloadRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *ApiFileDownloadRequest) GetIsGroupMessage() bool {
	if m != nil {
		return m.IsGroupMessage
	}
	return false
}

type ApiFileDownloadResponse struct {
	// Types that are valid to be assigned to Ret:
	//	*ApiFileDownloadResponse_File
	//	*ApiFileDownloadResponse_FileBase64
	Ret                  isApiFileDownloadResponse_Ret `protobuf_oneof:"ret"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ApiFileDownloadResponse) Reset()         { *m = ApiFileDownloadResponse{} }
func (m *ApiFileDownloadResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFileDownloadResponse) ProtoMessage()    {}
func (*ApiFileDownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_file_download_3c5c07279664bb30, []int{1}
}
func (m *ApiFileDownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFileDownloadResponse.Unmarshal(m, b)
}
func (m *ApiFileDownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFileDownloadResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFileDownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFileDownloadResponse.Merge(dst, src)
}
func (m *ApiFileDownloadResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFileDownloadResponse.Size(m)
}
func (m *ApiFileDownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFileDownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFileDownloadResponse proto.InternalMessageInfo

type isApiFileDownloadResponse_Ret interface {
	isApiFileDownloadResponse_Ret()
}

type ApiFileDownloadResponse_File struct {
	File []byte `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}
type ApiFileDownloadResponse_FileBase64 struct {
	FileBase64 string `protobuf:"bytes,2,opt,name=fileBase64,proto3,oneof"`
}

func (*ApiFileDownloadResponse_File) isApiFileDownloadResponse_Ret()       {}
func (*ApiFileDownloadResponse_FileBase64) isApiFileDownloadResponse_Ret() {}

func (m *ApiFileDownloadResponse) GetRet() isApiFileDownloadResponse_Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *ApiFileDownloadResponse) GetFile() []byte {
	if x, ok := m.GetRet().(*ApiFileDownloadResponse_File); ok {
		return x.File
	}
	return nil
}

func (m *ApiFileDownloadResponse) GetFileBase64() string {
	if x, ok := m.GetRet().(*ApiFileDownloadResponse_FileBase64); ok {
		return x.FileBase64
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ApiFileDownloadResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ApiFileDownloadResponse_OneofMarshaler, _ApiFileDownloadResponse_OneofUnmarshaler, _ApiFileDownloadResponse_OneofSizer, []interface{}{
		(*ApiFileDownloadResponse_File)(nil),
		(*ApiFileDownloadResponse_FileBase64)(nil),
	}
}

func _ApiFileDownloadResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ApiFileDownloadResponse)
	// ret
	switch x := m.Ret.(type) {
	case *ApiFileDownloadResponse_File:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.File)
	case *ApiFileDownloadResponse_FileBase64:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.FileBase64)
	case nil:
	default:
		return fmt.Errorf("ApiFileDownloadResponse.Ret has unexpected type %T", x)
	}
	return nil
}

func _ApiFileDownloadResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ApiFileDownloadResponse)
	switch tag {
	case 1: // ret.file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Ret = &ApiFileDownloadResponse_File{x}
		return true, err
	case 2: // ret.fileBase64
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Ret = &ApiFileDownloadResponse_FileBase64{x}
		return true, err
	default:
		return false, nil
	}
}

func _ApiFileDownloadResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ApiFileDownloadResponse)
	// ret
	switch x := m.Ret.(type) {
	case *ApiFileDownloadResponse_File:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.File)))
		n += len(x.File)
	case *ApiFileDownloadResponse_FileBase64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.FileBase64)))
		n += len(x.FileBase64)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ApiFileDownloadRequest)(nil), "site.ApiFileDownloadRequest")
	proto.RegisterType((*ApiFileDownloadResponse)(nil), "site.ApiFileDownloadResponse")
}

func init() {
	proto.RegisterFile("site/api_file_download.proto", fileDescriptor_api_file_download_3c5c07279664bb30)
}

var fileDescriptor_api_file_download_3c5c07279664bb30 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0xb6, 0x16, 0x33, 0x14, 0x85, 0x55, 0x6a, 0x0e, 0x3d, 0x84, 0x1c, 0xa4, 0x17,
	0x93, 0x83, 0xe2, 0xdd, 0x20, 0x5a, 0x0f, 0x82, 0xc4, 0x4b, 0x29, 0x85, 0xb2, 0x4d, 0xc6, 0x74,
	0x31, 0xc9, 0xae, 0xfb, 0x87, 0x12, 0x1f, 0xc5, 0x47, 0xf2, 0xa9, 0x64, 0xb7, 0x45, 0xab, 0x9e,
	0x76, 0xe7, 0xf7, 0xf1, 0x1b, 0x3e, 0x06, 0xc6, 0x8a, 0x69, 0x4c, 0xa8, 0x60, 0xcb, 0x17, 0x56,
	0xe1, 0xb2, 0xe0, 0x9b, 0xa6, 0xe2, 0xb4, 0x88, 0x85, 0xe4, 0x9a, 0x93, 0xbe, 0x4d, 0xa3, 0x0f,
	0x0f, 0x46, 0x37, 0x82, 0xdd, 0xb1, 0x0a, 0x6f, 0x77, 0x79, 0x86, 0x6f, 0x06, 0x95, 0x26, 0x23,
	0x18, 0x58, 0xef, 0xa1, 0x08, 0xbc, 0xd0, 0x9b, 0xf8, 0xd9, 0x6e, 0x22, 0x11, 0x0c, 0x25, 0x6a,
	0x23, 0x9b, 0x94, 0x2a, 0xbc, 0xbe, 0x0a, 0xba, 0xa1, 0x37, 0x39, 0xcc, 0x7e, 0x31, 0x32, 0x06,
	0xbf, 0x46, 0xa5, 0x68, 0x69, 0xf5, 0x9e, 0xd3, 0x7f, 0x00, 0x39, 0x87, 0x23, 0xa6, 0xee, 0x25,
	0x37, 0xe2, 0x71, 0xcb, 0x82, 0xbe, 0xdb, 0xf1, 0x87, 0x46, 0x33, 0x38, 0xfb, 0xd7, 0x4d, 0x09,
	0xde, 0x28, 0x24, 0xa7, 0xd0, 0xb7, 0x75, 0x5c, 0xb5, 0xe1, 0xb4, 0x93, 0xb9, 0x89, 0x84, 0x00,
	0xf6, 0xdd, 0x2b, 0xe6, 0x4f, 0x3b, 0xd9, 0x1e, 0x4b, 0x0f, 0xa0, 0x27, 0x51, 0xa7, 0x33, 0x38,
	0xc9, 0x79, 0x1d, 0xbf, 0xd3, 0xaa, 0xdd, 0x9e, 0x23, 0xb6, 0xd7, 0x98, 0x27, 0x25, 0xd3, 0x6b,
	0xb3, 0x8a, 0x73, 0x5e, 0x27, 0x85, 0xc9, 0x5f, 0xf3, 0x35, 0xd5, 0xdf, 0x9f, 0x8b, 0x92, 0x6a,
	0xdc, 0xd0, 0x36, 0x71, 0x42, 0x62, 0x85, 0xcf, 0xee, 0xf1, 0x9c, 0x56, 0xed, 0xe2, 0xc9, 0x92,
	0xc5, 0x33, 0xd3, 0xb8, 0x1a, 0xb8, 0xf4, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x70, 0xa1, 0x6a,
	0x0f, 0x7d, 0x01, 0x00, 0x00,
}
