// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_group_quit.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.group.quit
//
type ApiGroupQuitRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupQuitRequest) Reset()         { *m = ApiGroupQuitRequest{} }
func (m *ApiGroupQuitRequest) String() string { return proto.CompactTextString(m) }
func (*ApiGroupQuitRequest) ProtoMessage()    {}
func (*ApiGroupQuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_quit_2a9dacd37fc2f954, []int{0}
}
func (m *ApiGroupQuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupQuitRequest.Unmarshal(m, b)
}
func (m *ApiGroupQuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupQuitRequest.Marshal(b, m, deterministic)
}
func (dst *ApiGroupQuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupQuitRequest.Merge(dst, src)
}
func (m *ApiGroupQuitRequest) XXX_Size() int {
	return xxx_messageInfo_ApiGroupQuitRequest.Size(m)
}
func (m *ApiGroupQuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupQuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupQuitRequest proto.InternalMessageInfo

func (m *ApiGroupQuitRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type ApiGroupQuitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupQuitResponse) Reset()         { *m = ApiGroupQuitResponse{} }
func (m *ApiGroupQuitResponse) String() string { return proto.CompactTextString(m) }
func (*ApiGroupQuitResponse) ProtoMessage()    {}
func (*ApiGroupQuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_quit_2a9dacd37fc2f954, []int{1}
}
func (m *ApiGroupQuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupQuitResponse.Unmarshal(m, b)
}
func (m *ApiGroupQuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupQuitResponse.Marshal(b, m, deterministic)
}
func (dst *ApiGroupQuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupQuitResponse.Merge(dst, src)
}
func (m *ApiGroupQuitResponse) XXX_Size() int {
	return xxx_messageInfo_ApiGroupQuitResponse.Size(m)
}
func (m *ApiGroupQuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupQuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupQuitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiGroupQuitRequest)(nil), "site.ApiGroupQuitRequest")
	proto.RegisterType((*ApiGroupQuitResponse)(nil), "site.ApiGroupQuitResponse")
}

func init() {
	proto.RegisterFile("site/api_group_quit.proto", fileDescriptor_api_group_quit_2a9dacd37fc2f954)
}

var fileDescriptor_api_group_quit_2a9dacd37fc2f954 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0x88, 0x2f, 0x2c, 0xcd, 0x2c, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x29, 0xe9, 0x73, 0x09, 0x3b, 0x16, 0x64,
	0xba, 0x83, 0x24, 0x03, 0x4b, 0x33, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24,
	0xb8, 0xd8, 0xc1, 0x1a, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25,
	0x31, 0x2e, 0x11, 0x54, 0x0d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4e, 0x11, 0x5c, 0xc2, 0xc9,
	0xf9, 0xb9, 0x7a, 0x55, 0x89, 0x39, 0x95, 0x10, 0x0b, 0xf4, 0x40, 0xe6, 0x47, 0xe9, 0xa7, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x94, 0x26, 0x67, 0x27, 0x67, 0x24,
	0x96, 0xc0, 0x19, 0xba, 0xe9, 0x89, 0x25, 0xa9, 0xe5, 0x89, 0x95, 0xfa, 0x60, 0x0d, 0xfa, 0x20,
	0x0d, 0xa7, 0x98, 0xf8, 0xa3, 0x12, 0x73, 0x2a, 0x63, 0x02, 0x40, 0x22, 0x31, 0xc1, 0x99, 0x25,
	0xa9, 0x49, 0x6c, 0x60, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x67, 0x03, 0x5b,
	0xcc, 0x00, 0x00, 0x00,
}
