// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_group_delete.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.group.delete
//
type ApiGroupDeleteRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupDeleteRequest) Reset()         { *m = ApiGroupDeleteRequest{} }
func (m *ApiGroupDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ApiGroupDeleteRequest) ProtoMessage()    {}
func (*ApiGroupDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_delete_a45bafb4bf722ffe, []int{0}
}
func (m *ApiGroupDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupDeleteRequest.Unmarshal(m, b)
}
func (m *ApiGroupDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *ApiGroupDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupDeleteRequest.Merge(dst, src)
}
func (m *ApiGroupDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ApiGroupDeleteRequest.Size(m)
}
func (m *ApiGroupDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupDeleteRequest proto.InternalMessageInfo

func (m *ApiGroupDeleteRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type ApiGroupDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupDeleteResponse) Reset()         { *m = ApiGroupDeleteResponse{} }
func (m *ApiGroupDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ApiGroupDeleteResponse) ProtoMessage()    {}
func (*ApiGroupDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_delete_a45bafb4bf722ffe, []int{1}
}
func (m *ApiGroupDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupDeleteResponse.Unmarshal(m, b)
}
func (m *ApiGroupDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *ApiGroupDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupDeleteResponse.Merge(dst, src)
}
func (m *ApiGroupDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ApiGroupDeleteResponse.Size(m)
}
func (m *ApiGroupDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupDeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiGroupDeleteRequest)(nil), "site.ApiGroupDeleteRequest")
	proto.RegisterType((*ApiGroupDeleteResponse)(nil), "site.ApiGroupDeleteResponse")
}

func init() {
	proto.RegisterFile("site/api_group_delete.proto", fileDescriptor_api_group_delete_a45bafb4bf722ffe)
}

var fileDescriptor_api_group_delete_a45bafb4bf722ffe = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0x88, 0x4f, 0x49, 0xcd, 0x49, 0x2d,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x2a, 0x19, 0x72, 0x89, 0x3a,
	0x16, 0x64, 0xba, 0x83, 0xa4, 0x5d, 0xc0, 0xb2, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x12, 0x5c, 0xec, 0x60, 0x4d, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae,
	0x92, 0x04, 0x97, 0x18, 0xba, 0x96, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa7, 0x08, 0x2e, 0xe1,
	0xe4, 0xfc, 0x5c, 0xbd, 0xaa, 0xc4, 0x9c, 0x4a, 0x88, 0x25, 0x7a, 0x20, 0x3b, 0xa2, 0xf4, 0xd3,
	0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x53, 0x4a, 0x93, 0xb3, 0x93, 0x33,
	0x12, 0x4b, 0xe0, 0x0c, 0xdd, 0xf4, 0xc4, 0x92, 0xd4, 0xf2, 0xc4, 0x4a, 0x7d, 0xb0, 0x06, 0x7d,
	0x90, 0x86, 0x53, 0x4c, 0xfc, 0x51, 0x89, 0x39, 0x95, 0x31, 0x01, 0x20, 0x91, 0x98, 0xe0, 0xcc,
	0x92, 0xd4, 0x24, 0x36, 0xb0, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x43, 0x70, 0xff, 0xf0,
	0xd2, 0x00, 0x00, 0x00,
}
