// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_anonymous_login.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.passport.anonymous.login
// error:
//     error.passport.anonymous.loginName.occupied
//
//
type ApiPassportAnonymousLoginRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportAnonymousLoginRequest) Reset()         { *m = ApiPassportAnonymousLoginRequest{} }
func (m *ApiPassportAnonymousLoginRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportAnonymousLoginRequest) ProtoMessage()    {}
func (*ApiPassportAnonymousLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_anonymous_login_2943d280426cacc9, []int{0}
}
func (m *ApiPassportAnonymousLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportAnonymousLoginRequest.Unmarshal(m, b)
}
func (m *ApiPassportAnonymousLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportAnonymousLoginRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportAnonymousLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportAnonymousLoginRequest.Merge(dst, src)
}
func (m *ApiPassportAnonymousLoginRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportAnonymousLoginRequest.Size(m)
}
func (m *ApiPassportAnonymousLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportAnonymousLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportAnonymousLoginRequest proto.InternalMessageInfo

func (m *ApiPassportAnonymousLoginRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

type ApiPassportAnonymousLoginResponse struct {
	PreSessionId         string   `protobuf:"bytes,1,opt,name=preSessionId,proto3" json:"preSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportAnonymousLoginResponse) Reset()         { *m = ApiPassportAnonymousLoginResponse{} }
func (m *ApiPassportAnonymousLoginResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportAnonymousLoginResponse) ProtoMessage()    {}
func (*ApiPassportAnonymousLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_anonymous_login_2943d280426cacc9, []int{1}
}
func (m *ApiPassportAnonymousLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportAnonymousLoginResponse.Unmarshal(m, b)
}
func (m *ApiPassportAnonymousLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportAnonymousLoginResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportAnonymousLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportAnonymousLoginResponse.Merge(dst, src)
}
func (m *ApiPassportAnonymousLoginResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportAnonymousLoginResponse.Size(m)
}
func (m *ApiPassportAnonymousLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportAnonymousLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportAnonymousLoginResponse proto.InternalMessageInfo

func (m *ApiPassportAnonymousLoginResponse) GetPreSessionId() string {
	if m != nil {
		return m.PreSessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiPassportAnonymousLoginRequest)(nil), "site.ApiPassportAnonymousLoginRequest")
	proto.RegisterType((*ApiPassportAnonymousLoginResponse)(nil), "site.ApiPassportAnonymousLoginResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_anonymous_login.proto", fileDescriptor_api_passport_anonymous_login_2943d280426cacc9)
}

var fileDescriptor_api_passport_anonymous_login_2943d280426cacc9 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xc8, 0x2f, 0x2a, 0x89, 0x4f, 0xcc,
	0xcb, 0xcf, 0xab, 0xcc, 0xcd, 0x2f, 0x2d, 0x8e, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x29, 0x54, 0x72, 0xe0, 0x52, 0x70, 0x2c, 0xc8, 0x0c, 0x80,
	0x2a, 0x75, 0x84, 0xa9, 0xf4, 0x01, 0x29, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92,
	0xe1, 0xe2, 0x04, 0x6b, 0xf4, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42,
	0x08, 0x28, 0xb9, 0x73, 0x29, 0xe2, 0x31, 0xa1, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x89,
	0x8b, 0xa7, 0xa0, 0x28, 0x35, 0x38, 0xb5, 0xb8, 0x38, 0x33, 0x3f, 0xcf, 0x33, 0x05, 0x6a, 0x0a,
	0x8a, 0x98, 0x53, 0x04, 0x97, 0x70, 0x72, 0x7e, 0xae, 0x5e, 0x55, 0x62, 0x4e, 0x25, 0xc4, 0x89,
	0x7a, 0x20, 0x17, 0x46, 0xe9, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea,
	0xa7, 0x94, 0x26, 0x67, 0x27, 0x67, 0x24, 0x96, 0xc0, 0x19, 0xba, 0xe9, 0x89, 0x25, 0xa9, 0xe5,
	0x89, 0x95, 0xfa, 0x60, 0x0d, 0xfa, 0x20, 0x0d, 0xa7, 0x98, 0xf8, 0xa3, 0x12, 0x73, 0x2a, 0x63,
	0x02, 0x40, 0x22, 0x31, 0xc1, 0x99, 0x25, 0xa9, 0x49, 0x6c, 0x60, 0x59, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0x15, 0x8b, 0xd8, 0x1c, 0x01, 0x00, 0x00,
}
