// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_gw_config.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/duckchat/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiGwConfigRequest struct {
	Type                 core.GatewayType `protobuf:"varint,1,opt,name=type,proto3,enum=core.GatewayType" json:"type,omitempty"`
	Host                 string           `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ApiGwConfigRequest) Reset()         { *m = ApiGwConfigRequest{} }
func (m *ApiGwConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ApiGwConfigRequest) ProtoMessage()    {}
func (*ApiGwConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_gw_config_addecb2c8b260f68, []int{0}
}
func (m *ApiGwConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGwConfigRequest.Unmarshal(m, b)
}
func (m *ApiGwConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGwConfigRequest.Marshal(b, m, deterministic)
}
func (dst *ApiGwConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGwConfigRequest.Merge(dst, src)
}
func (m *ApiGwConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ApiGwConfigRequest.Size(m)
}
func (m *ApiGwConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGwConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGwConfigRequest proto.InternalMessageInfo

func (m *ApiGwConfigRequest) GetType() core.GatewayType {
	if m != nil {
		return m.Type
	}
	return core.GatewayType_GatewayInvalid
}

func (m *ApiGwConfigRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type ApiGwConfigResponse struct {
	SocketIdSalt         string   `protobuf:"bytes,1,opt,name=socketIdSalt,proto3" json:"socketIdSalt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGwConfigResponse) Reset()         { *m = ApiGwConfigResponse{} }
func (m *ApiGwConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ApiGwConfigResponse) ProtoMessage()    {}
func (*ApiGwConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_gw_config_addecb2c8b260f68, []int{1}
}
func (m *ApiGwConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGwConfigResponse.Unmarshal(m, b)
}
func (m *ApiGwConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGwConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ApiGwConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGwConfigResponse.Merge(dst, src)
}
func (m *ApiGwConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ApiGwConfigResponse.Size(m)
}
func (m *ApiGwConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGwConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGwConfigResponse proto.InternalMessageInfo

func (m *ApiGwConfigResponse) GetSocketIdSalt() string {
	if m != nil {
		return m.SocketIdSalt
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiGwConfigRequest)(nil), "site.ApiGwConfigRequest")
	proto.RegisterType((*ApiGwConfigResponse)(nil), "site.ApiGwConfigResponse")
}

func init() {
	proto.RegisterFile("site/api_gw_config.proto", fileDescriptor_api_gw_config_addecb2c8b260f68)
}

var fileDescriptor_api_gw_config_addecb2c8b260f68 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0x28, 0xc2, 0x82, 0x4c, 0xcc, 0x2e, 0xc5, 0xd3, 0x28, 0x08, 0xbb, 0x98, 0x80,
	0x9e, 0x3c, 0xaa, 0x87, 0xe1, 0x49, 0xe9, 0x3c, 0xc8, 0x18, 0x8c, 0x2c, 0x7b, 0xa6, 0x61, 0x5d,
	0x5f, 0x5c, 0x5e, 0x29, 0xf1, 0x4f, 0xf4, 0xaf, 0x92, 0xa4, 0x20, 0xf4, 0xf6, 0xf8, 0xbe, 0xf7,
	0xfb, 0xf8, 0xb1, 0xc2, 0x5b, 0x02, 0xa9, 0x9c, 0xdd, 0x99, 0x7e, 0xa7, 0xb1, 0xfd, 0xb2, 0x46,
	0xb8, 0x33, 0x12, 0xf2, 0x3c, 0x36, 0x37, 0x33, 0x8d, 0x67, 0x90, 0x2d, 0xd0, 0x90, 0x96, 0x6f,
	0x8c, 0x3f, 0x39, 0xbb, 0xea, 0x5f, 0xd2, 0x6b, 0x05, 0xdf, 0x1d, 0x78, 0xe2, 0xb7, 0x2c, 0xa7,
	0xe0, 0xa0, 0xc8, 0x16, 0xd9, 0x72, 0x76, 0x7f, 0x2d, 0x22, 0x24, 0x56, 0x8a, 0xa0, 0x57, 0xe1,
	0x23, 0x38, 0xa8, 0x52, 0xcd, 0x39, 0xcb, 0x6b, 0xf4, 0x54, 0x4c, 0x16, 0xd9, 0x72, 0x5a, 0xa5,
	0xbb, 0x7c, 0x64, 0xf3, 0xd1, 0xa0, 0x77, 0xd8, 0x7a, 0xe0, 0x25, 0xbb, 0xf4, 0xa8, 0x8f, 0x40,
	0xaf, 0x87, 0xb5, 0x6a, 0x28, 0x2d, 0x4f, 0xab, 0x51, 0xf6, 0xfc, 0xc9, 0xe6, 0x1a, 0x4f, 0xe2,
	0x47, 0x35, 0x61, 0xb0, 0x13, 0x51, 0x79, 0x23, 0x8d, 0xa5, 0xba, 0xdb, 0x0b, 0x8d, 0x27, 0x79,
	0xe8, 0xf4, 0x51, 0xd7, 0x8a, 0xfe, 0x8f, 0x3b, 0x33, 0x58, 0xc9, 0x04, 0xc8, 0x08, 0xfc, 0x4e,
	0xae, 0x36, 0xaa, 0x09, 0xdb, 0xf7, 0x98, 0x6c, 0xd7, 0x96, 0x60, 0x7f, 0x91, 0xda, 0x87, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0xd4, 0x08, 0x6d, 0x1e, 0x01, 0x00, 0x00,
}
