// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_group_list.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.group.list
//
type ApiGroupListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupListRequest) Reset()         { *m = ApiGroupListRequest{} }
func (m *ApiGroupListRequest) String() string { return proto.CompactTextString(m) }
func (*ApiGroupListRequest) ProtoMessage()    {}
func (*ApiGroupListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_list_865032a8c5151991, []int{0}
}
func (m *ApiGroupListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupListRequest.Unmarshal(m, b)
}
func (m *ApiGroupListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupListRequest.Marshal(b, m, deterministic)
}
func (dst *ApiGroupListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupListRequest.Merge(dst, src)
}
func (m *ApiGroupListRequest) XXX_Size() int {
	return xxx_messageInfo_ApiGroupListRequest.Size(m)
}
func (m *ApiGroupListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupListRequest proto.InternalMessageInfo

func (m *ApiGroupListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ApiGroupListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ApiGroupListResponse struct {
	List                 []*core.PublicGroupProfile `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	ListIsMute           map[string]bool            `protobuf:"bytes,2,rep,name=listIsMute,proto3" json:"listIsMute,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	TotalCount           int32                      `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ApiGroupListResponse) Reset()         { *m = ApiGroupListResponse{} }
func (m *ApiGroupListResponse) String() string { return proto.CompactTextString(m) }
func (*ApiGroupListResponse) ProtoMessage()    {}
func (*ApiGroupListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_list_865032a8c5151991, []int{1}
}
func (m *ApiGroupListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupListResponse.Unmarshal(m, b)
}
func (m *ApiGroupListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupListResponse.Marshal(b, m, deterministic)
}
func (dst *ApiGroupListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupListResponse.Merge(dst, src)
}
func (m *ApiGroupListResponse) XXX_Size() int {
	return xxx_messageInfo_ApiGroupListResponse.Size(m)
}
func (m *ApiGroupListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupListResponse proto.InternalMessageInfo

func (m *ApiGroupListResponse) GetList() []*core.PublicGroupProfile {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ApiGroupListResponse) GetListIsMute() map[string]bool {
	if m != nil {
		return m.ListIsMute
	}
	return nil
}

func (m *ApiGroupListResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ApiGroupListRequest)(nil), "site.ApiGroupListRequest")
	proto.RegisterType((*ApiGroupListResponse)(nil), "site.ApiGroupListResponse")
	proto.RegisterMapType((map[string]bool)(nil), "site.ApiGroupListResponse.ListIsMuteEntry")
}

func init() {
	proto.RegisterFile("site/api_group_list.proto", fileDescriptor_api_group_list_865032a8c5151991)
}

var fileDescriptor_api_group_list_865032a8c5151991 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x65, 0xa6, 0x3f, 0x7c, 0xdf, 0x75, 0xd1, 0x92, 0x16, 0x19, 0xbb, 0x90, 0xd2, 0x55, 0x11,
	0xcd, 0x80, 0x6e, 0x44, 0x70, 0xa1, 0x45, 0x44, 0xa9, 0x50, 0xe2, 0x46, 0x4a, 0xa1, 0xa4, 0x31,
	0x6d, 0x43, 0xd3, 0x66, 0x9c, 0xdc, 0x28, 0xe3, 0x23, 0xfa, 0x32, 0xbe, 0x82, 0x24, 0x23, 0xa5,
	0x8a, 0xab, 0xb9, 0xf7, 0xfc, 0xdc, 0x39, 0x27, 0x70, 0x60, 0x15, 0xca, 0x94, 0x67, 0x6a, 0xba,
	0xc8, 0x8d, 0xcb, 0xa6, 0x5a, 0x59, 0xa4, 0x59, 0x6e, 0xd0, 0x90, 0xaa, 0xa7, 0x3a, 0x4d, 0x61,
	0x72, 0x99, 0x06, 0xb2, 0xc4, 0x7b, 0x03, 0x68, 0x5d, 0x65, 0xea, 0xd6, 0x23, 0x43, 0x65, 0x91,
	0xc9, 0x17, 0x27, 0x2d, 0x92, 0x7d, 0xa8, 0x9b, 0xf9, 0xdc, 0x4a, 0x4c, 0xa2, 0x6e, 0xd4, 0xaf,
	0xb1, 0xef, 0x8d, 0xb4, 0xa1, 0x26, 0x8c, 0xdb, 0x60, 0x12, 0x07, 0xb8, 0x5c, 0x7a, 0x9f, 0x11,
	0xb4, 0x7f, 0x5e, 0xb1, 0x99, 0xd9, 0x58, 0x49, 0x8e, 0xa1, 0xea, 0x33, 0x24, 0x51, 0xb7, 0xd2,
	0xdf, 0x3b, 0x4d, 0xa8, 0xff, 0x3d, 0x1d, 0xb9, 0x99, 0x56, 0x22, 0x88, 0x47, 0xb9, 0x99, 0x2b,
	0x2d, 0x59, 0x50, 0x91, 0x7b, 0x00, 0xff, 0xbd, 0xb3, 0x0f, 0x0e, 0x65, 0x12, 0x07, 0xcf, 0x11,
	0xf5, 0xc1, 0xe9, 0x5f, 0xd7, 0xe9, 0x70, 0x2b, 0xbe, 0xd9, 0x60, 0x5e, 0xb0, 0x1d, 0x37, 0x39,
	0x04, 0x40, 0x83, 0x5c, 0x0f, 0x42, 0xda, 0x4a, 0x48, 0xbb, 0x83, 0x74, 0x2e, 0xa1, 0xf1, 0xcb,
	0x4e, 0x9a, 0x50, 0x59, 0xc9, 0x22, 0x14, 0xfe, 0xcf, 0xfc, 0xe8, 0xdb, 0xbe, 0x72, 0xed, 0x64,
	0x68, 0xfb, 0x8f, 0x95, 0xcb, 0x45, 0x7c, 0x1e, 0x5d, 0x3f, 0x41, 0x4b, 0x98, 0x35, 0x7d, 0xe7,
	0xba, 0x28, 0x1f, 0x32, 0xc4, 0x1c, 0xa7, 0x0b, 0x85, 0x4b, 0x37, 0xa3, 0xc2, 0xac, 0xd3, 0x67,
	0x27, 0x56, 0x62, 0xc9, 0x71, 0x3b, 0x9c, 0x2c, 0x38, 0xca, 0x37, 0x5e, 0xa4, 0xc1, 0x90, 0x7a,
	0xc3, 0x47, 0xdc, 0x18, 0x73, 0x5d, 0x4c, 0x46, 0x1e, 0x99, 0x3c, 0x2a, 0x94, 0xb3, 0x7a, 0x60,
	0xcf, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0xf5, 0x7d, 0x18, 0xcc, 0x01, 0x00, 0x00,
}
