// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_friend_update.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiFriendUpdateType int32

const (
	ApiFriendUpdateType_ApiFriendUpdateInvalid ApiFriendUpdateType = 0
	ApiFriendUpdateType_ApiFriendUpdateRemark  ApiFriendUpdateType = 1
	ApiFriendUpdateType_ApiFriendUpdateIsMute  ApiFriendUpdateType = 2
)

var ApiFriendUpdateType_name = map[int32]string{
	0: "ApiFriendUpdateInvalid",
	1: "ApiFriendUpdateRemark",
	2: "ApiFriendUpdateIsMute",
}
var ApiFriendUpdateType_value = map[string]int32{
	"ApiFriendUpdateInvalid": 0,
	"ApiFriendUpdateRemark":  1,
	"ApiFriendUpdateIsMute":  2,
}

func (x ApiFriendUpdateType) String() string {
	return proto.EnumName(ApiFriendUpdateType_name, int32(x))
}
func (ApiFriendUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_update_217f56d52d0aef51, []int{0}
}

type ApiFriendUpdateValue struct {
	Type ApiFriendUpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=site.ApiFriendUpdateType" json:"type,omitempty"`
	// Types that are valid to be assigned to Fields:
	//	*ApiFriendUpdateValue_Remark
	//	*ApiFriendUpdateValue_IsMute
	Fields               isApiFriendUpdateValue_Fields `protobuf_oneof:"fields"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ApiFriendUpdateValue) Reset()         { *m = ApiFriendUpdateValue{} }
func (m *ApiFriendUpdateValue) String() string { return proto.CompactTextString(m) }
func (*ApiFriendUpdateValue) ProtoMessage()    {}
func (*ApiFriendUpdateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_update_217f56d52d0aef51, []int{0}
}
func (m *ApiFriendUpdateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendUpdateValue.Unmarshal(m, b)
}
func (m *ApiFriendUpdateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendUpdateValue.Marshal(b, m, deterministic)
}
func (dst *ApiFriendUpdateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendUpdateValue.Merge(dst, src)
}
func (m *ApiFriendUpdateValue) XXX_Size() int {
	return xxx_messageInfo_ApiFriendUpdateValue.Size(m)
}
func (m *ApiFriendUpdateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendUpdateValue.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendUpdateValue proto.InternalMessageInfo

type isApiFriendUpdateValue_Fields interface {
	isApiFriendUpdateValue_Fields()
}

type ApiFriendUpdateValue_Remark struct {
	Remark string `protobuf:"bytes,2,opt,name=remark,proto3,oneof"`
}
type ApiFriendUpdateValue_IsMute struct {
	IsMute bool `protobuf:"varint,3,opt,name=isMute,proto3,oneof"`
}

func (*ApiFriendUpdateValue_Remark) isApiFriendUpdateValue_Fields() {}
func (*ApiFriendUpdateValue_IsMute) isApiFriendUpdateValue_Fields() {}

func (m *ApiFriendUpdateValue) GetFields() isApiFriendUpdateValue_Fields {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ApiFriendUpdateValue) GetType() ApiFriendUpdateType {
	if m != nil {
		return m.Type
	}
	return ApiFriendUpdateType_ApiFriendUpdateInvalid
}

func (m *ApiFriendUpdateValue) GetRemark() string {
	if x, ok := m.GetFields().(*ApiFriendUpdateValue_Remark); ok {
		return x.Remark
	}
	return ""
}

func (m *ApiFriendUpdateValue) GetIsMute() bool {
	if x, ok := m.GetFields().(*ApiFriendUpdateValue_IsMute); ok {
		return x.IsMute
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ApiFriendUpdateValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ApiFriendUpdateValue_OneofMarshaler, _ApiFriendUpdateValue_OneofUnmarshaler, _ApiFriendUpdateValue_OneofSizer, []interface{}{
		(*ApiFriendUpdateValue_Remark)(nil),
		(*ApiFriendUpdateValue_IsMute)(nil),
	}
}

func _ApiFriendUpdateValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ApiFriendUpdateValue)
	// fields
	switch x := m.Fields.(type) {
	case *ApiFriendUpdateValue_Remark:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Remark)
	case *ApiFriendUpdateValue_IsMute:
		t := uint64(0)
		if x.IsMute {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ApiFriendUpdateValue.Fields has unexpected type %T", x)
	}
	return nil
}

func _ApiFriendUpdateValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ApiFriendUpdateValue)
	switch tag {
	case 2: // fields.remark
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Fields = &ApiFriendUpdateValue_Remark{x}
		return true, err
	case 3: // fields.isMute
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Fields = &ApiFriendUpdateValue_IsMute{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _ApiFriendUpdateValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ApiFriendUpdateValue)
	// fields
	switch x := m.Fields.(type) {
	case *ApiFriendUpdateValue_Remark:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Remark)))
		n += len(x.Remark)
	case *ApiFriendUpdateValue_IsMute:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// *
//
// action: api.friend.update
//
type ApiFriendUpdateRequest struct {
	UserId               string                  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Values               []*ApiFriendUpdateValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ApiFriendUpdateRequest) Reset()         { *m = ApiFriendUpdateRequest{} }
func (m *ApiFriendUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFriendUpdateRequest) ProtoMessage()    {}
func (*ApiFriendUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_update_217f56d52d0aef51, []int{1}
}
func (m *ApiFriendUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendUpdateRequest.Unmarshal(m, b)
}
func (m *ApiFriendUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFriendUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendUpdateRequest.Merge(dst, src)
}
func (m *ApiFriendUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFriendUpdateRequest.Size(m)
}
func (m *ApiFriendUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendUpdateRequest proto.InternalMessageInfo

func (m *ApiFriendUpdateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ApiFriendUpdateRequest) GetValues() []*ApiFriendUpdateValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type ApiFriendUpdateResponse struct {
	Profile              *core.FriendUserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ApiFriendUpdateResponse) Reset()         { *m = ApiFriendUpdateResponse{} }
func (m *ApiFriendUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFriendUpdateResponse) ProtoMessage()    {}
func (*ApiFriendUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_update_217f56d52d0aef51, []int{2}
}
func (m *ApiFriendUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendUpdateResponse.Unmarshal(m, b)
}
func (m *ApiFriendUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFriendUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendUpdateResponse.Merge(dst, src)
}
func (m *ApiFriendUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFriendUpdateResponse.Size(m)
}
func (m *ApiFriendUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendUpdateResponse proto.InternalMessageInfo

func (m *ApiFriendUpdateResponse) GetProfile() *core.FriendUserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiFriendUpdateValue)(nil), "site.ApiFriendUpdateValue")
	proto.RegisterType((*ApiFriendUpdateRequest)(nil), "site.ApiFriendUpdateRequest")
	proto.RegisterType((*ApiFriendUpdateResponse)(nil), "site.ApiFriendUpdateResponse")
	proto.RegisterEnum("site.ApiFriendUpdateType", ApiFriendUpdateType_name, ApiFriendUpdateType_value)
}

func init() {
	proto.RegisterFile("site/api_friend_update.proto", fileDescriptor_api_friend_update_217f56d52d0aef51)
}

var fileDescriptor_api_friend_update_217f56d52d0aef51 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x5f, 0x6b, 0xea, 0x30,
	0x1c, 0xb5, 0x55, 0x7a, 0x35, 0xc2, 0x55, 0xe2, 0xbd, 0x5a, 0x65, 0x0f, 0xc5, 0xa7, 0x32, 0xb0,
	0x65, 0xdd, 0x27, 0x98, 0x0f, 0x63, 0xc2, 0x06, 0xd2, 0xfd, 0x61, 0x88, 0x20, 0xb1, 0xfd, 0xa9,
	0xc1, 0x6a, 0xb3, 0x24, 0x75, 0x74, 0xaf, 0xfb, 0x76, 0xfb, 0x54, 0x23, 0x69, 0xb7, 0x07, 0xf5,
	0x2d, 0xbf, 0xdf, 0x39, 0x27, 0x39, 0xe7, 0x04, 0x5d, 0x08, 0x2a, 0xc1, 0x27, 0x8c, 0x2e, 0x56,
	0x9c, 0xc2, 0x3e, 0x5e, 0x64, 0x2c, 0x26, 0x12, 0x3c, 0xc6, 0x53, 0x99, 0xe2, 0x9a, 0x42, 0x07,
	0xad, 0x28, 0xe5, 0xe0, 0x67, 0x02, 0x78, 0xb1, 0x1e, 0x7e, 0x1a, 0xe8, 0xdf, 0x0d, 0xa3, 0xb7,
	0x5a, 0xf1, 0xac, 0x05, 0x2f, 0x24, 0xc9, 0x00, 0x8f, 0x50, 0x4d, 0xe6, 0x0c, 0x6c, 0xc3, 0x31,
	0xdc, 0xbf, 0x41, 0xdf, 0x53, 0x72, 0xef, 0x88, 0xf9, 0x94, 0x33, 0x08, 0x35, 0x0d, 0xdb, 0xc8,
	0xe2, 0xb0, 0x23, 0x7c, 0x6b, 0x9b, 0x8e, 0xe1, 0x36, 0xee, 0x2a, 0x61, 0x39, 0x2b, 0x84, 0x8a,
	0x87, 0x4c, 0x82, 0x5d, 0x75, 0x0c, 0xb7, 0xae, 0x90, 0x62, 0x1e, 0xd7, 0x91, 0xb5, 0xa2, 0x90,
	0xc4, 0x62, 0x18, 0xa3, 0xee, 0xd1, 0xd5, 0x21, 0xbc, 0x65, 0x20, 0x24, 0xee, 0x22, 0x4b, 0xb9,
	0x9d, 0xc4, 0xda, 0x48, 0x23, 0x2c, 0x27, 0x1c, 0x20, 0xeb, 0xa0, 0x7c, 0x0a, 0xdb, 0x74, 0xaa,
	0x6e, 0x33, 0x18, 0x9c, 0x35, 0xa8, 0xa3, 0x84, 0x25, 0x73, 0x78, 0x8f, 0x7a, 0x27, 0xaf, 0x08,
	0x96, 0xee, 0x05, 0xe0, 0x2b, 0xf4, 0x87, 0xf1, 0x74, 0x45, 0x93, 0x22, 0x70, 0x33, 0xe8, 0x79,
	0xaa, 0x29, 0xaf, 0x24, 0x0b, 0xe0, 0xd3, 0x02, 0x0e, 0x7f, 0x78, 0x97, 0x6b, 0xd4, 0x39, 0x53,
	0x07, 0x1e, 0x9c, 0x44, 0x99, 0xec, 0x0f, 0x24, 0xa1, 0x71, 0xbb, 0x82, 0xfb, 0xe8, 0xff, 0x89,
	0x01, 0xd5, 0x51, 0xdb, 0x38, 0x03, 0x4d, 0x74, 0x49, 0x6d, 0x73, 0xfc, 0x8a, 0x3a, 0x51, 0xba,
	0xf3, 0x3e, 0x48, 0x92, 0x17, 0x9f, 0xa6, 0xa3, 0xce, 0xfc, 0x35, 0x95, 0x9b, 0x6c, 0xe9, 0x45,
	0xe9, 0xce, 0x8f, 0xb3, 0x68, 0x1b, 0x6d, 0x88, 0xfc, 0x3d, 0x8c, 0xd6, 0x44, 0xc2, 0x3b, 0xc9,
	0x7d, 0x2d, 0xf0, 0x95, 0xe0, 0xcb, 0x6c, 0xcd, 0x48, 0x92, 0xcf, 0xa7, 0x6a, 0x33, 0x7f, 0xa4,
	0x12, 0x96, 0x96, 0x46, 0xaf, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x78, 0x52, 0x96, 0x68, 0x3a,
	0x02, 0x00, 0x00,
}
