// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_plugin_list.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/duckchat/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.plugin.list
//
type ApiPluginListRequest struct {
	UsageType            core.PluginUsageType `protobuf:"varint,1,opt,name=usageType,proto3,enum=core.PluginUsageType" json:"usageType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApiPluginListRequest) Reset()         { *m = ApiPluginListRequest{} }
func (m *ApiPluginListRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPluginListRequest) ProtoMessage()    {}
func (*ApiPluginListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_plugin_list_b55bb34b11090f6f, []int{0}
}
func (m *ApiPluginListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPluginListRequest.Unmarshal(m, b)
}
func (m *ApiPluginListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPluginListRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPluginListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPluginListRequest.Merge(dst, src)
}
func (m *ApiPluginListRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPluginListRequest.Size(m)
}
func (m *ApiPluginListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPluginListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPluginListRequest proto.InternalMessageInfo

func (m *ApiPluginListRequest) GetUsageType() core.PluginUsageType {
	if m != nil {
		return m.UsageType
	}
	return core.PluginUsageType_PluginUsageNone
}

type ApiPluginListResponse struct {
	List                 []*core.PluginProfile `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ApiPluginListResponse) Reset()         { *m = ApiPluginListResponse{} }
func (m *ApiPluginListResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPluginListResponse) ProtoMessage()    {}
func (*ApiPluginListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_plugin_list_b55bb34b11090f6f, []int{1}
}
func (m *ApiPluginListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPluginListResponse.Unmarshal(m, b)
}
func (m *ApiPluginListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPluginListResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPluginListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPluginListResponse.Merge(dst, src)
}
func (m *ApiPluginListResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPluginListResponse.Size(m)
}
func (m *ApiPluginListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPluginListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPluginListResponse proto.InternalMessageInfo

func (m *ApiPluginListResponse) GetList() []*core.PluginProfile {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiPluginListRequest)(nil), "site.ApiPluginListRequest")
	proto.RegisterType((*ApiPluginListResponse)(nil), "site.ApiPluginListResponse")
}

func init() {
	proto.RegisterFile("site/api_plugin_list.proto", fileDescriptor_api_plugin_list_b55bb34b11090f6f)
}

var fileDescriptor_api_plugin_list_b55bb34b11090f6f = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0x2d, 0x82, 0x11, 0x14, 0xa7, 0x16, 0x4a, 0x57, 0xa5, 0x1b, 0xbb, 0x31, 0x81,
	0xf6, 0x05, 0xd4, 0xad, 0x2e, 0x86, 0x51, 0x41, 0x4a, 0xa1, 0xa4, 0xf1, 0x9a, 0x5e, 0x4c, 0x9b,
	0x38, 0xb9, 0x41, 0xe2, 0x23, 0xfa, 0x54, 0x92, 0x04, 0x7f, 0xe8, 0xee, 0x72, 0xbf, 0x73, 0x0e,
	0x1f, 0x1b, 0x79, 0x24, 0x10, 0xd2, 0xe1, 0xca, 0x99, 0xa0, 0x71, 0xb7, 0x32, 0xe8, 0x89, 0xbb,
	0xce, 0x92, 0xad, 0x7b, 0x89, 0x8d, 0xce, 0x95, 0xed, 0x40, 0x14, 0x5a, 0xc0, 0xe4, 0x8e, 0x5d,
	0xdc, 0x38, 0x6c, 0xf2, 0xeb, 0x1e, 0x3d, 0xb5, 0xf0, 0x1e, 0xc0, 0x53, 0x3d, 0x67, 0xc7, 0xc1,
	0x4b, 0x0d, 0x8f, 0xd1, 0xc1, 0xb0, 0x1a, 0x57, 0xd3, 0xd3, 0xd9, 0x80, 0xa7, 0x3a, 0x2f, 0xd9,
	0xa7, 0x1f, 0xd8, 0xfe, 0xe5, 0x26, 0xd7, 0x6c, 0xb0, 0x37, 0xe6, 0x9d, 0xdd, 0x79, 0xa8, 0x2f,
	0x59, 0x2f, 0xc9, 0x0c, 0xab, 0xf1, 0xe1, 0xf4, 0x64, 0xd6, 0xff, 0x3f, 0xd4, 0x74, 0xf6, 0x15,
	0x0d, 0xb4, 0x39, 0x70, 0xfb, 0xcc, 0xfa, 0xca, 0x6e, 0xf9, 0xa7, 0x34, 0xb1, 0x08, 0xf2, 0x24,
	0xbe, 0x10, 0x1a, 0x69, 0x13, 0xd6, 0x5c, 0xd9, 0xad, 0x78, 0x09, 0xea, 0x4d, 0x6d, 0x24, 0xfd,
	0x1e, 0x57, 0x5a, 0x12, 0x7c, 0xc8, 0x28, 0x72, 0x41, 0xa4, 0xc2, 0xd7, 0xc1, 0xd9, 0x42, 0x9a,
	0xb8, 0x6c, 0xd2, 0x67, 0xf9, 0x80, 0x04, 0xeb, 0xa3, 0x4c, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x35, 0x2e, 0xce, 0xee, 0x26, 0x01, 0x00, 0x00,
}
