// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_password_findPassword.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.passport.password.findPassword
//
//
type ApiPassportPasswordFindPasswordRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordFindPasswordRequest) Reset() {
	*m = ApiPassportPasswordFindPasswordRequest{}
}
func (m *ApiPassportPasswordFindPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordFindPasswordRequest) ProtoMessage()    {}
func (*ApiPassportPasswordFindPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_findPassword_22ef951bcfba5bf5, []int{0}
}
func (m *ApiPassportPasswordFindPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordFindPasswordRequest.Unmarshal(m, b)
}
func (m *ApiPassportPasswordFindPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordFindPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordFindPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordFindPasswordRequest.Merge(dst, src)
}
func (m *ApiPassportPasswordFindPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordFindPasswordRequest.Size(m)
}
func (m *ApiPassportPasswordFindPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordFindPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordFindPasswordRequest proto.InternalMessageInfo

func (m *ApiPassportPasswordFindPasswordRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

type ApiPassportPasswordFindPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordFindPasswordResponse) Reset() {
	*m = ApiPassportPasswordFindPasswordResponse{}
}
func (m *ApiPassportPasswordFindPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordFindPasswordResponse) ProtoMessage()    {}
func (*ApiPassportPasswordFindPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_findPassword_22ef951bcfba5bf5, []int{1}
}
func (m *ApiPassportPasswordFindPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordFindPasswordResponse.Unmarshal(m, b)
}
func (m *ApiPassportPasswordFindPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordFindPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordFindPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordFindPasswordResponse.Merge(dst, src)
}
func (m *ApiPassportPasswordFindPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordFindPasswordResponse.Size(m)
}
func (m *ApiPassportPasswordFindPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordFindPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordFindPasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiPassportPasswordFindPasswordRequest)(nil), "site.ApiPassportPasswordFindPasswordRequest")
	proto.RegisterType((*ApiPassportPasswordFindPasswordResponse)(nil), "site.ApiPassportPasswordFindPasswordResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_password_findPassword.proto", fileDescriptor_api_passport_password_findPassword_22ef951bcfba5bf5)
}

var fileDescriptor_api_passport_password_findPassword_22ef951bcfba5bf5 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2d, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xc8, 0x2f, 0x2a, 0x01, 0x33, 0xca,
	0xf3, 0x8b, 0x52, 0xe2, 0xd3, 0x32, 0xf3, 0x52, 0x02, 0xa0, 0x1c, 0xbd, 0x82, 0xa2, 0xfc, 0x92,
	0x7c, 0x21, 0x16, 0x90, 0x72, 0x25, 0x37, 0x2e, 0x35, 0xc7, 0x82, 0xcc, 0x00, 0xa8, 0x06, 0x98,
	0x12, 0x37, 0x24, 0xe5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0x39,
	0xf9, 0xe9, 0x99, 0x79, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08,
	0x01, 0x25, 0x4d, 0x2e, 0x75, 0x82, 0xe6, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x3a, 0x45, 0x70,
	0x09, 0x27, 0xe7, 0xe7, 0xea, 0x55, 0x25, 0xe6, 0x54, 0x42, 0x9c, 0xa2, 0x07, 0x72, 0x49, 0x94,
	0x7e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x4a, 0x69, 0x72, 0x76,
	0x72, 0x46, 0x62, 0x09, 0x9c, 0xa1, 0x9b, 0x9e, 0x58, 0x92, 0x5a, 0x9e, 0x58, 0xa9, 0x0f, 0xd6,
	0xa0, 0x0f, 0xd2, 0x70, 0x8a, 0x89, 0x3f, 0x2a, 0x31, 0xa7, 0x32, 0x26, 0x00, 0x24, 0x12, 0x13,
	0x9c, 0x59, 0x92, 0x9a, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x25, 0xd8,
	0x89, 0x6d, 0x0a, 0x01, 0x00, 0x00,
}
