// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_site_login.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.site.login
//
// error:
//     error.needRegister
type ApiSiteLoginRequest struct {
	PreSessionId         string   `protobuf:"bytes,1,opt,name=preSessionId,proto3" json:"preSessionId,omitempty"`
	DevicePubkPem        string   `protobuf:"bytes,2,opt,name=devicePubkPem,proto3" json:"devicePubkPem,omitempty"`
	LoginName            string   `protobuf:"bytes,3,opt,name=loginName,proto3" json:"loginName,omitempty"`
	IsRegister           bool     `protobuf:"varint,4,opt,name=isRegister,proto3" json:"isRegister,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiSiteLoginRequest) Reset()         { *m = ApiSiteLoginRequest{} }
func (m *ApiSiteLoginRequest) String() string { return proto.CompactTextString(m) }
func (*ApiSiteLoginRequest) ProtoMessage()    {}
func (*ApiSiteLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_site_login_5670f18de84e9636, []int{0}
}
func (m *ApiSiteLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSiteLoginRequest.Unmarshal(m, b)
}
func (m *ApiSiteLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSiteLoginRequest.Marshal(b, m, deterministic)
}
func (dst *ApiSiteLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSiteLoginRequest.Merge(dst, src)
}
func (m *ApiSiteLoginRequest) XXX_Size() int {
	return xxx_messageInfo_ApiSiteLoginRequest.Size(m)
}
func (m *ApiSiteLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSiteLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSiteLoginRequest proto.InternalMessageInfo

func (m *ApiSiteLoginRequest) GetPreSessionId() string {
	if m != nil {
		return m.PreSessionId
	}
	return ""
}

func (m *ApiSiteLoginRequest) GetDevicePubkPem() string {
	if m != nil {
		return m.DevicePubkPem
	}
	return ""
}

func (m *ApiSiteLoginRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *ApiSiteLoginRequest) GetIsRegister() bool {
	if m != nil {
		return m.IsRegister
	}
	return false
}

type ApiSiteLoginResponse struct {
	SessionId            string               `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Profile              *core.AllUserProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApiSiteLoginResponse) Reset()         { *m = ApiSiteLoginResponse{} }
func (m *ApiSiteLoginResponse) String() string { return proto.CompactTextString(m) }
func (*ApiSiteLoginResponse) ProtoMessage()    {}
func (*ApiSiteLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_site_login_5670f18de84e9636, []int{1}
}
func (m *ApiSiteLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSiteLoginResponse.Unmarshal(m, b)
}
func (m *ApiSiteLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSiteLoginResponse.Marshal(b, m, deterministic)
}
func (dst *ApiSiteLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSiteLoginResponse.Merge(dst, src)
}
func (m *ApiSiteLoginResponse) XXX_Size() int {
	return xxx_messageInfo_ApiSiteLoginResponse.Size(m)
}
func (m *ApiSiteLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSiteLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSiteLoginResponse proto.InternalMessageInfo

func (m *ApiSiteLoginResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ApiSiteLoginResponse) GetProfile() *core.AllUserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiSiteLoginRequest)(nil), "site.ApiSiteLoginRequest")
	proto.RegisterType((*ApiSiteLoginResponse)(nil), "site.ApiSiteLoginResponse")
}

func init() {
	proto.RegisterFile("site/api_site_login.proto", fileDescriptor_api_site_login_5670f18de84e9636)
}

var fileDescriptor_api_site_login_5670f18de84e9636 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xd1, 0x4a, 0xf3, 0x30,
	0x14, 0xc7, 0xe9, 0xbe, 0xf1, 0xe9, 0xa2, 0x32, 0xc8, 0x76, 0x51, 0x45, 0x64, 0x14, 0x2f, 0x76,
	0x63, 0x02, 0xfa, 0x04, 0xf3, 0x4e, 0x10, 0x29, 0x1d, 0x82, 0x8c, 0xc1, 0x48, 0xd3, 0x63, 0x17,
	0x96, 0x36, 0x31, 0x49, 0x95, 0xfa, 0x2e, 0xbe, 0x90, 0x4f, 0x25, 0x49, 0xd1, 0x59, 0xef, 0x0e,
	0xbf, 0xf3, 0x3f, 0xe1, 0x97, 0x3f, 0x3a, 0xb5, 0xc2, 0x01, 0x65, 0x5a, 0x6c, 0xfc, 0xb0, 0x91,
	0xaa, 0x14, 0x35, 0xd1, 0x46, 0x39, 0x85, 0x87, 0x9e, 0x9c, 0x8d, 0xb9, 0x32, 0x40, 0x1b, 0x0b,
	0xa6, 0xc3, 0xc9, 0x47, 0x84, 0x26, 0x0b, 0x2d, 0x96, 0xc2, 0xc1, 0xbd, 0x4f, 0x67, 0xf0, 0xd2,
	0x80, 0x75, 0x38, 0x41, 0xc7, 0xda, 0xc0, 0x12, 0xac, 0x15, 0xaa, 0xbe, 0x2b, 0xe2, 0x68, 0x16,
	0xcd, 0x47, 0x59, 0x8f, 0xe1, 0x4b, 0x74, 0x52, 0xc0, 0xab, 0xe0, 0x90, 0x36, 0xf9, 0x2e, 0x85,
	0x2a, 0x1e, 0x84, 0x50, 0x1f, 0xe2, 0x73, 0x34, 0x0a, 0x1e, 0x0f, 0xac, 0x82, 0xf8, 0x5f, 0x48,
	0xec, 0x01, 0xbe, 0x40, 0x48, 0xd8, 0x0c, 0x4a, 0x61, 0x1d, 0x98, 0x78, 0x38, 0x8b, 0xe6, 0x87,
	0xd9, 0x2f, 0x92, 0x14, 0x68, 0xda, 0xd7, 0xb3, 0x5a, 0xd5, 0x16, 0xfc, 0xab, 0xf6, 0x8f, 0xdc,
	0x1e, 0x60, 0x82, 0x0e, 0xb4, 0x51, 0xcf, 0x42, 0x42, 0x70, 0x3a, 0xba, 0x9e, 0x12, 0xff, 0x71,
	0xb2, 0x90, 0xf2, 0xd1, 0x82, 0x49, 0xbb, 0x5d, 0xf6, 0x1d, 0xba, 0x7d, 0x42, 0x13, 0xae, 0x2a,
	0xf2, 0xce, 0x64, 0xdb, 0xf5, 0x42, 0x7c, 0x5b, 0x2b, 0x5a, 0x0a, 0xb7, 0x6d, 0x72, 0xc2, 0x55,
	0x45, 0x8b, 0x86, 0xef, 0xf8, 0x96, 0xb9, 0x9f, 0xe1, 0xaa, 0x64, 0x0e, 0xde, 0x58, 0x4b, 0xc3,
	0x01, 0xf5, 0x07, 0x9f, 0x83, 0xf1, 0x8a, 0xc9, 0x76, 0x9d, 0x7a, 0xb2, 0xf6, 0xd2, 0xf9, 0xff,
	0xb0, 0xbd, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x33, 0xa7, 0x54, 0x9a, 0x01, 0x00, 0x00,
}
