// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_friend_profile.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.friend.profile
//
type ApiFriendProfileRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFriendProfileRequest) Reset()         { *m = ApiFriendProfileRequest{} }
func (m *ApiFriendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFriendProfileRequest) ProtoMessage()    {}
func (*ApiFriendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_profile_3715cad4bb7bc1be, []int{0}
}
func (m *ApiFriendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendProfileRequest.Unmarshal(m, b)
}
func (m *ApiFriendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendProfileRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFriendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendProfileRequest.Merge(dst, src)
}
func (m *ApiFriendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFriendProfileRequest.Size(m)
}
func (m *ApiFriendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendProfileRequest proto.InternalMessageInfo

func (m *ApiFriendProfileRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ApiFriendProfileResponse struct {
	Profile              *core.FriendUserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ApiFriendProfileResponse) Reset()         { *m = ApiFriendProfileResponse{} }
func (m *ApiFriendProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFriendProfileResponse) ProtoMessage()    {}
func (*ApiFriendProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_profile_3715cad4bb7bc1be, []int{1}
}
func (m *ApiFriendProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendProfileResponse.Unmarshal(m, b)
}
func (m *ApiFriendProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendProfileResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFriendProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendProfileResponse.Merge(dst, src)
}
func (m *ApiFriendProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFriendProfileResponse.Size(m)
}
func (m *ApiFriendProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendProfileResponse proto.InternalMessageInfo

func (m *ApiFriendProfileResponse) GetProfile() *core.FriendUserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiFriendProfileRequest)(nil), "site.ApiFriendProfileRequest")
	proto.RegisterType((*ApiFriendProfileResponse)(nil), "site.ApiFriendProfileResponse")
}

func init() {
	proto.RegisterFile("site/api_friend_profile.proto", fileDescriptor_api_friend_profile_3715cad4bb7bc1be)
}

var fileDescriptor_api_friend_profile_3715cad4bb7bc1be = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x4f, 0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x89, 0x2f, 0x28, 0xca, 0x4f,
	0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x4b, 0xf1, 0x27,
	0xe7, 0x17, 0xa5, 0xea, 0x97, 0x16, 0xa7, 0x16, 0x41, 0x84, 0x95, 0x0c, 0xb9, 0xc4, 0x1d, 0x0b,
	0x32, 0xdd, 0xc0, 0x3a, 0x02, 0x20, 0x1a, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc4,
	0xb8, 0xd8, 0x40, 0x0a, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x25,
	0x5f, 0x2e, 0x09, 0x4c, 0x2d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x86, 0x5c, 0xec, 0x50,
	0x6b, 0xc1, 0x9a, 0xb8, 0x8d, 0xc4, 0xf5, 0x40, 0x36, 0xea, 0x41, 0x54, 0x87, 0x16, 0xa7, 0x16,
	0xc1, 0x74, 0xc0, 0xd4, 0x39, 0x45, 0x70, 0x09, 0x27, 0xe7, 0xe7, 0xea, 0x55, 0x25, 0xe6, 0x54,
	0x42, 0xdc, 0xa4, 0x07, 0x72, 0x69, 0x94, 0x7e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72,
	0x7e, 0xae, 0x7e, 0x4a, 0x69, 0x72, 0x76, 0x72, 0x46, 0x62, 0x09, 0x9c, 0xa1, 0x9b, 0x9e, 0x58,
	0x92, 0x5a, 0x9e, 0x58, 0xa9, 0x0f, 0xd6, 0xa0, 0x0f, 0xd2, 0x70, 0x8a, 0x89, 0x3f, 0x2a, 0x31,
	0xa7, 0x32, 0x26, 0x00, 0x24, 0x12, 0x13, 0x9c, 0x59, 0x92, 0x9a, 0xc4, 0x06, 0x96, 0x35, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xf3, 0x3f, 0x40, 0x1a, 0x01, 0x00, 0x00,
}
