// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_password_modifyPassword.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.passport.password.modifyPassword
// error:
//     error.passport.password.maxerror
type ApiPassportPasswordModifyPasswordRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordModifyPasswordRequest) Reset() {
	*m = ApiPassportPasswordModifyPasswordRequest{}
}
func (m *ApiPassportPasswordModifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordModifyPasswordRequest) ProtoMessage()    {}
func (*ApiPassportPasswordModifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_modifyPassword_1c219e116bbdf3fe, []int{0}
}
func (m *ApiPassportPasswordModifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordModifyPasswordRequest.Unmarshal(m, b)
}
func (m *ApiPassportPasswordModifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordModifyPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordModifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordModifyPasswordRequest.Merge(dst, src)
}
func (m *ApiPassportPasswordModifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordModifyPasswordRequest.Size(m)
}
func (m *ApiPassportPasswordModifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordModifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordModifyPasswordRequest proto.InternalMessageInfo

func (m *ApiPassportPasswordModifyPasswordRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *ApiPassportPasswordModifyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ApiPassportPasswordModifyPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ApiPassportPasswordModifyPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordModifyPasswordResponse) Reset() {
	*m = ApiPassportPasswordModifyPasswordResponse{}
}
func (m *ApiPassportPasswordModifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordModifyPasswordResponse) ProtoMessage()    {}
func (*ApiPassportPasswordModifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_modifyPassword_1c219e116bbdf3fe, []int{1}
}
func (m *ApiPassportPasswordModifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordModifyPasswordResponse.Unmarshal(m, b)
}
func (m *ApiPassportPasswordModifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordModifyPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordModifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordModifyPasswordResponse.Merge(dst, src)
}
func (m *ApiPassportPasswordModifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordModifyPasswordResponse.Size(m)
}
func (m *ApiPassportPasswordModifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordModifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordModifyPasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiPassportPasswordModifyPasswordRequest)(nil), "site.ApiPassportPasswordModifyPasswordRequest")
	proto.RegisterType((*ApiPassportPasswordModifyPasswordResponse)(nil), "site.ApiPassportPasswordModifyPasswordResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_password_modifyPassword.proto", fileDescriptor_api_passport_password_modifyPassword_1c219e116bbdf3fe)
}

var fileDescriptor_api_passport_password_modifyPassword_1c219e116bbdf3fe = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2f, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xc8, 0x2f, 0x2a, 0x01, 0x33, 0xca,
	0xf3, 0x8b, 0x52, 0xe2, 0x73, 0xf3, 0x53, 0x32, 0xd3, 0x2a, 0x03, 0xa0, 0x5c, 0xbd, 0x82, 0xa2,
	0xfc, 0x92, 0x7c, 0x21, 0x16, 0x90, 0x06, 0xa5, 0x36, 0x46, 0x2e, 0x0d, 0xc7, 0x82, 0xcc, 0x00,
	0xa8, 0x1e, 0x98, 0x1a, 0x5f, 0x14, 0x1d, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32,
	0x5c, 0x9c, 0x39, 0xf9, 0xe9, 0x99, 0x79, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x08, 0x01, 0x21, 0x29, 0x2e, 0x0e, 0x98, 0x8d, 0x12, 0x4c, 0x60, 0x49, 0x38, 0x5f,
	0x48, 0x81, 0x8b, 0x3b, 0x2f, 0xb5, 0x1c, 0x66, 0x9e, 0x04, 0x33, 0x58, 0x1a, 0x59, 0x48, 0x49,
	0x9b, 0x4b, 0x93, 0x08, 0x77, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x3a, 0x45, 0x70, 0x09, 0x27,
	0xe7, 0xe7, 0xea, 0x55, 0x25, 0xe6, 0x54, 0x42, 0x7c, 0xa3, 0x07, 0xf2, 0x4c, 0x94, 0x7e, 0x7a,
	0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x4a, 0x69, 0x72, 0x76, 0x72, 0x46,
	0x62, 0x09, 0x9c, 0xa1, 0x9b, 0x9e, 0x58, 0x92, 0x5a, 0x9e, 0x58, 0xa9, 0x0f, 0xd6, 0x00, 0x0e,
	0xae, 0x53, 0x4c, 0xfc, 0x51, 0x89, 0x39, 0x95, 0x31, 0x01, 0x20, 0x91, 0x98, 0xe0, 0xcc, 0x92,
	0xd4, 0x24, 0x36, 0xb0, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x7a, 0x0f, 0x5e, 0x4f,
	0x01, 0x00, 0x00,
}
