// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_user_profile.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/duckchat/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.user.profile
//
type ApiUserProfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiUserProfileRequest) Reset()         { *m = ApiUserProfileRequest{} }
func (m *ApiUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ApiUserProfileRequest) ProtoMessage()    {}
func (*ApiUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_user_profile_01ebb6a2201046e0, []int{0}
}
func (m *ApiUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserProfileRequest.Unmarshal(m, b)
}
func (m *ApiUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserProfileRequest.Marshal(b, m, deterministic)
}
func (dst *ApiUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserProfileRequest.Merge(dst, src)
}
func (m *ApiUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ApiUserProfileRequest.Size(m)
}
func (m *ApiUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserProfileRequest proto.InternalMessageInfo

type ApiUserProfileResponse struct {
	Profile              *core.AllUserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApiUserProfileResponse) Reset()         { *m = ApiUserProfileResponse{} }
func (m *ApiUserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ApiUserProfileResponse) ProtoMessage()    {}
func (*ApiUserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_user_profile_01ebb6a2201046e0, []int{1}
}
func (m *ApiUserProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserProfileResponse.Unmarshal(m, b)
}
func (m *ApiUserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserProfileResponse.Marshal(b, m, deterministic)
}
func (dst *ApiUserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserProfileResponse.Merge(dst, src)
}
func (m *ApiUserProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ApiUserProfileResponse.Size(m)
}
func (m *ApiUserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserProfileResponse proto.InternalMessageInfo

func (m *ApiUserProfileResponse) GetProfile() *core.AllUserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiUserProfileRequest)(nil), "site.ApiUserProfileRequest")
	proto.RegisterType((*ApiUserProfileResponse)(nil), "site.ApiUserProfileResponse")
}

func init() {
	proto.RegisterFile("site/api_user_profile.proto", fileDescriptor_api_user_profile_01ebb6a2201046e0)
}

var fileDescriptor_api_user_profile_01ebb6a2201046e0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0x2f, 0x28, 0xca, 0x4f, 0xcb, 0xcc,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x4a, 0xf1, 0x27, 0xe7, 0x17,
	0xa5, 0xea, 0x83, 0xa4, 0x21, 0xc2, 0x4a, 0xe2, 0x5c, 0xa2, 0x8e, 0x05, 0x99, 0xa1, 0xc5, 0xa9,
	0x45, 0x01, 0x10, 0xe5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0x1e, 0x5c, 0x62, 0xe8,
	0x12, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x7a, 0x5c, 0xec, 0x50, 0xa3, 0x25, 0x18, 0x15,
	0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x40, 0xa6, 0xea, 0x39, 0xe6, 0xe4, 0x20, 0x2b, 0x87, 0x29,
	0x72, 0x8a, 0xe0, 0x12, 0x4e, 0xce, 0xcf, 0xd5, 0xab, 0x4a, 0xcc, 0xa9, 0x84, 0x58, 0xaa, 0x07,
	0x72, 0x4a, 0x94, 0x7e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x4a,
	0x69, 0x72, 0x76, 0x72, 0x46, 0x62, 0x09, 0x9c, 0xa1, 0x9b, 0x9e, 0x58, 0x92, 0x5a, 0x9e, 0x58,
	0xa9, 0x0f, 0xd6, 0xa0, 0x0f, 0xd2, 0x70, 0x8a, 0x89, 0x3f, 0x2a, 0x31, 0xa7, 0x32, 0x26, 0x00,
	0x24, 0x12, 0x13, 0x9c, 0x59, 0x92, 0x9a, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0x8e, 0xdd, 0xfd, 0xf9, 0x00, 0x00, 0x00,
}
