// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_ldap_login.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.passport.ldap.login
// error:
//
//
type ApiPassportLdapLoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportLdapLoginRequest) Reset()         { *m = ApiPassportLdapLoginRequest{} }
func (m *ApiPassportLdapLoginRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportLdapLoginRequest) ProtoMessage()    {}
func (*ApiPassportLdapLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_ldap_login_0d43238c675b9b37, []int{0}
}
func (m *ApiPassportLdapLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportLdapLoginRequest.Unmarshal(m, b)
}
func (m *ApiPassportLdapLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportLdapLoginRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportLdapLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportLdapLoginRequest.Merge(dst, src)
}
func (m *ApiPassportLdapLoginRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportLdapLoginRequest.Size(m)
}
func (m *ApiPassportLdapLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportLdapLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportLdapLoginRequest proto.InternalMessageInfo

func (m *ApiPassportLdapLoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ApiPassportLdapLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ApiPassportLdapLoginResponse struct {
	PreSessionId         string   `protobuf:"bytes,1,opt,name=preSessionId,proto3" json:"preSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportLdapLoginResponse) Reset()         { *m = ApiPassportLdapLoginResponse{} }
func (m *ApiPassportLdapLoginResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportLdapLoginResponse) ProtoMessage()    {}
func (*ApiPassportLdapLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_ldap_login_0d43238c675b9b37, []int{1}
}
func (m *ApiPassportLdapLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportLdapLoginResponse.Unmarshal(m, b)
}
func (m *ApiPassportLdapLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportLdapLoginResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportLdapLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportLdapLoginResponse.Merge(dst, src)
}
func (m *ApiPassportLdapLoginResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportLdapLoginResponse.Size(m)
}
func (m *ApiPassportLdapLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportLdapLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportLdapLoginResponse proto.InternalMessageInfo

func (m *ApiPassportLdapLoginResponse) GetPreSessionId() string {
	if m != nil {
		return m.PreSessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiPassportLdapLoginRequest)(nil), "site.ApiPassportLdapLoginRequest")
	proto.RegisterType((*ApiPassportLdapLoginResponse)(nil), "site.ApiPassportLdapLoginResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_ldap_login.proto", fileDescriptor_api_passport_ldap_login_0d43238c675b9b37)
}

var fileDescriptor_api_passport_ldap_login_0d43238c675b9b37 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x69, 0x11, 0x3f, 0x16, 0x41, 0x88, 0x97, 0xa0, 0x1e, 0x24, 0x27, 0x2f, 0x66, 0x0f,
	0x3e, 0x81, 0xbd, 0x09, 0x3d, 0x94, 0xe6, 0x22, 0xa5, 0x10, 0xa6, 0xbb, 0x43, 0xba, 0x98, 0x66,
	0xc6, 0xcc, 0x2c, 0x25, 0x3e, 0xa2, 0x4f, 0x25, 0x1b, 0x6b, 0x41, 0xe8, 0x6d, 0xe6, 0xff, 0xf1,
	0xe3, 0x6f, 0x0a, 0x09, 0x8a, 0x16, 0x38, 0xd4, 0x0c, 0x22, 0x4c, 0xbd, 0xd6, 0xad, 0x07, 0xae,
	0x5b, 0x6a, 0x42, 0x57, 0x72, 0x4f, 0x4a, 0xd9, 0x59, 0xca, 0x14, 0x95, 0xb9, 0x7f, 0xe5, 0xb0,
	0x38, 0xa4, 0xe6, 0x1e, 0x78, 0x9e, 0x32, 0x4b, 0xfc, 0x8c, 0x28, 0x9a, 0xe5, 0xe6, 0x02, 0x9c,
	0xa3, 0xd8, 0x69, 0x3e, 0x79, 0x9c, 0x3c, 0x5d, 0x2d, 0xff, 0xde, 0xec, 0xce, 0x5c, 0x26, 0xf6,
	0x9e, 0x7a, 0x9f, 0x4f, 0x47, 0xeb, 0xf8, 0x17, 0x33, 0xf3, 0x70, 0x1a, 0x2a, 0x4c, 0x9d, 0x60,
	0x56, 0x98, 0x6b, 0xee, 0xb1, 0x42, 0x91, 0x40, 0xdd, 0x9b, 0x3f, 0xa0, 0xff, 0x69, 0xb3, 0x77,
	0x73, 0xeb, 0x68, 0x57, 0x7e, 0x41, 0x3b, 0xfc, 0x0e, 0x2e, 0xd3, 0xde, 0x95, 0x6d, 0x82, 0x6e,
	0xe3, 0xa6, 0x74, 0xb4, 0xb3, 0x3e, 0xba, 0x0f, 0xb7, 0x05, 0x3d, 0x1e, 0xcf, 0x0d, 0x28, 0xee,
	0x61, 0xb0, 0x63, 0xc1, 0xa6, 0xc2, 0xf7, 0xf4, 0x66, 0x05, 0xed, 0xb0, 0x5e, 0x24, 0x65, 0x5d,
	0x05, 0xc5, 0xcd, 0xf9, 0xe8, 0xbe, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x39, 0xf1, 0x1c, 0xd2,
	0x25, 0x01, 0x00, 0x00,
}
