// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_friend_apply.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.friend.apply
//
type ApiFriendApplyRequest struct {
	ToUserId             string   `protobuf:"bytes,1,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	Greetings            string   `protobuf:"bytes,2,opt,name=greetings,proto3" json:"greetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFriendApplyRequest) Reset()         { *m = ApiFriendApplyRequest{} }
func (m *ApiFriendApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFriendApplyRequest) ProtoMessage()    {}
func (*ApiFriendApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_apply_781a0ec282e8c844, []int{0}
}
func (m *ApiFriendApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendApplyRequest.Unmarshal(m, b)
}
func (m *ApiFriendApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendApplyRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFriendApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendApplyRequest.Merge(dst, src)
}
func (m *ApiFriendApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFriendApplyRequest.Size(m)
}
func (m *ApiFriendApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendApplyRequest proto.InternalMessageInfo

func (m *ApiFriendApplyRequest) GetToUserId() string {
	if m != nil {
		return m.ToUserId
	}
	return ""
}

func (m *ApiFriendApplyRequest) GetGreetings() string {
	if m != nil {
		return m.Greetings
	}
	return ""
}

type ApiFriendApplyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFriendApplyResponse) Reset()         { *m = ApiFriendApplyResponse{} }
func (m *ApiFriendApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFriendApplyResponse) ProtoMessage()    {}
func (*ApiFriendApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_apply_781a0ec282e8c844, []int{1}
}
func (m *ApiFriendApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendApplyResponse.Unmarshal(m, b)
}
func (m *ApiFriendApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendApplyResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFriendApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendApplyResponse.Merge(dst, src)
}
func (m *ApiFriendApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFriendApplyResponse.Size(m)
}
func (m *ApiFriendApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendApplyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiFriendApplyRequest)(nil), "site.ApiFriendApplyRequest")
	proto.RegisterType((*ApiFriendApplyResponse)(nil), "site.ApiFriendApplyResponse")
}

func init() {
	proto.RegisterFile("site/api_friend_apply.proto", fileDescriptor_api_friend_apply_781a0ec282e8c844)
}

var fileDescriptor_api_friend_apply_781a0ec282e8c844 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x4f, 0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x89, 0x4f, 0x2c, 0x28, 0xc8,
	0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x2a, 0x05, 0x72, 0x89, 0x3a,
	0x16, 0x64, 0xba, 0x81, 0xa5, 0x1d, 0x41, 0xb2, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x52, 0x5c, 0x1c, 0x25, 0xf9, 0xa1, 0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x70, 0xbe, 0x90, 0x0c, 0x17, 0x67, 0x7a, 0x51, 0x6a, 0x6a, 0x49, 0x66, 0x5e, 0x7a,
	0xb1, 0x04, 0x13, 0x58, 0x12, 0x21, 0xa0, 0x24, 0xc1, 0x25, 0x86, 0x6e, 0x64, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x53, 0x04, 0x97, 0x70, 0x72, 0x7e, 0xae, 0x5e, 0x55, 0x22, 0xcc, 0x11, 0x7a,
	0x20, 0x37, 0x44, 0xe9, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7,
	0x94, 0x26, 0x67, 0x27, 0x67, 0x24, 0x96, 0xc0, 0x19, 0xba, 0xe9, 0x89, 0x25, 0xa9, 0xe5, 0x89,
	0x95, 0xfa, 0x60, 0x0d, 0xfa, 0x20, 0x0d, 0xa7, 0x98, 0xf8, 0xa3, 0x12, 0x73, 0x2a, 0x63, 0x02,
	0x40, 0x22, 0x31, 0xc1, 0x99, 0x25, 0xa9, 0x49, 0x6c, 0x60, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x00, 0xa1, 0x81, 0xef, 0xf2, 0x00, 0x00, 0x00,
}
