// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_site_config.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.site.config
//
//
type ApiSiteConfigRequest struct {
	Random               string   `protobuf:"bytes,1,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiSiteConfigRequest) Reset()         { *m = ApiSiteConfigRequest{} }
func (m *ApiSiteConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ApiSiteConfigRequest) ProtoMessage()    {}
func (*ApiSiteConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_site_config_17f9e236edee149c, []int{0}
}
func (m *ApiSiteConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSiteConfigRequest.Unmarshal(m, b)
}
func (m *ApiSiteConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSiteConfigRequest.Marshal(b, m, deterministic)
}
func (dst *ApiSiteConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSiteConfigRequest.Merge(dst, src)
}
func (m *ApiSiteConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ApiSiteConfigRequest.Size(m)
}
func (m *ApiSiteConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSiteConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSiteConfigRequest proto.InternalMessageInfo

func (m *ApiSiteConfigRequest) GetRandom() string {
	if m != nil {
		return m.Random
	}
	return ""
}

type ApiSiteConfigResponse struct {
	Config *core.PublicSiteConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// randomSignBase64 = rsa(site.privk, request.random)
	RandomSignBase64     string              `protobuf:"bytes,2,opt,name=randomSignBase64,proto3" json:"randomSignBase64,omitempty"`
	IsSessionValid       bool                `protobuf:"varint,3,opt,name=isSessionValid,proto3" json:"isSessionValid,omitempty"`
	LoginPluginProfile   *core.PluginProfile `protobuf:"bytes,4,opt,name=loginPluginProfile,proto3" json:"loginPluginProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ApiSiteConfigResponse) Reset()         { *m = ApiSiteConfigResponse{} }
func (m *ApiSiteConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ApiSiteConfigResponse) ProtoMessage()    {}
func (*ApiSiteConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_site_config_17f9e236edee149c, []int{1}
}
func (m *ApiSiteConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSiteConfigResponse.Unmarshal(m, b)
}
func (m *ApiSiteConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSiteConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ApiSiteConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSiteConfigResponse.Merge(dst, src)
}
func (m *ApiSiteConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ApiSiteConfigResponse.Size(m)
}
func (m *ApiSiteConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSiteConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSiteConfigResponse proto.InternalMessageInfo

func (m *ApiSiteConfigResponse) GetConfig() *core.PublicSiteConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ApiSiteConfigResponse) GetRandomSignBase64() string {
	if m != nil {
		return m.RandomSignBase64
	}
	return ""
}

func (m *ApiSiteConfigResponse) GetIsSessionValid() bool {
	if m != nil {
		return m.IsSessionValid
	}
	return false
}

func (m *ApiSiteConfigResponse) GetLoginPluginProfile() *core.PluginProfile {
	if m != nil {
		return m.LoginPluginProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiSiteConfigRequest)(nil), "site.ApiSiteConfigRequest")
	proto.RegisterType((*ApiSiteConfigResponse)(nil), "site.ApiSiteConfigResponse")
}

func init() {
	proto.RegisterFile("site/api_site_config.proto", fileDescriptor_api_site_config_17f9e236edee149c)
}

var fileDescriptor_api_site_config_17f9e236edee149c = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xe9, 0xfe, 0x63, 0xfc, 0x8d, 0xe0, 0x34, 0xd3, 0x51, 0x7a, 0x35, 0x76, 0x21, 0x43,
	0x30, 0x05, 0x15, 0xef, 0xdd, 0x5e, 0xa0, 0xb4, 0x20, 0x32, 0x06, 0x23, 0x4d, 0xb3, 0xec, 0x60,
	0x9a, 0xd4, 0x26, 0x45, 0xea, 0x23, 0xfa, 0x14, 0x3e, 0x8a, 0x24, 0x2d, 0x32, 0xa6, 0x77, 0x27,
	0xbf, 0x73, 0xbe, 0x73, 0xbe, 0x7c, 0x28, 0x32, 0x60, 0x79, 0x4c, 0x2b, 0xd8, 0xba, 0x62, 0xcb,
	0xb4, 0xda, 0x81, 0x20, 0x55, 0xad, 0xad, 0xc6, 0x43, 0x87, 0xa2, 0x31, 0xd3, 0x35, 0x8f, 0x5d,
	0xd9, 0xe1, 0xe8, 0xc2, 0x83, 0x4a, 0x36, 0x02, 0x54, 0x87, 0xe6, 0x04, 0x5d, 0x3e, 0x55, 0x90,
	0x81, 0xe5, 0x2b, 0xbf, 0x20, 0xe5, 0x6f, 0x0d, 0x37, 0x16, 0x4f, 0xd1, 0xa8, 0xa6, 0xaa, 0xd0,
	0x65, 0x18, 0xcc, 0x82, 0xc5, 0x49, 0xda, 0xbf, 0xe6, 0x5f, 0x01, 0xba, 0x3a, 0x12, 0x98, 0x4a,
	0x2b, 0xc3, 0x31, 0x41, 0xa3, 0xce, 0x83, 0x57, 0x9c, 0xde, 0x4d, 0x89, 0xbb, 0x46, 0x92, 0x26,
	0x97, 0xc0, 0x0e, 0xe6, 0xfb, 0x29, 0x7c, 0x83, 0xce, 0xbb, 0x9d, 0x19, 0x08, 0xb5, 0xa4, 0x86,
	0x3f, 0x3e, 0x84, 0x03, 0x7f, 0xeb, 0x17, 0xc7, 0xd7, 0xe8, 0x0c, 0x4c, 0xc6, 0x8d, 0x01, 0xad,
	0x9e, 0xa9, 0x84, 0x22, 0xfc, 0x37, 0x0b, 0x16, 0xff, 0xd3, 0x23, 0x8a, 0x57, 0x08, 0x4b, 0x2d,
	0x40, 0x25, 0xfe, 0x8b, 0x49, 0xad, 0x77, 0x20, 0x79, 0x38, 0xf4, 0x7e, 0x26, 0xbd, 0x9f, 0xc3,
	0x56, 0xfa, 0xc7, 0xf8, 0xf2, 0x05, 0x4d, 0x98, 0x2e, 0xc9, 0x07, 0x95, 0x6d, 0x17, 0x12, 0x71,
	0x11, 0xae, 0x63, 0x01, 0x76, 0xdf, 0xe4, 0x84, 0xe9, 0x32, 0x2e, 0x1a, 0xf6, 0xca, 0xf6, 0xd4,
	0xfe, 0x14, 0xb7, 0x82, 0x5a, 0xfe, 0x4e, 0xdb, 0xd8, 0x0b, 0x7c, 0xe6, 0x9f, 0x83, 0xf1, 0x9a,
	0xca, 0x76, 0x93, 0x38, 0xb2, 0x71, 0x01, 0xe4, 0x23, 0xdf, 0xbd, 0xff, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x08, 0xb8, 0x9c, 0xbb, 0x01, 0x00, 0x00,
}
