// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_friend_applyList.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.friend.applyList
//
type ApiFriendApplyListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFriendApplyListRequest) Reset()         { *m = ApiFriendApplyListRequest{} }
func (m *ApiFriendApplyListRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFriendApplyListRequest) ProtoMessage()    {}
func (*ApiFriendApplyListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_applyList_fc46707ad0fe6d76, []int{0}
}
func (m *ApiFriendApplyListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendApplyListRequest.Unmarshal(m, b)
}
func (m *ApiFriendApplyListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendApplyListRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFriendApplyListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendApplyListRequest.Merge(dst, src)
}
func (m *ApiFriendApplyListRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFriendApplyListRequest.Size(m)
}
func (m *ApiFriendApplyListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendApplyListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendApplyListRequest proto.InternalMessageInfo

func (m *ApiFriendApplyListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ApiFriendApplyListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ApiFriendApplyListResponse struct {
	List                 []*core.ApplyUserProfile `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount           int32                    `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ApiFriendApplyListResponse) Reset()         { *m = ApiFriendApplyListResponse{} }
func (m *ApiFriendApplyListResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFriendApplyListResponse) ProtoMessage()    {}
func (*ApiFriendApplyListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_applyList_fc46707ad0fe6d76, []int{1}
}
func (m *ApiFriendApplyListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendApplyListResponse.Unmarshal(m, b)
}
func (m *ApiFriendApplyListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendApplyListResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFriendApplyListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendApplyListResponse.Merge(dst, src)
}
func (m *ApiFriendApplyListResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFriendApplyListResponse.Size(m)
}
func (m *ApiFriendApplyListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendApplyListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendApplyListResponse proto.InternalMessageInfo

func (m *ApiFriendApplyListResponse) GetList() []*core.ApplyUserProfile {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ApiFriendApplyListResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ApiFriendApplyListRequest)(nil), "site.ApiFriendApplyListRequest")
	proto.RegisterType((*ApiFriendApplyListResponse)(nil), "site.ApiFriendApplyListResponse")
}

func init() {
	proto.RegisterFile("site/api_friend_applyList.proto", fileDescriptor_api_friend_applyList_fc46707ad0fe6d76)
}

var fileDescriptor_api_friend_applyList_fc46707ad0fe6d76 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x69, 0x6d, 0x7b, 0x88, 0x87, 0x42, 0x94, 0x52, 0x7b, 0x50, 0xe9, 0xa9, 0x08, 0x26,
	0xa0, 0x4f, 0x50, 0x05, 0x41, 0xf0, 0x50, 0x56, 0x04, 0x29, 0x85, 0x92, 0xa6, 0xb3, 0xdd, 0x60,
	0xba, 0x13, 0x93, 0x09, 0xb2, 0x3e, 0xa2, 0x4f, 0x25, 0xc9, 0xaa, 0xf4, 0xe0, 0x2d, 0xf3, 0xe5,
	0xff, 0x26, 0xf9, 0xd9, 0x45, 0x30, 0x04, 0x52, 0x39, 0xb3, 0x2e, 0xbd, 0x81, 0x7a, 0xbb, 0x56,
	0xce, 0xd9, 0xe6, 0xc9, 0x04, 0x12, 0xce, 0x23, 0x21, 0xef, 0xa5, 0xc0, 0x64, 0xa8, 0xd1, 0x83,
	0x8c, 0x01, 0x7c, 0x8b, 0xa7, 0x8f, 0xec, 0x6c, 0xee, 0xcc, 0x43, 0x76, 0xe6, 0xbf, 0x4a, 0x01,
	0xef, 0x11, 0x02, 0xf1, 0x11, 0x1b, 0x60, 0x59, 0x06, 0xa0, 0x71, 0xe7, 0xb2, 0x33, 0xeb, 0x17,
	0x3f, 0x13, 0x3f, 0x65, 0x7d, 0x8d, 0xb1, 0xa6, 0x71, 0x37, 0xe3, 0x76, 0x98, 0x56, 0x6c, 0xf2,
	0xdf, 0xaa, 0xe0, 0xb0, 0x0e, 0xc0, 0xaf, 0x58, 0xcf, 0x9a, 0x90, 0x36, 0x1d, 0xcd, 0x8e, 0x6f,
	0x46, 0x22, 0x7d, 0x44, 0xe4, 0xd8, 0x4b, 0x00, 0xbf, 0xf0, 0x58, 0x1a, 0x0b, 0x45, 0xce, 0xf0,
	0x73, 0xc6, 0x08, 0x49, 0xd9, 0xfb, 0x83, 0x47, 0x0e, 0xc8, 0xdd, 0x2b, 0x3b, 0xd1, 0xb8, 0x17,
	0x9f, 0xca, 0x36, 0x6d, 0x0d, 0x91, 0xca, 0x2d, 0xe5, 0xce, 0x50, 0x15, 0x37, 0x42, 0xe3, 0x5e,
	0x6e, 0xa3, 0x7e, 0xd3, 0x95, 0xa2, 0xbf, 0xc3, 0xf5, 0x4e, 0x11, 0x7c, 0xa8, 0x46, 0x66, 0x41,
	0x26, 0xe1, 0xab, 0x3b, 0x5c, 0x2a, 0xdb, 0xac, 0x16, 0x89, 0xac, 0x9e, 0x0d, 0xc1, 0x66, 0x90,
	0x6f, 0x6f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xd2, 0x2d, 0x0a, 0x4f, 0x01, 0x00, 0x00,
}
