// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_file_upload.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.file.upload
// error:
// .    error.file.large     the file is larger than the limit the server allowed.
// .    error.file.wrong     the file doesnot match the filetype in request.
type ApiFileUploadRequest struct {
	File                 []byte        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	FileType             core.FileType `protobuf:"varint,2,opt,name=fileType,proto3,enum=core.FileType" json:"fileType,omitempty"`
	IsMessageAttachment  bool          `protobuf:"varint,3,opt,name=isMessageAttachment,proto3" json:"isMessageAttachment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApiFileUploadRequest) Reset()         { *m = ApiFileUploadRequest{} }
func (m *ApiFileUploadRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFileUploadRequest) ProtoMessage()    {}
func (*ApiFileUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_file_upload_78cc0a578778fcf5, []int{0}
}
func (m *ApiFileUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFileUploadRequest.Unmarshal(m, b)
}
func (m *ApiFileUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFileUploadRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFileUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFileUploadRequest.Merge(dst, src)
}
func (m *ApiFileUploadRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFileUploadRequest.Size(m)
}
func (m *ApiFileUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFileUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFileUploadRequest proto.InternalMessageInfo

func (m *ApiFileUploadRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *ApiFileUploadRequest) GetFileType() core.FileType {
	if m != nil {
		return m.FileType
	}
	return core.FileType_FileInvalid
}

func (m *ApiFileUploadRequest) GetIsMessageAttachment() bool {
	if m != nil {
		return m.IsMessageAttachment
	}
	return false
}

type ApiFileUploadResponse struct {
	FileId               string   `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFileUploadResponse) Reset()         { *m = ApiFileUploadResponse{} }
func (m *ApiFileUploadResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFileUploadResponse) ProtoMessage()    {}
func (*ApiFileUploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_file_upload_78cc0a578778fcf5, []int{1}
}
func (m *ApiFileUploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFileUploadResponse.Unmarshal(m, b)
}
func (m *ApiFileUploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFileUploadResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFileUploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFileUploadResponse.Merge(dst, src)
}
func (m *ApiFileUploadResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFileUploadResponse.Size(m)
}
func (m *ApiFileUploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFileUploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFileUploadResponse proto.InternalMessageInfo

func (m *ApiFileUploadResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiFileUploadRequest)(nil), "site.ApiFileUploadRequest")
	proto.RegisterType((*ApiFileUploadResponse)(nil), "site.ApiFileUploadResponse")
}

func init() {
	proto.RegisterFile("site/api_file_upload.proto", fileDescriptor_api_file_upload_78cc0a578778fcf5)
}

var fileDescriptor_api_file_upload_78cc0a578778fcf5 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xe9, 0x1c, 0x63, 0x06, 0xa9, 0x90, 0xa9, 0x94, 0x5d, 0x95, 0x5d, 0x15, 0xc1, 0x44,
	0xf4, 0x09, 0xe6, 0xc5, 0xc0, 0x0b, 0x41, 0xa2, 0x82, 0x8c, 0xc1, 0xc8, 0xd2, 0x63, 0x1b, 0x4c,
	0x9b, 0xb8, 0x9c, 0x22, 0xf5, 0x09, 0x7c, 0x36, 0x9f, 0x4a, 0x92, 0x8d, 0x5d, 0x88, 0x57, 0x39,
	0xf9, 0xbf, 0x73, 0x7e, 0xfe, 0x9f, 0x4c, 0xbd, 0x46, 0xe0, 0xd2, 0xe9, 0xf5, 0x9b, 0x36, 0xb0,
	0xee, 0x9c, 0xb1, 0xb2, 0x64, 0x6e, 0x6b, 0xd1, 0xd2, 0x61, 0x60, 0xd3, 0x54, 0xd9, 0x2d, 0xf0,
	0x16, 0x70, 0xa7, 0xce, 0xbe, 0x13, 0x72, 0x36, 0x77, 0x7a, 0xa1, 0x0d, 0xbc, 0xc4, 0x6d, 0x01,
	0x1f, 0x1d, 0x78, 0xa4, 0x94, 0x0c, 0x83, 0x47, 0x96, 0xe4, 0x49, 0x71, 0x22, 0xe2, 0x4c, 0x2f,
	0xc9, 0x38, 0xbc, 0xcf, 0xbd, 0x83, 0x6c, 0x90, 0x27, 0x45, 0x7a, 0x93, 0xb2, 0xe0, 0xc7, 0x16,
	0x7b, 0x55, 0x1c, 0x38, 0xbd, 0x26, 0x13, 0xed, 0x1f, 0xc0, 0x7b, 0x59, 0xc1, 0x1c, 0x51, 0xaa,
	0xba, 0x81, 0x16, 0xb3, 0xa3, 0x3c, 0x29, 0xc6, 0xe2, 0x3f, 0x34, 0xe3, 0xe4, 0xfc, 0x4f, 0x12,
	0xef, 0x6c, 0xeb, 0x81, 0x5e, 0x90, 0x51, 0xb0, 0xbd, 0x2f, 0x63, 0x98, 0x63, 0xb1, 0xff, 0xdd,
	0xbd, 0x92, 0x89, 0xb2, 0x0d, 0xfb, 0x92, 0xa6, 0xdf, 0xb5, 0x61, 0xa1, 0xe2, 0x92, 0x57, 0x1a,
	0xeb, 0x6e, 0xc3, 0x94, 0x6d, 0x78, 0xd9, 0xa9, 0x77, 0x55, 0x4b, 0x3c, 0x0c, 0x57, 0x95, 0x44,
	0xf8, 0x94, 0x3d, 0x8f, 0x07, 0x3c, 0x1c, 0xfc, 0x0c, 0x4e, 0x97, 0xd2, 0xf4, 0xab, 0xc7, 0xa0,
	0xac, 0x9e, 0x34, 0xc2, 0x66, 0x14, 0xe9, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xb2,
	0xce, 0x52, 0x50, 0x01, 0x00, 0x00,
}
