// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_group_removeMember.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.group.removeMember
//
type ApiGroupRemoveMemberRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	UserIds              []string `protobuf:"bytes,2,rep,name=userIds,proto3" json:"userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupRemoveMemberRequest) Reset()         { *m = ApiGroupRemoveMemberRequest{} }
func (m *ApiGroupRemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*ApiGroupRemoveMemberRequest) ProtoMessage()    {}
func (*ApiGroupRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_removeMember_7007010f950cb43c, []int{0}
}
func (m *ApiGroupRemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupRemoveMemberRequest.Unmarshal(m, b)
}
func (m *ApiGroupRemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupRemoveMemberRequest.Marshal(b, m, deterministic)
}
func (dst *ApiGroupRemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupRemoveMemberRequest.Merge(dst, src)
}
func (m *ApiGroupRemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_ApiGroupRemoveMemberRequest.Size(m)
}
func (m *ApiGroupRemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupRemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupRemoveMemberRequest proto.InternalMessageInfo

func (m *ApiGroupRemoveMemberRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *ApiGroupRemoveMemberRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type ApiGroupRemoveMemberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupRemoveMemberResponse) Reset()         { *m = ApiGroupRemoveMemberResponse{} }
func (m *ApiGroupRemoveMemberResponse) String() string { return proto.CompactTextString(m) }
func (*ApiGroupRemoveMemberResponse) ProtoMessage()    {}
func (*ApiGroupRemoveMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_removeMember_7007010f950cb43c, []int{1}
}
func (m *ApiGroupRemoveMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupRemoveMemberResponse.Unmarshal(m, b)
}
func (m *ApiGroupRemoveMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupRemoveMemberResponse.Marshal(b, m, deterministic)
}
func (dst *ApiGroupRemoveMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupRemoveMemberResponse.Merge(dst, src)
}
func (m *ApiGroupRemoveMemberResponse) XXX_Size() int {
	return xxx_messageInfo_ApiGroupRemoveMemberResponse.Size(m)
}
func (m *ApiGroupRemoveMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupRemoveMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupRemoveMemberResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiGroupRemoveMemberRequest)(nil), "site.ApiGroupRemoveMemberRequest")
	proto.RegisterType((*ApiGroupRemoveMemberResponse)(nil), "site.ApiGroupRemoveMemberResponse")
}

func init() {
	proto.RegisterFile("site/api_group_removeMember.proto", fileDescriptor_api_group_removeMember_7007010f950cb43c)
}

var fileDescriptor_api_group_removeMember_7007010f950cb43c = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0x88, 0x2f, 0x4a, 0xcd, 0xcd, 0x2f,
	0x4b, 0xf5, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01,
	0x29, 0x51, 0x0a, 0xe4, 0x92, 0x76, 0x2c, 0xc8, 0x74, 0x07, 0x29, 0x0a, 0x42, 0x52, 0x13, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc1, 0xc5, 0x0e, 0x36, 0xc0, 0x33, 0x45, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x05, 0xc9, 0x94, 0x16, 0xa7, 0x16, 0x79, 0xa6, 0x14, 0x4b,
	0x30, 0x29, 0x30, 0x83, 0x64, 0xa0, 0x5c, 0x25, 0x39, 0x2e, 0x19, 0xec, 0x46, 0x16, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x3a, 0x45, 0x70, 0x09, 0x27, 0xe7, 0xe7, 0xea, 0x55, 0x25, 0xe6, 0x54, 0x42,
	0x9c, 0xa2, 0x07, 0x72, 0x49, 0x94, 0x7e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e,
	0xae, 0x7e, 0x4a, 0x69, 0x72, 0x76, 0x72, 0x46, 0x62, 0x09, 0x9c, 0xa1, 0x9b, 0x9e, 0x58, 0x92,
	0x5a, 0x9e, 0x58, 0xa9, 0x0f, 0xd6, 0xa0, 0x0f, 0xd2, 0x70, 0x8a, 0x89, 0x3f, 0x2a, 0x31, 0xa7,
	0x32, 0x26, 0x00, 0x24, 0x12, 0x13, 0x9c, 0x59, 0x92, 0x9a, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0x8e, 0x19, 0x57, 0xfe, 0x00, 0x00, 0x00,
}
