// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_sync_check.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiSyncType int32

const (
	ApiSyncType_ApiSyncInvalid    ApiSyncType = 0
	ApiSyncType_ApiSyncFriendList ApiSyncType = 1
)

var ApiSyncType_name = map[int32]string{
	0: "ApiSyncInvalid",
	1: "ApiSyncFriendList",
}
var ApiSyncType_value = map[string]int32{
	"ApiSyncInvalid":    0,
	"ApiSyncFriendList": 1,
}

func (x ApiSyncType) String() string {
	return proto.EnumName(ApiSyncType_name, int32(x))
}
func (ApiSyncType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_sync_check_55f9f8c8719818b5, []int{0}
}

// *
// action: api.sync.check
type ApiSyncCheckRequest struct {
	Type                 ApiSyncType `protobuf:"varint,1,opt,name=type,proto3,enum=site.ApiSyncType" json:"type,omitempty"`
	LocalVersion         int32       `protobuf:"varint,2,opt,name=localVersion,proto3" json:"localVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ApiSyncCheckRequest) Reset()         { *m = ApiSyncCheckRequest{} }
func (m *ApiSyncCheckRequest) String() string { return proto.CompactTextString(m) }
func (*ApiSyncCheckRequest) ProtoMessage()    {}
func (*ApiSyncCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_sync_check_55f9f8c8719818b5, []int{0}
}
func (m *ApiSyncCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSyncCheckRequest.Unmarshal(m, b)
}
func (m *ApiSyncCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSyncCheckRequest.Marshal(b, m, deterministic)
}
func (dst *ApiSyncCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSyncCheckRequest.Merge(dst, src)
}
func (m *ApiSyncCheckRequest) XXX_Size() int {
	return xxx_messageInfo_ApiSyncCheckRequest.Size(m)
}
func (m *ApiSyncCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSyncCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSyncCheckRequest proto.InternalMessageInfo

func (m *ApiSyncCheckRequest) GetType() ApiSyncType {
	if m != nil {
		return m.Type
	}
	return ApiSyncType_ApiSyncInvalid
}

func (m *ApiSyncCheckRequest) GetLocalVersion() int32 {
	if m != nil {
		return m.LocalVersion
	}
	return 0
}

type ApiSyncCheckResponse struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiSyncCheckResponse) Reset()         { *m = ApiSyncCheckResponse{} }
func (m *ApiSyncCheckResponse) String() string { return proto.CompactTextString(m) }
func (*ApiSyncCheckResponse) ProtoMessage()    {}
func (*ApiSyncCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_sync_check_55f9f8c8719818b5, []int{1}
}
func (m *ApiSyncCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSyncCheckResponse.Unmarshal(m, b)
}
func (m *ApiSyncCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSyncCheckResponse.Marshal(b, m, deterministic)
}
func (dst *ApiSyncCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSyncCheckResponse.Merge(dst, src)
}
func (m *ApiSyncCheckResponse) XXX_Size() int {
	return xxx_messageInfo_ApiSyncCheckResponse.Size(m)
}
func (m *ApiSyncCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSyncCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSyncCheckResponse proto.InternalMessageInfo

func (m *ApiSyncCheckResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*ApiSyncCheckRequest)(nil), "site.ApiSyncCheckRequest")
	proto.RegisterType((*ApiSyncCheckResponse)(nil), "site.ApiSyncCheckResponse")
	proto.RegisterEnum("site.ApiSyncType", ApiSyncType_name, ApiSyncType_value)
}

func init() {
	proto.RegisterFile("site/api_sync_check.proto", fileDescriptor_api_sync_check_55f9f8c8719818b5)
}

var fileDescriptor_api_sync_check_55f9f8c8719818b5 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xbf, 0x8e, 0x7d, 0x0a, 0x47, 0x99, 0x5b, 0xa6, 0x50, 0xef, 0x46, 0x41, 0x18, 0x82,
	0x8d, 0xe8, 0x8d, 0xb7, 0x2a, 0x08, 0x82, 0x17, 0xd2, 0x89, 0xc8, 0x18, 0xcc, 0x2c, 0x3d, 0xac,
	0x61, 0x59, 0x12, 0x9b, 0x74, 0x12, 0x7f, 0xa2, 0xbf, 0x4a, 0x12, 0xab, 0xb8, 0xbb, 0x9c, 0xf7,
	0x39, 0x0f, 0x6f, 0x0e, 0x1c, 0x5b, 0xe1, 0x90, 0x32, 0x23, 0xe6, 0xd6, 0x2b, 0x3e, 0xe7, 0x15,
	0xf2, 0x55, 0x6e, 0x6a, 0xed, 0x34, 0xe9, 0x06, 0x94, 0xbd, 0xc2, 0xf0, 0xda, 0x88, 0x89, 0x57,
	0xfc, 0x36, 0xb0, 0x02, 0xdf, 0x1a, 0xb4, 0x8e, 0x9c, 0x40, 0xd7, 0x79, 0x83, 0x69, 0x32, 0x4a,
	0xc6, 0xbd, 0x8b, 0x41, 0x1e, 0x76, 0xf3, 0x76, 0xf1, 0xc9, 0x1b, 0x2c, 0x22, 0x26, 0x19, 0xec,
	0x4b, 0xcd, 0x99, 0x7c, 0xc6, 0xda, 0x0a, 0xad, 0xd2, 0xce, 0x28, 0x19, 0xff, 0x2f, 0xb6, 0xb2,
	0xec, 0x1c, 0x0e, 0xb7, 0x1b, 0xac, 0xd1, 0xca, 0x22, 0x49, 0x61, 0x77, 0xd3, 0x6a, 0x49, 0xd4,
	0x7e, 0xc6, 0xd3, 0x2b, 0xd8, 0xfb, 0x53, 0x45, 0x08, 0xf4, 0xda, 0xf1, 0x5e, 0x6d, 0x98, 0x14,
	0x65, 0xff, 0x1f, 0x39, 0x82, 0x41, 0x9b, 0xdd, 0xd5, 0x02, 0x55, 0xf9, 0x20, 0xac, 0xeb, 0x27,
	0x37, 0x2f, 0x30, 0xe4, 0x7a, 0x9d, 0x7f, 0x30, 0xe9, 0xbf, 0xaf, 0x8c, 0x1f, 0x9f, 0xd2, 0xa5,
	0x70, 0x55, 0xb3, 0xc8, 0xb9, 0x5e, 0xd3, 0xb2, 0xe1, 0x2b, 0x5e, 0x31, 0xf7, 0xfb, 0x38, 0x5b,
	0x32, 0x87, 0xef, 0xcc, 0xd3, 0x28, 0xd0, 0x20, 0x7c, 0x76, 0x0e, 0xa6, 0x4c, 0xfa, 0xd9, 0x63,
	0x48, 0x66, 0x13, 0xe1, 0x70, 0xb1, 0x13, 0xe9, 0xe5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6,
	0x76, 0xbc, 0x93, 0x51, 0x01, 0x00, 0x00,
}
