// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_user_update.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/duckchat/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiUserUpdateType int32

const (
	ApiUserUpdateType_ApiUserUpdateInvalid  ApiUserUpdateType = 0
	ApiUserUpdateType_ApiUserUpdateAvatar   ApiUserUpdateType = 1
	ApiUserUpdateType_ApiUserUpdateNickname ApiUserUpdateType = 2
)

var ApiUserUpdateType_name = map[int32]string{
	0: "ApiUserUpdateInvalid",
	1: "ApiUserUpdateAvatar",
	2: "ApiUserUpdateNickname",
}
var ApiUserUpdateType_value = map[string]int32{
	"ApiUserUpdateInvalid":  0,
	"ApiUserUpdateAvatar":   1,
	"ApiUserUpdateNickname": 2,
}

func (x ApiUserUpdateType) String() string {
	return proto.EnumName(ApiUserUpdateType_name, int32(x))
}
func (ApiUserUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_user_update_1e25ec6f144f16e8, []int{0}
}

type ApiUserUpdateValue struct {
	Type ApiUserUpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=site.ApiUserUpdateType" json:"type,omitempty"`
	// Types that are valid to be assigned to Fields:
	//	*ApiUserUpdateValue_Avatar
	//	*ApiUserUpdateValue_Nickname
	Fields               isApiUserUpdateValue_Fields `protobuf_oneof:"fields"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ApiUserUpdateValue) Reset()         { *m = ApiUserUpdateValue{} }
func (m *ApiUserUpdateValue) String() string { return proto.CompactTextString(m) }
func (*ApiUserUpdateValue) ProtoMessage()    {}
func (*ApiUserUpdateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_user_update_1e25ec6f144f16e8, []int{0}
}
func (m *ApiUserUpdateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserUpdateValue.Unmarshal(m, b)
}
func (m *ApiUserUpdateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserUpdateValue.Marshal(b, m, deterministic)
}
func (dst *ApiUserUpdateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserUpdateValue.Merge(dst, src)
}
func (m *ApiUserUpdateValue) XXX_Size() int {
	return xxx_messageInfo_ApiUserUpdateValue.Size(m)
}
func (m *ApiUserUpdateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserUpdateValue.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserUpdateValue proto.InternalMessageInfo

type isApiUserUpdateValue_Fields interface {
	isApiUserUpdateValue_Fields()
}

type ApiUserUpdateValue_Avatar struct {
	Avatar string `protobuf:"bytes,2,opt,name=avatar,proto3,oneof"`
}
type ApiUserUpdateValue_Nickname struct {
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3,oneof"`
}

func (*ApiUserUpdateValue_Avatar) isApiUserUpdateValue_Fields()   {}
func (*ApiUserUpdateValue_Nickname) isApiUserUpdateValue_Fields() {}

func (m *ApiUserUpdateValue) GetFields() isApiUserUpdateValue_Fields {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ApiUserUpdateValue) GetType() ApiUserUpdateType {
	if m != nil {
		return m.Type
	}
	return ApiUserUpdateType_ApiUserUpdateInvalid
}

func (m *ApiUserUpdateValue) GetAvatar() string {
	if x, ok := m.GetFields().(*ApiUserUpdateValue_Avatar); ok {
		return x.Avatar
	}
	return ""
}

func (m *ApiUserUpdateValue) GetNickname() string {
	if x, ok := m.GetFields().(*ApiUserUpdateValue_Nickname); ok {
		return x.Nickname
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ApiUserUpdateValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ApiUserUpdateValue_OneofMarshaler, _ApiUserUpdateValue_OneofUnmarshaler, _ApiUserUpdateValue_OneofSizer, []interface{}{
		(*ApiUserUpdateValue_Avatar)(nil),
		(*ApiUserUpdateValue_Nickname)(nil),
	}
}

func _ApiUserUpdateValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ApiUserUpdateValue)
	// fields
	switch x := m.Fields.(type) {
	case *ApiUserUpdateValue_Avatar:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Avatar)
	case *ApiUserUpdateValue_Nickname:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Nickname)
	case nil:
	default:
		return fmt.Errorf("ApiUserUpdateValue.Fields has unexpected type %T", x)
	}
	return nil
}

func _ApiUserUpdateValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ApiUserUpdateValue)
	switch tag {
	case 2: // fields.avatar
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Fields = &ApiUserUpdateValue_Avatar{x}
		return true, err
	case 3: // fields.nickname
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Fields = &ApiUserUpdateValue_Nickname{x}
		return true, err
	default:
		return false, nil
	}
}

func _ApiUserUpdateValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ApiUserUpdateValue)
	// fields
	switch x := m.Fields.(type) {
	case *ApiUserUpdateValue_Avatar:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Avatar)))
		n += len(x.Avatar)
	case *ApiUserUpdateValue_Nickname:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Nickname)))
		n += len(x.Nickname)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// *
//
// action: api.user.update
//
type ApiUserUpdateRequest struct {
	Values               []*ApiUserUpdateValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ApiUserUpdateRequest) Reset()         { *m = ApiUserUpdateRequest{} }
func (m *ApiUserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ApiUserUpdateRequest) ProtoMessage()    {}
func (*ApiUserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_user_update_1e25ec6f144f16e8, []int{1}
}
func (m *ApiUserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserUpdateRequest.Unmarshal(m, b)
}
func (m *ApiUserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *ApiUserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserUpdateRequest.Merge(dst, src)
}
func (m *ApiUserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ApiUserUpdateRequest.Size(m)
}
func (m *ApiUserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserUpdateRequest proto.InternalMessageInfo

func (m *ApiUserUpdateRequest) GetValues() []*ApiUserUpdateValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type ApiUserUpdateResponse struct {
	Profile              *core.AllUserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApiUserUpdateResponse) Reset()         { *m = ApiUserUpdateResponse{} }
func (m *ApiUserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ApiUserUpdateResponse) ProtoMessage()    {}
func (*ApiUserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_user_update_1e25ec6f144f16e8, []int{2}
}
func (m *ApiUserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiUserUpdateResponse.Unmarshal(m, b)
}
func (m *ApiUserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiUserUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *ApiUserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiUserUpdateResponse.Merge(dst, src)
}
func (m *ApiUserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ApiUserUpdateResponse.Size(m)
}
func (m *ApiUserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiUserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiUserUpdateResponse proto.InternalMessageInfo

func (m *ApiUserUpdateResponse) GetProfile() *core.AllUserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiUserUpdateValue)(nil), "site.ApiUserUpdateValue")
	proto.RegisterType((*ApiUserUpdateRequest)(nil), "site.ApiUserUpdateRequest")
	proto.RegisterType((*ApiUserUpdateResponse)(nil), "site.ApiUserUpdateResponse")
	proto.RegisterEnum("site.ApiUserUpdateType", ApiUserUpdateType_name, ApiUserUpdateType_value)
}

func init() {
	proto.RegisterFile("site/api_user_update.proto", fileDescriptor_api_user_update_1e25ec6f144f16e8)
}

var fileDescriptor_api_user_update_1e25ec6f144f16e8 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0x69, 0x21, 0x7d, 0xbc, 0x21, 0x79, 0xf0, 0x06, 0x0c, 0x95, 0xb8, 0x20, 0xac, 0x88,
	0xc6, 0xa9, 0xc1, 0x5f, 0x00, 0x1b, 0x71, 0x63, 0x48, 0x15, 0x63, 0x08, 0x09, 0x19, 0xda, 0x0b,
	0x4c, 0x18, 0xda, 0xb1, 0x33, 0xc5, 0xd4, 0xad, 0xff, 0xce, 0x5f, 0x65, 0x66, 0x5a, 0x49, 0x40,
	0x77, 0xed, 0x3d, 0xdf, 0xb9, 0x39, 0xe7, 0x0e, 0xea, 0x48, 0xa6, 0xc0, 0xa3, 0x82, 0x2d, 0x52,
	0x09, 0xc9, 0x22, 0x15, 0x21, 0x55, 0x40, 0x44, 0x12, 0xab, 0x18, 0x57, 0xb4, 0xd6, 0xa9, 0x07,
	0x71, 0x02, 0x9e, 0x56, 0xf3, 0x71, 0xef, 0xc3, 0x42, 0x78, 0x28, 0xd8, 0x54, 0x42, 0x32, 0x35,
	0xf8, 0x33, 0xe5, 0x29, 0xe0, 0x2b, 0x54, 0x51, 0x99, 0x00, 0xd7, 0xea, 0x5a, 0xfd, 0x7f, 0x83,
	0x36, 0xd1, 0x66, 0x72, 0xc4, 0x3d, 0x65, 0x02, 0x7c, 0x03, 0x61, 0x17, 0x39, 0x74, 0x4f, 0x15,
	0x4d, 0x5c, 0xbb, 0x6b, 0xf5, 0xff, 0x8e, 0x4b, 0x7e, 0xf1, 0x8f, 0x2f, 0x50, 0x35, 0x62, 0xc1,
	0x36, 0xa2, 0x3b, 0x70, 0xcb, 0x85, 0x76, 0x98, 0x8c, 0xaa, 0xc8, 0x59, 0x31, 0xe0, 0xa1, 0xec,
	0x8d, 0x51, 0xeb, 0x68, 0xb9, 0x0f, 0xaf, 0x29, 0x48, 0x85, 0x6f, 0x90, 0xb3, 0xd7, 0x79, 0xa4,
	0x6b, 0x77, 0xcb, 0xfd, 0xda, 0xc0, 0xfd, 0x25, 0x88, 0x09, 0xec, 0x17, 0x5c, 0xef, 0x0e, 0x9d,
	0x9d, 0x6c, 0x92, 0x22, 0x8e, 0x24, 0x60, 0x82, 0xfe, 0x88, 0x24, 0x5e, 0x31, 0x9e, 0x97, 0xaa,
	0x0d, 0x5a, 0x44, 0xdf, 0x82, 0x0c, 0x39, 0xd7, 0xf4, 0x24, 0xd7, 0xfc, 0x6f, 0xe8, 0x92, 0xa2,
	0xff, 0x3f, 0xfa, 0x62, 0xf7, 0x24, 0xe7, 0x7d, 0xb4, 0xa7, 0x9c, 0x85, 0x8d, 0x12, 0x6e, 0xa3,
	0xe6, 0x91, 0x32, 0x34, 0x07, 0x68, 0x58, 0xf8, 0xfc, 0x24, 0xd0, 0x43, 0xd1, 0xbe, 0x61, 0x8f,
	0x5e, 0x50, 0x33, 0x88, 0x77, 0xe4, 0x9d, 0xf2, 0x2c, 0x7f, 0x0d, 0xd3, 0x6e, 0xe6, 0xad, 0x99,
	0xda, 0xa4, 0x4b, 0x12, 0xc4, 0x3b, 0x2f, 0x4c, 0x83, 0x6d, 0xb0, 0xa1, 0xea, 0xf0, 0x71, 0xbd,
	0xa6, 0x0a, 0xde, 0x68, 0xe6, 0x19, 0x83, 0xa7, 0x0d, 0x9f, 0x76, 0x7d, 0x46, 0x79, 0x36, 0x9f,
	0xe8, 0xc9, 0xfc, 0x91, 0x29, 0x58, 0x3a, 0x46, 0xbd, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xb3,
	0x13, 0x8f, 0x08, 0x11, 0x02, 0x00, 0x00,
}
