// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_password_login.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.passport.password.login
// error:
//     error.passport.password.maxerror
//
type ApiPassportPasswordLoginRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SitePubkPem          string   `protobuf:"bytes,3,opt,name=sitePubkPem,proto3" json:"sitePubkPem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordLoginRequest) Reset()         { *m = ApiPassportPasswordLoginRequest{} }
func (m *ApiPassportPasswordLoginRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordLoginRequest) ProtoMessage()    {}
func (*ApiPassportPasswordLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_login_457733328968de12, []int{0}
}
func (m *ApiPassportPasswordLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordLoginRequest.Unmarshal(m, b)
}
func (m *ApiPassportPasswordLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordLoginRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordLoginRequest.Merge(dst, src)
}
func (m *ApiPassportPasswordLoginRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordLoginRequest.Size(m)
}
func (m *ApiPassportPasswordLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordLoginRequest proto.InternalMessageInfo

func (m *ApiPassportPasswordLoginRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *ApiPassportPasswordLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ApiPassportPasswordLoginRequest) GetSitePubkPem() string {
	if m != nil {
		return m.SitePubkPem
	}
	return ""
}

type ApiPassportPasswordLoginResponse struct {
	PreSessionId         string   `protobuf:"bytes,1,opt,name=preSessionId,proto3" json:"preSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordLoginResponse) Reset()         { *m = ApiPassportPasswordLoginResponse{} }
func (m *ApiPassportPasswordLoginResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordLoginResponse) ProtoMessage()    {}
func (*ApiPassportPasswordLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_login_457733328968de12, []int{1}
}
func (m *ApiPassportPasswordLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordLoginResponse.Unmarshal(m, b)
}
func (m *ApiPassportPasswordLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordLoginResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordLoginResponse.Merge(dst, src)
}
func (m *ApiPassportPasswordLoginResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordLoginResponse.Size(m)
}
func (m *ApiPassportPasswordLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordLoginResponse proto.InternalMessageInfo

func (m *ApiPassportPasswordLoginResponse) GetPreSessionId() string {
	if m != nil {
		return m.PreSessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiPassportPasswordLoginRequest)(nil), "site.ApiPassportPasswordLoginRequest")
	proto.RegisterType((*ApiPassportPasswordLoginResponse)(nil), "site.ApiPassportPasswordLoginResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_password_login.proto", fileDescriptor_api_passport_password_login_457733328968de12)
}

var fileDescriptor_api_passport_password_login_457733328968de12 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0xce, 0x2c, 0x49,
	0xd5, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xc8, 0x2f, 0x2a, 0x01, 0x33, 0xca,
	0xf3, 0x8b, 0x52, 0xe2, 0x73, 0xf2, 0xd3, 0x33, 0xf3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x58, 0x40, 0xea, 0x94, 0x6a, 0xb9, 0xe4, 0x1d, 0x0b, 0x32, 0x03, 0xa0, 0x2a, 0x03, 0xa0, 0x0a,
	0x7d, 0x40, 0xea, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0xc1, 0xfa,
	0xfc, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x52, 0x5c,
	0x1c, 0x30, 0xe3, 0x25, 0x98, 0xc0, 0x92, 0x70, 0xbe, 0x90, 0x02, 0x17, 0x37, 0xc8, 0x92, 0x80,
	0xd2, 0xa4, 0xec, 0x80, 0xd4, 0x5c, 0x09, 0x66, 0xb0, 0x34, 0xb2, 0x90, 0x92, 0x1b, 0x97, 0x02,
	0x6e, 0xeb, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x94, 0xb8, 0x78, 0x0a, 0x8a, 0x52, 0x83,
	0x53, 0x8b, 0x8b, 0x33, 0xf3, 0xf3, 0x3c, 0x53, 0xa0, 0x4e, 0x40, 0x11, 0x73, 0x8a, 0xe0, 0x12,
	0x4e, 0xce, 0xcf, 0xd5, 0xab, 0x4a, 0xcc, 0xa9, 0x84, 0x78, 0x4f, 0x0f, 0x64, 0x4b, 0x94, 0x7e,
	0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x4a, 0x69, 0x72, 0x76, 0x72,
	0x46, 0x62, 0x09, 0x9c, 0xa1, 0x9b, 0x9e, 0x58, 0x92, 0x5a, 0x9e, 0x58, 0xa9, 0x0f, 0xd6, 0xa0,
	0x0f, 0xd2, 0x70, 0x8a, 0x89, 0x3f, 0x2a, 0x31, 0xa7, 0x32, 0x26, 0x00, 0x24, 0x12, 0x13, 0x9c,
	0x59, 0x92, 0x9a, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x37, 0xf6,
	0x79, 0x57, 0x01, 0x00, 0x00,
}
