// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_group_invitableFriends.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.group.invitableFriends
//
type ApiGroupInvitableFriendsRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiGroupInvitableFriendsRequest) Reset()         { *m = ApiGroupInvitableFriendsRequest{} }
func (m *ApiGroupInvitableFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*ApiGroupInvitableFriendsRequest) ProtoMessage()    {}
func (*ApiGroupInvitableFriendsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_invitableFriends_bd215194d5a0aa95, []int{0}
}
func (m *ApiGroupInvitableFriendsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupInvitableFriendsRequest.Unmarshal(m, b)
}
func (m *ApiGroupInvitableFriendsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupInvitableFriendsRequest.Marshal(b, m, deterministic)
}
func (dst *ApiGroupInvitableFriendsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupInvitableFriendsRequest.Merge(dst, src)
}
func (m *ApiGroupInvitableFriendsRequest) XXX_Size() int {
	return xxx_messageInfo_ApiGroupInvitableFriendsRequest.Size(m)
}
func (m *ApiGroupInvitableFriendsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupInvitableFriendsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupInvitableFriendsRequest proto.InternalMessageInfo

func (m *ApiGroupInvitableFriendsRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *ApiGroupInvitableFriendsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ApiGroupInvitableFriendsRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ApiGroupInvitableFriendsResponse struct {
	List                 []*core.PublicUserProfile `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	ListIsMute           map[string]bool           `protobuf:"bytes,2,rep,name=listIsMute,proto3" json:"listIsMute,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	TotalCount           int32                     `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ApiGroupInvitableFriendsResponse) Reset()         { *m = ApiGroupInvitableFriendsResponse{} }
func (m *ApiGroupInvitableFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*ApiGroupInvitableFriendsResponse) ProtoMessage()    {}
func (*ApiGroupInvitableFriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_group_invitableFriends_bd215194d5a0aa95, []int{1}
}
func (m *ApiGroupInvitableFriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGroupInvitableFriendsResponse.Unmarshal(m, b)
}
func (m *ApiGroupInvitableFriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGroupInvitableFriendsResponse.Marshal(b, m, deterministic)
}
func (dst *ApiGroupInvitableFriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGroupInvitableFriendsResponse.Merge(dst, src)
}
func (m *ApiGroupInvitableFriendsResponse) XXX_Size() int {
	return xxx_messageInfo_ApiGroupInvitableFriendsResponse.Size(m)
}
func (m *ApiGroupInvitableFriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGroupInvitableFriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGroupInvitableFriendsResponse proto.InternalMessageInfo

func (m *ApiGroupInvitableFriendsResponse) GetList() []*core.PublicUserProfile {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ApiGroupInvitableFriendsResponse) GetListIsMute() map[string]bool {
	if m != nil {
		return m.ListIsMute
	}
	return nil
}

func (m *ApiGroupInvitableFriendsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ApiGroupInvitableFriendsRequest)(nil), "site.ApiGroupInvitableFriendsRequest")
	proto.RegisterType((*ApiGroupInvitableFriendsResponse)(nil), "site.ApiGroupInvitableFriendsResponse")
	proto.RegisterMapType((map[string]bool)(nil), "site.ApiGroupInvitableFriendsResponse.ListIsMuteEntry")
}

func init() {
	proto.RegisterFile("site/api_group_invitableFriends.proto", fileDescriptor_api_group_invitableFriends_bd215194d5a0aa95)
}

var fileDescriptor_api_group_invitableFriends_bd215194d5a0aa95 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x5d, 0x4b, 0xf3, 0x30,
	0x14, 0xc7, 0x69, 0xf7, 0xf2, 0x3c, 0xc6, 0x8b, 0x49, 0x14, 0x2d, 0xbb, 0xd0, 0x32, 0x10, 0x06,
	0x62, 0x0a, 0x0a, 0x22, 0x82, 0x17, 0x2a, 0x2a, 0x03, 0x85, 0x51, 0x51, 0x64, 0x0c, 0x46, 0xda,
	0x9d, 0x6d, 0x61, 0x59, 0x53, 0xf3, 0x32, 0xa9, 0x1f, 0xc0, 0x0f, 0xe7, 0xa7, 0x92, 0xa4, 0x73,
	0x8c, 0x81, 0x78, 0xd5, 0xf3, 0xff, 0xf7, 0xfc, 0xce, 0x5b, 0xd0, 0xa1, 0x62, 0x1a, 0x22, 0x9a,
	0xb3, 0xc1, 0x58, 0x0a, 0x93, 0x0f, 0x58, 0x36, 0x67, 0x9a, 0x26, 0x1c, 0xee, 0x24, 0x83, 0x6c,
	0xa8, 0x48, 0x2e, 0x85, 0x16, 0xb8, 0x6a, 0xd3, 0x9a, 0x8d, 0x54, 0x48, 0x88, 0x8c, 0x02, 0x59,
	0xda, 0x2d, 0x86, 0x0e, 0xae, 0x72, 0x76, 0x6f, 0xc9, 0xce, 0x1a, 0x18, 0xc3, 0x9b, 0x01, 0xa5,
	0x71, 0x80, 0xfe, 0xb9, 0xca, 0x9d, 0x61, 0xe0, 0x85, 0x5e, 0x7b, 0x23, 0xfe, 0x91, 0x78, 0x17,
	0xd5, 0xc5, 0x68, 0xa4, 0x40, 0x07, 0x7e, 0xe8, 0xb5, 0x6b, 0xf1, 0x42, 0xe1, 0x1d, 0x54, 0x4b,
	0x85, 0xc9, 0x74, 0x50, 0x71, 0x76, 0x29, 0x5a, 0x9f, 0x3e, 0x0a, 0x7f, 0xef, 0xa5, 0x72, 0x91,
	0x29, 0xc0, 0x47, 0xa8, 0xca, 0x99, 0xd2, 0x81, 0x17, 0x56, 0xda, 0x9b, 0x27, 0x7b, 0xc4, 0xce,
	0x4b, 0xba, 0x26, 0xe1, 0x2c, 0x7d, 0x56, 0x20, 0xbb, 0x52, 0x8c, 0x18, 0x87, 0xd8, 0x25, 0xe1,
	0x17, 0x84, 0xec, 0xb7, 0xa3, 0x1e, 0x8d, 0x86, 0xc0, 0x77, 0xc8, 0x19, 0xb1, 0x8b, 0x92, 0xbf,
	0x1a, 0x91, 0x87, 0x25, 0x78, 0x9b, 0x69, 0x59, 0xc4, 0x2b, 0x95, 0xf0, 0x3e, 0x42, 0x5a, 0x68,
	0xca, 0x6f, 0x56, 0x96, 0x58, 0x71, 0x9a, 0x97, 0xa8, 0xb1, 0x86, 0xe3, 0x2d, 0x54, 0x99, 0x42,
	0xb1, 0x38, 0x90, 0x0d, 0xed, 0x11, 0xe6, 0x94, 0x1b, 0x70, 0xb7, 0xf9, 0x1f, 0x97, 0xe2, 0xc2,
	0x3f, 0xf7, 0xae, 0x5f, 0xd1, 0x76, 0x2a, 0x66, 0xe4, 0x83, 0xf2, 0xa2, 0x7c, 0x05, 0x37, 0x72,
	0x2f, 0x1a, 0x33, 0x3d, 0x31, 0x09, 0x49, 0xc5, 0x2c, 0x1a, 0x9a, 0x74, 0x9a, 0x4e, 0xa8, 0x5e,
	0x06, 0xc7, 0x63, 0xaa, 0xe1, 0x9d, 0x16, 0x91, 0x03, 0x22, 0x0b, 0x7c, 0xf9, 0x8d, 0x1e, 0xe5,
	0x45, 0xbf, 0x6b, 0x9d, 0xfe, 0x13, 0xd3, 0x90, 0xd4, 0xdd, 0xdf, 0xd3, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x3a, 0x6a, 0x71, 0x14, 0x02, 0x00, 0x00,
}
