// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_friend_list.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/yayashanzei/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// action: api.friend.list
//
type ApiFriendListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiFriendListRequest) Reset()         { *m = ApiFriendListRequest{} }
func (m *ApiFriendListRequest) String() string { return proto.CompactTextString(m) }
func (*ApiFriendListRequest) ProtoMessage()    {}
func (*ApiFriendListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_list_7b4b0cf84f73ca52, []int{0}
}
func (m *ApiFriendListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendListRequest.Unmarshal(m, b)
}
func (m *ApiFriendListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendListRequest.Marshal(b, m, deterministic)
}
func (dst *ApiFriendListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendListRequest.Merge(dst, src)
}
func (m *ApiFriendListRequest) XXX_Size() int {
	return xxx_messageInfo_ApiFriendListRequest.Size(m)
}
func (m *ApiFriendListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendListRequest proto.InternalMessageInfo

func (m *ApiFriendListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ApiFriendListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ApiFriendListResponse struct {
	Friends              []*core.FriendUserProfile `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	TotalCount           int32                     `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ApiFriendListResponse) Reset()         { *m = ApiFriendListResponse{} }
func (m *ApiFriendListResponse) String() string { return proto.CompactTextString(m) }
func (*ApiFriendListResponse) ProtoMessage()    {}
func (*ApiFriendListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_friend_list_7b4b0cf84f73ca52, []int{1}
}
func (m *ApiFriendListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiFriendListResponse.Unmarshal(m, b)
}
func (m *ApiFriendListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiFriendListResponse.Marshal(b, m, deterministic)
}
func (dst *ApiFriendListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiFriendListResponse.Merge(dst, src)
}
func (m *ApiFriendListResponse) XXX_Size() int {
	return xxx_messageInfo_ApiFriendListResponse.Size(m)
}
func (m *ApiFriendListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiFriendListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiFriendListResponse proto.InternalMessageInfo

func (m *ApiFriendListResponse) GetFriends() []*core.FriendUserProfile {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *ApiFriendListResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ApiFriendListRequest)(nil), "site.ApiFriendListRequest")
	proto.RegisterType((*ApiFriendListResponse)(nil), "site.ApiFriendListResponse")
}

func init() {
	proto.RegisterFile("site/api_friend_list.proto", fileDescriptor_api_friend_list_7b4b0cf84f73ca52)
}

var fileDescriptor_api_friend_list_7b4b0cf84f73ca52 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0x6a, 0x2b, 0xc4, 0x43, 0x61, 0xad, 0xba, 0xf4, 0x20, 0xa5, 0xa7, 0x5e, 0x4c,
	0x50, 0x3f, 0x81, 0x7f, 0xf0, 0xe4, 0xa1, 0xac, 0x08, 0x52, 0x0a, 0x25, 0x4d, 0x67, 0xdb, 0xe8,
	0x76, 0x67, 0xcd, 0x4c, 0x90, 0xf5, 0x23, 0xfa, 0xa9, 0x24, 0x1b, 0x95, 0xd2, 0x5b, 0xe6, 0x37,
	0xef, 0x65, 0xde, 0x13, 0x43, 0xb2, 0x0c, 0x4a, 0xd7, 0x76, 0x51, 0x38, 0x0b, 0xd5, 0x6a, 0x51,
	0x5a, 0x62, 0x59, 0x3b, 0x64, 0x4c, 0x0f, 0xc3, 0x6e, 0xd8, 0x37, 0xe8, 0x40, 0x79, 0x02, 0x17,
	0xf1, 0xf8, 0x41, 0x0c, 0x6e, 0x6b, 0xfb, 0xd8, 0xca, 0x9f, 0x2c, 0x71, 0x0e, 0x1f, 0x1e, 0x88,
	0xd3, 0x33, 0xd1, 0xc3, 0xa2, 0x20, 0xe0, 0x2c, 0x19, 0x25, 0x93, 0x6e, 0xfe, 0x3b, 0xa5, 0x03,
	0xd1, 0x35, 0xe8, 0x2b, 0xce, 0x3a, 0x2d, 0x8e, 0xc3, 0xf8, 0x4d, 0x9c, 0xee, 0xfd, 0x42, 0x35,
	0x56, 0x04, 0xe9, 0x95, 0x38, 0x8a, 0x51, 0x28, 0x4b, 0x46, 0x07, 0x93, 0xe3, 0xeb, 0x73, 0x19,
	0x12, 0xc8, 0x28, 0x7d, 0x21, 0x70, 0x53, 0x87, 0x85, 0x2d, 0x21, 0xff, 0xd3, 0xa5, 0x17, 0x42,
	0x30, 0xb2, 0x2e, 0xef, 0x77, 0xce, 0xec, 0x90, 0xbb, 0x57, 0x71, 0x62, 0x70, 0x2b, 0xbf, 0x74,
	0xd9, 0xc4, 0x0e, 0x32, 0x34, 0x9b, 0xa9, 0xb5, 0xe5, 0x8d, 0x5f, 0x4a, 0x83, 0x5b, 0xb5, 0xf2,
	0xe6, 0xdd, 0x6c, 0x34, 0xff, 0x3f, 0x2e, 0xd7, 0x9a, 0xe1, 0x53, 0x37, 0xaa, 0x35, 0xa8, 0x60,
	0xf8, 0xee, 0xf4, 0x67, 0xba, 0x6c, 0xe6, 0xd3, 0x40, 0xe6, 0xcf, 0x96, 0x61, 0xd9, 0x6b, 0xb7,
	0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0x6b, 0x99, 0xbe, 0x47, 0x01, 0x00, 0x00,
}
