// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/api_passport_password_resetPassword.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
//
// reset password with the url send to your email.
//
// action: api.passport.password.resetPassword
//
//
type ApiPassportPasswordResetPasswordRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordResetPasswordRequest) Reset() {
	*m = ApiPassportPasswordResetPasswordRequest{}
}
func (m *ApiPassportPasswordResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordResetPasswordRequest) ProtoMessage()    {}
func (*ApiPassportPasswordResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_resetPassword_c52261f4a8538405, []int{0}
}
func (m *ApiPassportPasswordResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordResetPasswordRequest.Unmarshal(m, b)
}
func (m *ApiPassportPasswordResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordResetPasswordRequest.Merge(dst, src)
}
func (m *ApiPassportPasswordResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordResetPasswordRequest.Size(m)
}
func (m *ApiPassportPasswordResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordResetPasswordRequest proto.InternalMessageInfo

func (m *ApiPassportPasswordResetPasswordRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *ApiPassportPasswordResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ApiPassportPasswordResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ApiPassportPasswordResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiPassportPasswordResetPasswordResponse) Reset() {
	*m = ApiPassportPasswordResetPasswordResponse{}
}
func (m *ApiPassportPasswordResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ApiPassportPasswordResetPasswordResponse) ProtoMessage()    {}
func (*ApiPassportPasswordResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_passport_password_resetPassword_c52261f4a8538405, []int{1}
}
func (m *ApiPassportPasswordResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiPassportPasswordResetPasswordResponse.Unmarshal(m, b)
}
func (m *ApiPassportPasswordResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiPassportPasswordResetPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ApiPassportPasswordResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiPassportPasswordResetPasswordResponse.Merge(dst, src)
}
func (m *ApiPassportPasswordResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ApiPassportPasswordResetPasswordResponse.Size(m)
}
func (m *ApiPassportPasswordResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiPassportPasswordResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiPassportPasswordResetPasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiPassportPasswordResetPasswordRequest)(nil), "site.ApiPassportPasswordResetPasswordRequest")
	proto.RegisterType((*ApiPassportPasswordResetPasswordResponse)(nil), "site.ApiPassportPasswordResetPasswordResponse")
}

func init() {
	proto.RegisterFile("site/api_passport_password_resetPassword.proto", fileDescriptor_api_passport_password_resetPassword_c52261f4a8538405)
}

var fileDescriptor_api_passport_password_resetPassword_c52261f4a8538405 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x4f, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xa6, 0xf5, 0x07, 0xbb, 0x17, 0x61, 0xf5, 0x10, 0xc4, 0x83, 0xf4, 0x62, 0x11, 0xdc, 0x3d,
	0xf8, 0x04, 0xfa, 0x00, 0x12, 0xe2, 0x45, 0x4a, 0xa1, 0x4c, 0xb7, 0x43, 0xba, 0x34, 0xc9, 0xac,
	0xbb, 0x13, 0xca, 0xfa, 0x88, 0x3e, 0x95, 0x64, 0x9b, 0x44, 0x6f, 0xbd, 0x7d, 0xbf, 0xcc, 0x37,
	0x42, 0x05, 0xcb, 0xa8, 0xc1, 0xd9, 0xb5, 0x83, 0x10, 0x1c, 0x79, 0x4e, 0xe0, 0x40, 0x7e, 0xbb,
	0xf6, 0x18, 0x90, 0xf3, 0x9e, 0x29, 0xe7, 0x89, 0x49, 0x9e, 0x77, 0xf9, 0x79, 0x14, 0x8f, 0xaf,
	0xce, 0xe6, 0x7d, 0x63, 0x88, 0x14, 0xff, 0xf3, 0x05, 0x7e, 0xb5, 0x18, 0x58, 0xde, 0x8b, 0x59,
	0x45, 0xa5, 0x6d, 0xde, 0xa1, 0xc6, 0x6c, 0xf2, 0x30, 0x59, 0xcc, 0x8a, 0x3f, 0x41, 0xde, 0x8a,
	0x0b, 0xa6, 0x3d, 0x36, 0xd9, 0x34, 0x39, 0x47, 0x22, 0xef, 0xc4, 0xd5, 0x30, 0x22, 0x3b, 0x4b,
	0xc6, 0xc8, 0xe7, 0x4f, 0x62, 0x71, 0xfa, 0x74, 0x70, 0xd4, 0x04, 0x7c, 0xfb, 0x14, 0x37, 0x86,
	0x6a, 0xf5, 0x0d, 0x55, 0x3c, 0xce, 0x4f, 0xdf, 0x2e, 0x75, 0x69, 0x79, 0xd7, 0x6e, 0x94, 0xa1,
	0x5a, 0x6f, 0x5b, 0xb3, 0x37, 0x3b, 0xe0, 0x11, 0x3c, 0x97, 0xc0, 0x78, 0x80, 0xa8, 0x53, 0x41,
	0x77, 0x85, 0x9f, 0xe9, 0xf5, 0x12, 0xaa, 0xb8, 0xca, 0x3b, 0x65, 0xf5, 0x61, 0x19, 0x37, 0x97,
	0xc9, 0x7d, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xac, 0x29, 0x85, 0xd6, 0x3f, 0x01, 0x00, 0x00,
}
