// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/im_cts_message.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/duckchat/duckchat-gateway/proto/core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *：
// 	action: im.cts.message
type ImCtsMessageRequest struct {
	Message              *core.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImCtsMessageRequest) Reset()         { *m = ImCtsMessageRequest{} }
func (m *ImCtsMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ImCtsMessageRequest) ProtoMessage()    {}
func (*ImCtsMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_cts_message_e8e582daccfd5650, []int{0}
}
func (m *ImCtsMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImCtsMessageRequest.Unmarshal(m, b)
}
func (m *ImCtsMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImCtsMessageRequest.Marshal(b, m, deterministic)
}
func (dst *ImCtsMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImCtsMessageRequest.Merge(dst, src)
}
func (m *ImCtsMessageRequest) XXX_Size() int {
	return xxx_messageInfo_ImCtsMessageRequest.Size(m)
}
func (m *ImCtsMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImCtsMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImCtsMessageRequest proto.InternalMessageInfo

func (m *ImCtsMessageRequest) GetMessage() *core.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*ImCtsMessageRequest)(nil), "site.ImCtsMessageRequest")
}

func init() {
	proto.RegisterFile("site/im_cts_message.proto", fileDescriptor_im_cts_message_e8e582daccfd5650)
}

var fileDescriptor_im_cts_message_e8e582daccfd5650 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xce, 0x2c, 0x49,
	0xd5, 0xcf, 0xcc, 0x8d, 0x4f, 0x2e, 0x29, 0x8e, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x49, 0x09, 0x25, 0xe7, 0x17, 0xa5, 0xea,
	0xa3, 0xc8, 0x28, 0xd9, 0x71, 0x09, 0x7b, 0xe6, 0x3a, 0x97, 0x14, 0xfb, 0x42, 0x44, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xd4, 0xb9, 0xd8, 0xa1, 0xea, 0x24, 0x18, 0x15, 0x18, 0x35,
	0xb8, 0x8d, 0x78, 0xf5, 0x40, 0x9a, 0xf5, 0x60, 0xca, 0x60, 0xb2, 0x4e, 0x11, 0x5c, 0xc2, 0xc9,
	0xf9, 0xb9, 0x7a, 0x55, 0x89, 0x39, 0x95, 0x10, 0x13, 0xf5, 0x40, 0x56, 0x45, 0xe9, 0xa7, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x94, 0x26, 0x67, 0x27, 0x67, 0x24,
	0x96, 0xc0, 0x19, 0xba, 0xe9, 0x89, 0x25, 0xa9, 0xe5, 0x89, 0x95, 0xfa, 0x60, 0x0d, 0xfa, 0x20,
	0x0d, 0xa7, 0x98, 0xf8, 0xa3, 0x12, 0x73, 0x2a, 0x63, 0x02, 0x40, 0x22, 0x31, 0xc1, 0x99, 0x25,
	0xa9, 0x49, 0x6c, 0x60, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x23, 0x7c, 0x31,
	0xd7, 0x00, 0x00, 0x00,
}
