// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site/im_cts_ping.proto

package site // import "github.com/duckchat/duckchat-gateway/proto/site"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// No parameters are required.
type ImCtsPingRequest struct {
	Random               string   `protobuf:"bytes,1,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImCtsPingRequest) Reset()         { *m = ImCtsPingRequest{} }
func (m *ImCtsPingRequest) String() string { return proto.CompactTextString(m) }
func (*ImCtsPingRequest) ProtoMessage()    {}
func (*ImCtsPingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_cts_ping_88fb89299e2e0e34, []int{0}
}
func (m *ImCtsPingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImCtsPingRequest.Unmarshal(m, b)
}
func (m *ImCtsPingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImCtsPingRequest.Marshal(b, m, deterministic)
}
func (dst *ImCtsPingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImCtsPingRequest.Merge(dst, src)
}
func (m *ImCtsPingRequest) XXX_Size() int {
	return xxx_messageInfo_ImCtsPingRequest.Size(m)
}
func (m *ImCtsPingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImCtsPingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImCtsPingRequest proto.InternalMessageInfo

func (m *ImCtsPingRequest) GetRandom() string {
	if m != nil {
		return m.Random
	}
	return ""
}

func init() {
	proto.RegisterType((*ImCtsPingRequest)(nil), "site.ImCtsPingRequest")
}

func init() { proto.RegisterFile("site/im_cts_ping.proto", fileDescriptor_im_cts_ping_88fb89299e2e0e34) }

var fileDescriptor_im_cts_ping_88fb89299e2e0e34 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xce, 0x2c, 0x49,
	0xd5, 0xcf, 0xcc, 0x8d, 0x4f, 0x2e, 0x29, 0x8e, 0x2f, 0xc8, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x2b, 0x69, 0x71, 0x09, 0x78, 0xe6, 0x3a, 0x97, 0x14, 0x07,
	0x64, 0xe6, 0xa5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71, 0xb1, 0x15, 0x25,
	0xe6, 0xa5, 0xe4, 0xe7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x4e, 0x11, 0x5c,
	0xc2, 0xc9, 0xf9, 0xb9, 0x7a, 0x55, 0x89, 0x39, 0x95, 0x10, 0x33, 0xf4, 0x40, 0x46, 0x44, 0xe9,
	0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x94, 0x26, 0x67, 0x27,
	0x67, 0x24, 0x96, 0xc0, 0x19, 0xba, 0xe9, 0x89, 0x25, 0xa9, 0xe5, 0x89, 0x95, 0xfa, 0x60, 0x0d,
	0xfa, 0x20, 0x0d, 0xa7, 0x98, 0xf8, 0xa3, 0x12, 0x73, 0x2a, 0x63, 0x02, 0x40, 0x22, 0x31, 0xc1,
	0x99, 0x25, 0xa9, 0x49, 0x6c, 0x60, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x3c,
	0x1f, 0x25, 0xac, 0x00, 0x00, 0x00,
}
